### ISSUE TITLE
Paella Player breaks CI builds on develop

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast#1123]
Building `opencast-engage-paella-player` on `develop` fails on both [Travis CI](https://api.travis-ci.org/v3/job/594329191/log.txt) and [buildbot](http://ci.opencast.org/#/builders/10/builds/3263/steps/4/logs/build), breaking the CI.

```

[INFO] --- frontend-maven-plugin:1.7.6:gulp (gulp build) @ opencast-engage-paella-player ---
[INFO] Running 'gulp.js paella-opencast:build' in /builds/Pull_Request_Build/build/modules/engage-paella-player
[INFO] [16:52:02] Using gulpfile /builds/Pull_Request_Build/build/modules/engage-paella-player/gulpfile.js
[INFO] [16:52:02] Starting 'paella-opencast:build'...
[INFO] [16:52:02] Starting 'paella-opencast:compile.debug'...
[INFO] [16:52:02] Starting 'paella-opencast:prepare'...
[INFO] [16:52:02] Starting 'paella-opencast:prepare:source'...
[INFO] [16:52:03] Finished 'paella-opencast:prepare:source' after 946 ms
[INFO] [16:52:03] Starting '<anonymous>'...
[WARNING] npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
[INFO] 
[INFO] > chromedriver@76.0.1 install /builds/Pull_Request_Build/build/modules/engage-paella-player/target/gulp/paella/node_modules/chromedriver
[INFO] > node install.js
[INFO] 
[INFO] ChromeDriver binary exists. Validating...
[INFO] ChromeDriver 76.0.3809.126 (d80a294506b4c9d18015e755cee48f953ddc3f2f-refs/branch-heads/3809@{#1024})
[INFO] 
[INFO] ChromeDriver is already available at '/tmp/76.0.3809.126/chromedriver/chromedriver'.
[INFO] Copying to target path /builds/Pull_Request_Build/build/modules/engage-paella-player/target/gulp/paella/node_modules/chromedriver/lib/chromedriver
[INFO] Fixing file permissions
[INFO] Done. ChromeDriver binary available at /builds/Pull_Request_Build/build/modules/engage-paella-player/target/gulp/paella/node_modules/chromedriver/lib/chromedriver/chromedriver
[INFO] 
[INFO] > core-js@2.6.9 postinstall /builds/Pull_Request_Build/build/modules/engage-paella-player/target/gulp/paella/node_modules/core-js
[INFO] > node scripts/postinstall || echo "ignore"
[INFO] 
[INFO] Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
[INFO] 
[INFO] The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
[INFO] > https://opencollective.com/core-js 
[INFO] > https://www.patreon.com/zloirock 
[INFO] 
[INFO] Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
[INFO] 
[ERROR] npm notice created a lockfile as package-lock.json. You should commit this file.
[WARNING] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
[WARNING] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
[ERROR] 
[INFO] added 768 packages from 967 contributors and audited 9085 packages in 17.833s
[INFO] found 0 vulnerabilities
[INFO] 
[INFO] [16:52:21] Finished '<anonymous>' after 19 s
[INFO] [16:52:21] Finished 'paella-opencast:prepare' after 19 s
[INFO] [16:52:21] Starting '<anonymous>'...
[ERROR] [16:52:25] '<anonymous>' errored after 3.64 s
[ERROR] [16:52:25] Error: 1
[ERROR]     at formatError (/builds/Pull_Request_Build/build/modules/engage-paella-player/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^4.0.0/format-error.js:21:10)
[ERROR]     at Gulp.<anonymous> (/builds/Pull_Request_Build/build/modules/engage-paella-player/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^4.0.0/log/events.js:33:15)
[ERROR]     at Gulp.emit (events.js:203:15)
[ERROR]     at Gulp.EventEmitter.emit (domain.js:448:20)
[ERROR]     at Object.error (/builds/Pull_Request_Build/build/modules/engage-paella-player/node_modules/undertaker/lib/helpers/createExtensions.js:61:10)
[ERROR]     at handler (/builds/Pull_Request_Build/build/modules/engage-paella-player/node_modules/now-and-later/lib/mapSeries.js:47:14)
[ERROR]     at f (/builds/Pull_Request_Build/build/modules/engage-paella-player/node_modules/once/once.js:25:25)
[ERROR]     at f (/builds/Pull_Request_Build/build/modules/engage-paella-player/node_modules/once/once.js:25:25)
[ERROR]     at tryCatch (/builds/Pull_Request_Build/build/modules/engage-paella-player/node_modules/async-done/index.js:24:15)
[ERROR]     at done (/builds/Pull_Request_Build/build/modules/engage-paella-player/node_modules/async-done/index.js:40:12)
[ERROR] [16:52:25] 'paella-opencast:compile.debug' errored after 23 s
[ERROR] [16:52:25] 'paella-opencast:build' errored after 23 s
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[…]
[INFO] Opencast :: engage-paella-player ................... FAILURE [ 43.373 s]
[…]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 09:06 min
[INFO] Finished at: 2019-10-06T16:52:25+00:00
[INFO] Final Memory: 285M/1379M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.7.6:gulp (gulp build) on project opencast-engage-paella-player: Failed to run task: 'gulp.js paella-opencast:build' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :opencast-engage-paella-player
program finished with exit code 1
```

**Comment by karendolan** [comment]
@lkiesow I do not know if this is related. I'm getting an error from the paella gulp trying to find a missing lunr.min.js. I am manually bypassing the error locally by modifying the modules/engage-paella/node_modules/paellaplayer/package.json  dependency  "lunr": "^2.3.6", to  "lunr": "2.3.6".

24 hours ago lunr published 2.3.7 to npmjs. The lunr.js 2.3.6 tag git repo does not contain a lunr.min.js, so I don't know why it's being pulled down in the 2.3.6 npmjs package. It doesn't exist in the 2.3.7 npmjs package.

Maybe the lunr.min.js was published by accident in 2.3.6, but the file was never checked into the lunr.js github rep,o so it was forgotten when 2.3.7 was published... (i.e "[With npm pubish] All files in the package directory are included if no local .gitignore or .npmignore file exists". It's easy to npm publish artifacts from your local workspace that are not checked into github. https://docs.npmjs.com/cli/publish )

[EDIT] I created a ticket for the lunr.js repo https://github.com/olivernn/lunr.js/issues/420

**Comment by gregorydlogan** [comment]
Ah, this explains the error emails I've been getting from Buildbot.  Speaking of which, those should be going to dev@.  This will be fixed soonish.

**Comment by karendolan** [comment]
@lkiesow and @gregorydlogan 
(1)  I notice that the engage-paella-player/node_modules/paellaplayer is not pulling down the paella player's package-lock.json via the eirslet's npm install. Paella 6.2.2's package-local.json that exists in the targeted repo: https://github.com/polimediaupv/paella/tree/6.2.2
I can't figure out why it would ignore that file. I see that it pulls down the package-lock.json for needle (node_modules//fsevents/node_modules/needle/package-lock.json). [EDIT] (opps, that's fsevents node_module dependency... not direct depenency)

(2) If paella 6.2.2's lock file was pulled down by the erslett's npm, the engage-paella-player/gulpfile.js  npm "install" gulp task could be changed to npm "ci" which will honor the lock file's versions with target lunr 2.3.6 (vs 2.3.7 with the missing min file). I'm reading  that npm "install" after v5.1 ignores the lock file and creates a new one based on the package.json wiggle room. The new-ish "npm ci" is required in order to honor the lock file's locked versions.

**Comment by gregorydlogan** [comment]
This also affects `r/8.x`

**Comment by karendolan** [comment]
More FYI  regarding the missing package-lock.json in node_modules/paellaplayer and ability to lock down versions Paella Player's dependencies. I'm going to test with a npm-shrinkwrap.json file "which is essentially the same file, but allows publication".

> "One key detail about package-lock.json is that it cannot be published, and it will be ignored if found in any place other than the toplevel package. It shares a format with npm-shrinkwrap.json, which is essentially the same file, but allows publication. This is not recommended unless deploying a CLI tool or otherwise using the publication process for producing production packages."
https://docs.npmjs.com/files/package-lock.json
