### ISSUE TITLE
Dataloader is non-functional

### ISSUE THREAD

**Issue by gregorydlogan** [opencast/opencast#1140]
Per https://opencast.jira.com/browse/MH-13011

Description:
Old code that used to be useful, no one uses it now.  Let's remove it.

Steps to reproduce:
1. Attempt to use the dataloader

Actual Results:
`org.opencastproject.dataloader.testdata=true` does nothing. The correct key in the code is `org.opencastproject.security.demo.loadusers`. Once that's used, you see an error about an unset organization context.

Expected Results:
A bunch of test users and groups

Stack trace:
```
karaf@root>Exception in thread "Thread-33" java.lang.IllegalStateException: No organization is set in security context
at org.opencastproject.kernel.security.SecurityServiceSpringImpl.getUser(SecurityServiceSpringImpl.java:93)
at org.opencastproject.userdirectory.utils.UserDirectoryUtils.isCurrentUserAuthorizedHandleRoles(UserDirectoryUtils.java:52)
at org.opencastproject.userdirectory.JpaUserAndRoleProvider.addUser(JpaUserAndRoleProvider.java:282)
at org.opencastproject.dataloader.UserAndSeriesLoader.loadLdapUser(UserAndSeriesLoader.java:312)
at org.opencastproject.dataloader.UserAndSeriesLoader$Loader.run(UserAndSeriesLoader.java:207)
```

**Comment by lkiesow** [comment]
There is no dataloader any longer in Opencast. It has been removed a while ago.
