### ISSUE TITLE
Preview extraction fails on short videos

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast#1219]
When ingesting a video with a length shorter than 5s, the extraction of a preview image will fail due to the configuration of the default workflow.

**Comment by lkiesow** [comment]
```
2020-01-05 02:12:18,761 | ERROR | (AbstractJobProducer$JobRunner:344) - Error handling operation 'Image': org.opencastproject.serviceregistry.api.ServiceRegistryException: Error handling operation 'Image'                                  
        at org.opencastproject.composer.impl.ComposerServiceImpl.process(ComposerServiceImpl.java:1530)                                                                                                                                       
        at org.opencastproject.job.api.AbstractJobProducer$JobRunner.call(AbstractJobProducer.java:314)                                                                                                                                       
        at org.opencastproject.job.api.AbstractJobProducer$JobRunner.call(AbstractJobProducer.java:273)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.opencastproject.composer.api.EncoderException: An image could not be extracted from the track http://localhost:8080/files/mediapackage/9bf975ce-67ad-406a-9193-9e0807c13d20/f7544c6d-69c2-4943-85e5-9b66432b0a5c/0_5s.mp4 with 
id f7544c6d-69c2-4943-85e5-9b66432b0a5c because the extraction time (1.0 second(s)) is outside of the track's duration (0.535 second(s))
        at org.opencastproject.composer.impl.ComposerServiceImpl.image(ComposerServiceImpl.java:1121)
        at org.opencastproject.composer.impl.ComposerServiceImpl.process(ComposerServiceImpl.java:1422)
        ... 6 more

```
