### ISSUE TITLE
Distribution to S3 fails

### ISSUE THREAD

**Issue by edalex-tom** [opencast/opencast#1253]
**Describe the bug**
As part of a workflow with Amazon S3 integration, publish fails with a null pointer exception.

**To Reproduce**
In a Opencast environment with default tenant:

1. [Configure Amazon S3 Distribution](https://docs.opencast.org/r/7.x/admin/#modules/awss3distribution/#aws-s3-distribution-configuration)
2. [Add publish to S3 operation to workflow](https://docs.opencast.org/r/7.x/admin/#workflowoperationhandlers/publish-aws-woh/)
3. Add event through admin UI or via Opencast external API
4. Assets (transcoded videos) are uploaded to S3 bucket
5. Event marked as failure with details highlighting a null pointer exception

```
INFO  | (PublishEngageWorkflowOperationHandler:357) - Publishing media package 642ac347-8a17-4289-bcf1-4e9c9695a3fd to search index
ERROR | (WorkflowOperationWorker:180) - Workflow operation 'operation:'publish-aws', position:9, state:'FAILED'' failed
java.lang.NullPointerException: null
   at org.opencastproject.workflow.handler.distribution.PublishEngageWorkflowOperationHandler.start(PublishEngageWorkflowOperationHandler.java:360) ~[?:?]
   at org.opencastproject.workflow.impl.WorkflowOperationWorker.start(WorkflowOperationWorker.java:233) ~[194:opencast-workflow-service-impl:7.4.0]
   at org.opencastproject.workflow.impl.WorkflowOperationWorker.execute(WorkflowOperationWorker.java:155) [194:opencast-workflow-service-impl:7.4.0]
   at org.opencastproject.workflow.impl.WorkflowServiceImpl.runWorkflowOperation(WorkflowServiceImpl.java:848) [194:opencast-workflow-service-impl:7.4.0]
```

**Environment Information**

- OS: Ubuntu 18.04
- Opencast version: 7.4, 8.x, bug is not present in 6.6

**Comment by gregorydlogan** [comment]
@edalex-tom Fixed in #1270.  If you've got the resources, testing would be welcome.

**Comment by edalex-tom** [comment]
Hi @gregorydlogan, thanks for having a look.  Unfortunately I won't have a chance to revisit this again in the near future.

**Comment by karendolan** [comment]
Pull https://github.com/opencast/opencast/pull/1270 merged, resolves AWS publish fix regarding "MH-13381, Use Organization Identifier in Workflows"
