### ISSUE TITLE
An admin closing their browser during upload should not ERROR the Ingest Service

### ISSUE THREAD

**Issue by gregorydlogan** [opencast/opencast#1306]
As reported on list, the following stack trace appears if you close your browser or otherwise lose connection mid upload.

```
2019-11-27T18:18:53,963 | INFO | (IngestServiceImpl:647) - Created mediapackage 58c51d73-97d4-482d-9f6e-80978a4b6bc4
2019-11-27T18:18:54,153 | INFO | (IngestServiceImpl:760) - Start adding track d5714bc0-36b3-4837-b9a0-0e1f134b2e60 from input stream on mediapackage 58c51d73-97d4-482d-9f6e-80978a4b6bc4
2019-11-27T18:39:21,339 | INFO | (ServiceRegistryJpaImpl:2501) - State set to WARNING for current service org.opencastproject.ingest on host https://admin.opencast.de
2019-11-27T18:39:21,364 | ERROR | (IndexServiceImpl:555) - Unable to create event: java.io.IOException: java.util.concurrent.TimeoutException: Idle timeout expired: 30000/30000 ms
at org.eclipse.jetty.server.HttpInput$ErrorState.noContent(HttpInput.java:1080)
at org.eclipse.jetty.server.HttpInput.read(HttpInput.java:313)
at org.apache.commons.fileupload.MultipartStream$ItemInputStream.makeAvailable(MultipartStream.java:1027)
at org.apache.commons.fileupload.MultipartStream$ItemInputStream.read(MultipartStream.java:931)
at org.apache.commons.io.input.ProxyInputStream.read(ProxyInputStream.java:99)
at org.opencastproject.util.ProgressInputStream.read(ProgressInputStream.java:84)
at java.security.DigestInputStream.read(DigestInputStream.java:161)
at java.io.FilterInputStream.read(FilterInputStream.java:107)
```

This puts the ingest service into ERROR state, and prevents normal operations.

**Comment by gregorydlogan** [comment]
Initial investigation (in r/7.x):

- private addContentToRepo creates a ProgressInputStream, which does the actual fetch during the call to workingFileRepository.put at the end of the method.
- Catching the IOException at this point means coming up with some kind of error URI which can be returned, rather than throwing an exception -> bad form.
- Catching the IOException in the calling method (ie, addTrack, etc) means we have to handle it in multiple places, and *also* have to decide what to return from that method.  Do we return the input, unmodified mediapackage?  This breaks the API IMO.  But if we throw an error then we have a bunch of reworking to do.
* The TimeoutException is *not* thrown, it is the message inside the IOException.  We can check if the IOException's message contains TimeoutException, but can't directly catch the timeout :(
