### ISSUE TITLE
Error when Opencast tries to create org.apache.karaf.shell.cfg

### ISSUE THREAD

**Issue by mliradelc** [opencast/opencast#1372]
**Describe the bug**
When opencast is started, this message appears:

```bash
2020-01-20T10:52:55,290 | WARN  | (FeatureConfigInstaller:130) - Can't update cfg file
java.io.FileNotFoundException: /etc/opencast/org.apache.karaf.shell.cfg (Keine Berechtigung)
	at java.io.FileOutputStream.open0(Native Method) ~[?:1.8.0_232]
	at java.io.FileOutputStream.open(FileOutputStream.java:270) ~[?:1.8.0_232]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213) ~[?:1.8.0_232]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162) ~[?:1.8.0_232]
	at org.apache.felix.utils.properties.Properties.save(Properties.java:153) ~[org.apache.karaf.main-4.2.7.jar:4.2.7]
	at org.apache.felix.utils.properties.TypedProperties.save(TypedProperties.java:106) ~[org.apache.karaf.main-4.2.7.jar:4.2.7]
	at org.apache.karaf.features.internal.service.FeatureConfigInstaller.updateStorage(FeatureConfigInstaller.java:293) ~[?:?]
	at org.apache.karaf.features.internal.service.FeatureConfigInstaller.installFeatureConfigs(FeatureConfigInstaller.java:128) ~[?:?]
	at org.apache.karaf.features.internal.service.BundleInstallSupportImpl.installConfigs(BundleInstallSupportImpl.java:301) ~[?:?]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.installConfigs(FeaturesServiceImpl.java:1178) ~[?:?]
	at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:955) ~[?:?]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1062) ~[?:?]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:998) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_232]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
```

The problem is that opencast tries to generate the file `org.apache.karaf.shell.cfg` on the folder. The RPM installation creates a user called "opencast" that doesn't have the authorization to write in the system folders. **That is ok.**

The rpm packet should include this file to avoid this error. 

**workaround**
Allow `opencast` user to write in the system folder. That solves the issue but lefts a security issue in the server.
**To Reproduce**
1. Start opencast

**Environment Information**
 - OS: CentOS 7
 - Browser Safari
 - Opencast version 9 branch develop

**Comment by lkiesow** [comment]
Hi Max, there exists no Opencast 9 RPM yet, so this is just a local problem with your packageing, isn't it? Hence, this is no community issue, is it?

**Comment by mliradelc** [comment]
You are right Lars, there are not OC 9 RPM packages yet. I have built the develop branch myself, I notice this will be a problem in the future because that file should be in /etc/ folder in the repo.

**Comment by lkiesow** [comment]
In that case, it will be my responsibility when I'm building this and I'm aware of that since it's nothing new :-)
