### ISSUE TITLE
WebM-Videos from Opencast Studio will not be processed with schedule-and-upload workflow

### ISSUE THREAD

**Issue by rrolf** [opencast/opencast#1384]
**Describe the bug**
Use Opencast Studio and upload the video to an Opencast with the schedule-and-upload workflow selected. 
The processing will fail in the "image" operation with the following error:

```
2020-02-01 13:28:21,643 | ERROR | (WorkflowOperationWorker:141) - Workflow operation 'operation:'image', position:17, state:'FAILED'' failed
org.opencastproject.workflow.api.WorkflowOperationException: Track https://oc-test.virtuos.uni-osnabrueck.de/files/mediapackage/6269562a-8cc0-4190-aea5-c5b8137e653e/f76dea5f-2ad4-4969-bca7-d20222e1cda1/presenter_video___recording__1_.webm cannot tell its duration
	at org.opencastproject.workflow.handler.composer.ImageWorkflowOperationHandler$6.apply(ImageWorkflowOperationHandler.java:484) ~[?:?]
	at org.opencastproject.workflow.handler.composer.ImageWorkflowOperationHandler$6.apply(ImageWorkflowOperationHandler.java:481) ~[?:?]
	at com.entwinemedia.fn.StreamOp$35$1.apply(StreamOp.java:483) ~[27:functional:1.4.2]
	at com.entwinemedia.fn.StreamOp$Iterate.hasNext(StreamOp.java:668) ~[27:functional:1.4.2]
	at com.entwinemedia.fn.data.ListBuilderUtils.fillAndFinish(ListBuilderUtils.java:112) ~[27:functional:1.4.2]
	at com.entwinemedia.fn.data.ListBuilderUtils.createNew(ListBuilderUtils.java:64) ~[27:functional:1.4.2]
	at com.entwinemedia.fn.data.ImmutableLooseListBuilder.mk(ImmutableLooseListBuilder.java:62) ~[27:functional:1.4.2]
	at com.entwinemedia.fn.Stream.toList(Stream.java:400) ~[27:functional:1.4.2]
	at com.entwinemedia.fn.Stream.toList(Stream.java:394) ~[27:functional:1.4.2]
	at org.opencastproject.workflow.handler.composer.ImageWorkflowOperationHandler.configure(ImageWorkflowOperationHandler.java:487) ~[?:?]
	at org.opencastproject.workflow.handler.composer.ImageWorkflowOperationHandler.start(ImageWorkflowOperationHandler.java:142) ~[?:?]
	at org.opencastproject.workflow.impl.WorkflowOperationWorker.start(WorkflowOperationWorker.java:193) ~[209:opencast-workflow-service-impl:8.1.0]
	at org.opencastproject.workflow.impl.WorkflowOperationWorker.execute(WorkflowOperationWorker.java:116) [209:opencast-workflow-service-impl:8.1.0]
	at org.opencastproject.workflow.impl.WorkflowServiceImpl.runWorkflowOperation(WorkflowServiceImpl.java:784) [209:opencast-workflow-service-impl:8.1.0]
	at org.opencastproject.workflow.impl.WorkflowServiceImpl.process(WorkflowServiceImpl.java:1806) [209:opencast-workflow-service-impl:8.1.0]
	at org.opencastproject.workflow.impl.WorkflowServiceImpl$JobRunner.call(WorkflowServiceImpl.java:2234) [209:opencast-workflow-service-impl:8.1.0]
	at org.opencastproject.workflow.impl.WorkflowServiceImpl$JobRunner.call(WorkflowServiceImpl.java:2200) [209:opencast-workflow-service-impl:8.1.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]

```
**To Reproduce**
1. Go to https://studio.opencast.org
2. Click on 'Settings' and replace the workflow with schedule-and-upload
3. Make a recording
4. Check the processing of the recording

**Comment by rrolf** [comment]
It is the editor.thumbnail.preview that is called in the image operation.
profile.editor.thumbnail.preview.ffmpeg.command = -ss #{time} -i #{in.video.path} -r 1 -frames:v 1 -filter:v yadif,scale=320:-1 #{out.dir}/#{out.name}#{out.suffix}

**Comment by rrolf** [comment]
Timelinepreview and video-segmenter also fail with webM videos

**Comment by lkiesow** [comment]
The workflow does succeed by now since the linked patches are merged
