### ISSUE TITLE
OC Studio recordings do not support editing properly

### ISSUE THREAD

**Issue by gregorydlogan** [opencast/opencast#1525]
**Describe the bug**
Current description on list is to set `skipEditorPreview` to `false` to enable editing.  While this *does* enable the editing suite, the videos cannot be properly edited because the editing workflow assumes the presence of `*/work` flavoured media - something that the studio workflow does not currently produce.

**To Reproduce**
1. Edit the OC studio workflow to enable editing
2. Go to studio, make a recording and upload it
2. Processing...
3. Edit the video
4. See error:

```
2020-04-15T14:39:40,893 | ERROR | (WorkflowOperationWorker:143) - Workflow operation 'operation:'editor', position:6, state:'FAILED'' failed
org.opencastproject.workflow.api.WorkflowOperationException: No source tracks found in mediapacksge 4cfc4f79-210f-4741-9f81-b36ac0bd979d with flavors */work.
        at org.opencastproject.workflow.handler.videoeditor.VideoEditorWorkflowOperationHandler.resume(VideoEditorWorkflowOperationHandler.java:407) ~[?:?]
        at org.opencastproject.workflow.handler.videoeditor.VideoEditorWorkflowOperationHandler.start(VideoEditorWorkflowOperationHandler.java:294) ~[?:?]
        at org.opencastproject.workflow.impl.WorkflowOperationWorker.start(WorkflowOperationWorker.java:193) ~[210:opencast-workflow-service-impl:8.3.0]
        at org.opencastproject.workflow.impl.WorkflowOperationWorker.execute(WorkflowOperationWorker.java:116) [210:opencast-workflow-service-impl:8.3.0]
        at org.opencastproject.workflow.impl.WorkflowServiceImpl.runWorkflowOperation(WorkflowServiceImpl.java:784) [210:opencast-workflow-service-impl:8.3.0]
        at org.opencastproject.workflow.impl.WorkflowServiceImpl.process(WorkflowServiceImpl.java:1806) [210:opencast-workflow-service-impl:8.3.0]
        at org.opencastproject.workflow.impl.WorkflowServiceImpl$JobRunner.call(WorkflowServiceImpl.java:2234) [210:opencast-workflow-service-impl:8.3.0]
        at org.opencastproject.workflow.impl.WorkflowServiceImpl$JobRunner.call(WorkflowServiceImpl.java:2200) [210:opencast-workflow-service-impl:8.3.0]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]

```

**Comment by lkiesow** [comment]
Should be fixed by now given that you configure Studio to publish to the editor though usually, the Studio-Editor should be sufficient.
