### ISSUE TITLE
Heartbeat checks can cause processing slowdowns in some environments

### ISSUE THREAD

**Issue by gregorydlogan** [opencast/opencast#1538]
**Describe the bug**
In a cluster with workers inaccessible from the presentation node, errors like this are observed with current default settings:
```
2020-04-19T07:05:11,428 | WARN  | (ServiceRegistryJpaImpl$JobProducerHeartbeat:3405) - Added org.opencastproject.caption@http://worker.myopencast.de to the watch list
2020-04-19T07:06:11,446 | WARN  | (ServiceRegistryJpaImpl$JobProducerHeartbeat:3394) - Unable to reach org.opencastproject.composer@http://worker.myopencast.de : {}
org.opencastproject.security.api.TrustedHttpClientException: org.apache.http.conn.ConnectTimeoutException: Connect to worker.myopencast.de:80 timed out
        at org.opencastproject.kernel.security.TrustedHttpClientImpl.execute(TrustedHttpClientImpl.java:394) ~[?:?]
        at org.opencastproject.kernel.security.TrustedHttpClientImpl.execute(TrustedHttpClientImpl.java:346) ~[?:?]
        at org.opencastproject.serviceregistry.impl.ServiceRegistryJpaImpl$JobProducerHeartbeat.run(ServiceRegistryJpaImpl.java:3366) [91:opencast-serviceregistry:7.6.0]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]
Caused by: org.apache.http.conn.ConnectTimeoutException: Connect to worker.myopencast.de:80 timed out
        at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:123) ~[?:?]
        at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180) ~[?:?]
        at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:326) ~[?:?]
        at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:605) ~[?:?]
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:440) ~[?:?]
        at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:835) ~[?:?]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[?:?]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108) ~[?:?]
        at org.opencastproject.kernel.http.impl.HttpClientImpl.execute(HttpClientImpl.java:77) ~[?:?]
        at org.opencastproject.kernel.security.TrustedHttpClientImpl.execute(TrustedHttpClientImpl.java:387) ~[?:?]
        ... 9 more
2020-04-19T07:06:11,447 | INFO  | (ServiceRegistryJpaImpl:1475) - Unregistering Service org.opencastproject.composer@http://worker.myopencast.de and cleaning its running jobs
2020-04-19T07:06:11,521 | WARN  | (ServiceRegistryJpaImpl$JobProducerHeartbeat:3402) - Marking org.opencastproject.composer@http://worker.myopencast.de as offline
2020-04-19T07:07:11,563 | WARN  | (ServiceRegistryJpaImpl$JobProducerHeartbeat:3394) - Unable to reach org.opencastproject.coverimage@http://worker.myopencast.de : {}
org.opencastproject.security.api.TrustedHttpClientException: org.apache.http.conn.ConnectTimeoutException: Connect to worker.myopencast.de:80 timed out
        at org.opencastproject.kernel.security.TrustedHttpClientImpl.execute(TrustedHttpClientImpl.java:394) ~[?:?]
        at org.opencastproject.kernel.security.TrustedHttpClientImpl.execute(TrustedHttpClientImpl.java:346) ~[?:?]
        at org.opencastproject.serviceregistry.impl.ServiceRegistryJpaImpl$JobProducerHeartbeat.run(ServiceRegistryJpaImpl.java:3366) [91:opencast-serviceregistry:7.6.0]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]
Caused by: org.apache.http.conn.ConnectTimeoutException: Connect to worker.myopencast.de:80 timed out
        at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:123) ~[?:?]
```

This is caused by the heartbeat check being at its default of 60 seconds on all nodes.  This check is normally fine, except when the connection graph is not complete - some of the nodes are only accessible from other nodes.  In this situation the heartbeat fails on some of the nodes, which should knock them offline until the next heartbeat (which is likely to be almost immediate, but who knows).  Further to that, the only node whose heartbeat information actually matters is admin, since it's doing the dispatching.  Whether node A can talk to node B is irrelevant as long as admin can talk to both.

I see two solutions here:

- Update the documentation to turn the heartbeat checks off for non-admin nodes
- Update the service registry code to tie heartbeat checks and dispatching to the (same?) interval
  - We could also just disable heartbeat checks if dispatching is disabled, but otherwise leave things as they are too

Reported by Dietmar Zenker and Matthias Vollroth on the users list.

**Comment by lkiesow** [comment]
generally, it's a user error if nodes cannot reach each other and I immediately know of two other cases where this could cause errors. So, it's basically a “sorry but your configuration is broken”.

That said, `+1` for disabling the heartbeat on all nodes where dispatching is disabled (dispatch interval set to 0) which means that it is usually only activated on the admin node. The reason for the `+1` is that we have seen smaller problems in the past when a node could temporarily not reach another one. That change should be easy enough.

**Comment by gregorydlogan** [comment]
Known cases as discussed on IRC:
- Remotes talk directly to impls
- WFR might need to talk
- Availability checks in WOHs might need to talk

**Comment by Arnei** [comment]
@gregorydlogan Did #7311, which was made to address #6706, also address this issue? Is there more that should be done here?

**Comment by gregorydlogan** [comment]
I think so.  It's still a configuration error if all nodes can't talk to eachother, but not having the heartbeat enabled on anything other than admin(s) should solve effectively 99% of the problem.
