### ISSUE TITLE
Opencast 9 does not build with JDK 11

### ISSUE THREAD

**Issue by gregorydlogan** [opencast/opencast#1688]
**Describe the bug**
Attempting to build with JDK 11 and OC 9 (currently `develop`) yields NoClassDefFound exceptions during dublinecore unit tests.

**To Reproduce**
1. Build with JDK 11

```
# mvn -B -V -Dmaven.repo.local=/builder/m2 clean install
Apache Maven 3.6.3
Maven home: /usr/share/maven
Java version: 11.0.7, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.9.0-12-amd64", arch: "amd64", family: "unix"
[...]
[ERROR] Tests run: 15, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.158 s <<< FAILURE! - in org.opencastproject.metadata.dublincore.DublinCoreTest
[ERROR] testMediaPackageMetadataExtraction(org.opencastproject.metadata.dublincore.DublinCoreTest)  Time elapsed: 0.004 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.opencastproject.mediapackage.MediaPackageImpl
	at org.opencastproject.metadata.dublincore.DublinCoreTest.testMediaPackageMetadataExtraction(DublinCoreTest.java:430)
[INFO] Running org.opencastproject.metadata.dublincore.StaticMetadataServiceDublinCoreImplTest
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.006 s <<< FAILURE! - in org.opencastproject.metadata.dublincore.StaticMetadataServiceDublinCoreImplTest
[ERROR] testExtractMetadata(org.opencastproject.metadata.dublincore.StaticMetadataServiceDublinCoreImplTest)  Time elapsed: 0.003 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.opencastproject.mediapackage.MediaPackageImpl
	at org.opencastproject.metadata.dublincore.StaticMetadataServiceDublinCoreImplTest.newMediaPackage(StaticMetadataServiceDublinCoreImplTest.java:91)
	at org.opencastproject.metadata.dublincore.StaticMetadataServiceDublinCoreImplTest.testExtractMetadata(StaticMetadataServiceDublinCoreImplTest.java:48)
[ERROR] testDefectMetadata(org.opencastproject.metadata.dublincore.StaticMetadataServiceDublinCoreImplTest)  Time elapsed: 0.003 s  <<< ERROR!
java.lang.Exception: Unexpected exception, expected<java.lang.IllegalArgumentException> but was<java.lang.NoClassDefFoundError>
	at org.opencastproject.metadata.dublincore.StaticMetadataServiceDublinCoreImplTest.newMediaPackage(StaticMetadataServiceDublinCoreImplTest.java:91)
	at org.opencastproject.metadata.dublincore.StaticMetadataServiceDublinCoreImplTest.testDefectMetadata(StaticMetadataServiceDublinCoreImplTest.java:59)
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   DublinCoreTest.testMediaPackageMetadataExtraction:430 » NoClassDefFound Could ...
[ERROR]   DublinCoreXmlFormatTest.readFromNode:94 » ExceptionInInitializer
[ERROR]   StaticMetadataServiceDublinCoreImplTest.testDefectMetadata »  Unexpected excep...
[ERROR]   StaticMetadataServiceDublinCoreImplTest.testExtractMetadata:48->newMediaPackage:91 » NoClassDefFound
[INFO] 
[ERROR] Tests run: 42, Failures: 0, Errors: 4, Skipped: 0
```

**Comment by karendolan** [comment]
@gregorydlogan do I need to adjust the pom.xml to build in 11?  Currently, OC 9 pom.xml ```<jdk.version>1.8</jdk.version>```

**Comment by gregorydlogan** [comment]
@karendolan That, to be honest, might be part of what's causing this, but this happens with JDK11 building the codebase exactly as it currently is.
