### ISSUE TITLE
Build fails on ARM without Python 2.x

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast#1967]
There is no prebuilt node-sass binary for ARM and the latest version still references an older node-gyp version which expects Python 2 to be the default Python. The error is likely fixed in their current master branch.

<details>

```
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 1 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO] 
[INFO] -----------< org.opencastproject:opencast-admin-ui-frontend >-----------
[INFO] Building Opencast :: admin-ui-frontend 9-SNAPSHOT
[INFO] -------------------------------[ bundle ]-------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:3.0.0:clean (default-clean) @ opencast-admin-ui-frontend ---
[INFO] Deleting /home/lars/dev/opencast/modules/admin-ui-frontend/target
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-maven) @ opencast-admin-ui-frontend ---
[INFO] 
[INFO] --- buildnumber-maven-plugin:1.4:create (default) @ opencast-admin-ui-frontend ---
[INFO] ShortRevision tag detected. The value is '7'.
[INFO] Executing: /bin/sh -c cd '/home/lars/dev/opencast/modules/admin-ui-frontend' && 'git' 'rev-parse' '--verify' '--short=7' 'HEAD'
[INFO] Working directory: /home/lars/dev/opencast/modules/admin-ui-frontend
[INFO] Storing buildNumber: bbee052 at timestamp: 1602779951153
[INFO] Storing buildScmBranch: develop
[INFO] 
[INFO] --- maven-checkstyle-plugin:3.1.0:check (default) @ opencast-admin-ui-frontend ---
[INFO] Starting audit...
Audit done.
[INFO] 
[INFO] --- frontend-maven-plugin:1.7.6:install-node-and-npm (install node and npm) @ opencast-admin-ui-frontend ---
[INFO] Node v12.18.0 is already installed.
[INFO] NPM 6.14.4 is already installed.
[INFO] 
[INFO] --- frontend-maven-plugin:1.7.6:npm (npm ci) @ opencast-admin-ui-frontend ---
[INFO] Running 'npm ci' in /home/lars/dev/opencast/modules/admin-ui-frontend
[WARNING] npm WARN prepare removing existing node_modules/ before installation
[INFO] 
[INFO] > node-sass@4.14.1 install /home/lars/dev/opencast/modules/admin-ui-frontend/node_modules/node-sass
[INFO] > node scripts/install.js
[INFO] 
[INFO] Downloading binary from https://github.com/sass/node-sass/releases/download/v4.14.1/linux-arm64-72_binding.node
[ERROR] Cannot download "https://github.com/sass/node-sass/releases/download/v4.14.1/linux-arm64-72_binding.node": 
[ERROR] 
[ERROR] HTTP error 404 Not Found
[ERROR] 
[ERROR] Hint: If github.com is not accessible in your location
[ERROR]       try setting a proxy via HTTP_PROXY, e.g. 
[ERROR] 
[ERROR]       export HTTP_PROXY=http://example.com:1234
[ERROR] 
[ERROR] or configure npm proxy via
[INFO] 
[INFO] > node-sass@4.14.1 postinstall /home/lars/dev/opencast/modules/admin-ui-frontend/node_modules/node-sass
[INFO] > node scripts/build.js
[INFO] 
[ERROR] 
[ERROR]       npm config set proxy http://example.com:8080
[INFO] Building: /home/lars/dev/opencast/modules/admin-ui-frontend/node/node /home/lars/dev/opencast/modules/admin-ui-frontend/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
[ERROR] gyp info it worked if it ends with ok
[ERROR] gyp verb cli [
[ERROR] gyp verb cli   '/home/lars/dev/opencast/modules/admin-ui-frontend/node/node',
[ERROR] gyp verb cli   '/home/lars/dev/opencast/modules/admin-ui-frontend/node_modules/node-gyp/bin/node-gyp.js',
[ERROR] gyp verb cli   'rebuild',
[ERROR] gyp verb cli   '--verbose',
[ERROR] gyp verb cli   '--libsass_ext=',
[ERROR] gyp verb cli   '--libsass_cflags=',
[ERROR] gyp verb cli   '--libsass_ldflags=',
[ERROR] gyp verb cli   '--libsass_library='
[ERROR] gyp verb cli ]
[ERROR] gyp info using node-gyp@3.8.0
[ERROR] gyp info using node@12.18.0 | linux | arm64
[ERROR] gyp verb command rebuild []
[ERROR] gyp verb command clean []
[ERROR] gyp verb clean removing "build" directory
[ERROR] gyp verb command configure []
[ERROR] gyp verb check python checking for Python executable "python2" in the PATH
[ERROR] gyp verb `which` failed Error: not found: python2
[ERROR] gyp verb `which` failed     at getNotFoundError (/home/lars/dev/opencast/modules/admin-ui-frontend/node_modules/which/which.js:13:12)
[ERROR] gyp verb `which` failed     at F (/home/lars/dev/opencast/modules/admin-ui-frontend/node_modules/which/which.js:68:19)
[ERROR] gyp verb `which` failed     at E (/home/lars/dev/opencast/modules/admin-ui-frontend/node_modules/which/which.js:80:29)
[ERROR] gyp verb `which` failed     at /home/lars/dev/opencast/modules/admin-ui-frontend/node_modules/which/which.js:89:16
[ERROR] gyp verb `which` failed     at /home/lars/dev/opencast/modules/admin-ui-frontend/node_modules/isexe/index.js:42:5
[ERROR] gyp verb `which` failed     at /home/lars/dev/opencast/modules/admin-ui-frontend/node_modules/isexe/mode.js:8:5
[ERROR] gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:167:21)
[ERROR] gyp verb `which` failed  python2 Error: not found: python2
[ERROR] gyp verb `which` failed     at getNotFoundError (/home/lars/dev/opencast/modules/admin-ui-frontend/node_modules/which/which.js:13:12)
[ERROR] gyp verb `which` failed     at F (/home/lars/dev/opencast/modules/admin-ui-frontend/node_modules/which/which.js:68:19)
[ERROR] gyp verb `which` failed     at E (/home/lars/dev/opencast/modules/admin-ui-frontend/node_modules/which/which.js:80:29)
[ERROR] gyp verb `which` failed     at /home/lars/dev/opencast/modules/admin-ui-frontend/node_modules/which/which.js:89:16
[ERROR] gyp verb `which` failed     at /home/lars/dev/opencast/modules/admin-ui-frontend/node_modules/isexe/index.js:42:5
[ERROR] gyp verb `which` failed     at /home/lars/dev/opencast/modules/admin-ui-frontend/node_modules/isexe/mode.js:8:5
[ERROR] gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:167:21) {
[ERROR] gyp verb `which` failed   code: 'ENOENT'
[ERROR] gyp verb `which` failed }
[ERROR] gyp verb check python checking for Python executable "python" in the PATH
[ERROR] gyp verb `which` succeeded python /bin/python
[ERROR] gyp ERR! configure error 
[ERROR] gyp ERR! stack Error: Command failed: /bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
[ERROR] gyp ERR! stack   File "<string>", line 1
[ERROR] gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
[ERROR] gyp ERR! stack                       ^
[ERROR] gyp ERR! stack SyntaxError: invalid syntax
[ERROR] gyp ERR! stack 
[ERROR] gyp ERR! stack     at ChildProcess.exithandler (child_process.js:303:12)
[ERROR] gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
[ERROR] gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
[ERROR] gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
[ERROR] gyp ERR! System Linux 5.7.19-1-MANJARO-ARM
[ERROR] gyp ERR! command "/home/lars/dev/opencast/modules/admin-ui-frontend/node/node" "/home/lars/dev/opencast/modules/admin-ui-frontend/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
[ERROR] gyp ERR! cwd /home/lars/dev/opencast/modules/admin-ui-frontend/node_modules/node-sass
[ERROR] gyp ERR! node -v v12.18.0
[ERROR] gyp ERR! node-gyp -v v3.8.0
[ERROR] gyp ERR! not ok 
[ERROR] Build failed with error code: 1
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! errno 1
[ERROR] npm ERR! node-sass@4.14.1 postinstall: `node scripts/build.js`
[ERROR] npm ERR! Exit status 1
[ERROR] npm ERR! 
[ERROR] npm ERR! Failed at the node-sass@4.14.1 postinstall script.
[ERROR] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[ERROR] 
[ERROR] npm ERR! A complete log of this run can be found in:
[ERROR] npm ERR!     /home/lars/.npm/_logs/2020-10-15T16_39_58_359Z-debug.log
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:21 min
[INFO] Finished at: 2020-10-15T18:39:58+02:00
[INFO] ------------------------------------------------------------------------
[WARNING] The requested profile "dev" could not be activated because it does not exist.
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.7.6:npm (npm ci) on project opencast-admin-ui-frontend: Failed to run task: 'npm ci' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```
</details>

**Comment by mliradelc** [comment]
Besides the question itself, that is important for the future of the project (Looking forward how is ARM taking over x86)

Can you say that is a bug when the architecture is not supported by the project :thinking: ? 

For me is more a feature request: "Support Opencast in ARM architecture"

**Comment by lkiesow** [comment]
> Can you say that is a bug when the architecture is not supported by the project thinking ?

Were do we say that we don't support ARM?

**Comment by gregorydlogan** [comment]
I've been wondering how long until someone comes along and asks for this, especially with the AWS instances being so cheap.  In theory, Opencast should run anywhere where you can get Java to run.  Workers might require other things (ffmpeg), but lots of those things are likely portable to ARM as well.  Or POWER, or...

I don't see any issue with supporting other hardware, especially easily obtainable hardware (rasp pi 3+ is armv8, which is the same as Graviton).  We should at least be compile and (mostly) startable on ARM, with the caveat that Real Support(tm) isn't going to show up until an adopter for it shows up.

**Comment by karendolan** [comment]
I'm going to use this ticket for a pull to migrate admiin-ui-front end's node-sass to sass project as recommended on the node-sass project site.
ref: https://www.npmjs.com/package/node-sass
ref: https://sass-lang.com/blog/libsass-is-deprecated

The motivation is that our site is having problems with node-sass complaining about the global bindings when running local development, and sass (Dart sass) doesn't have that issue.

**Comment by karendolan** [comment]
@lkiesow can you verify that the patch works to build on ARM?

**Comment by lkiesow** [comment]
Just tested without the patch, and even that seems to work by now with the current state of `develop`:

```
[INFO] Assemblies // Distribution Develop ................. SUCCESS [03:12 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  36:40 min
[INFO] Finished at: 2022-03-11T16:41:32+01:00
[INFO] ------------------------------------------------------------------------
[lars@pine]~/dev/opencast/opencast% python2                                                                                                                               (git)-[develop] [0]
zsh: command not found: python2
[lars@pine]~/dev/opencast/opencast% 
```

But will test the patch anyway in a moment. We should still upgrade after all.
