### ISSUE TITLE
CaptureAgentsEndpointTest requires unused network port

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast#2098]
Running the admin interface tests failed with:

```
[INFO] Running org.opencastproject.adminui.endpoint.CaptureAgentsEndpointTest
Error:  Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.167 s <<< FAILURE! - in org.opencastproject.adminui.endpoint.CaptureAgentsEndpointTest
Error:  org.opencastproject.adminui.endpoint.CaptureAgentsEndpointTest  Time elapsed: 0.167 s  <<< ERROR!
java.io.IOException: Failed to bind to 0.0.0.0/0.0.0.0:8084
	at org.opencastproject.adminui.endpoint.CaptureAgentsEndpointTest.oneTimeSetUp(CaptureAgentsEndpointTest.java:193)
Caused by: java.net.BindException: Address already in use
	at org.opencastproject.adminui.endpoint.CaptureAgentsEndpointTest.oneTimeSetUp(CaptureAgentsEndpointTest.java:193)
```

…which is most likely a concurrency problem.
I any case, the tests shouldn't hard-code a single port but at least try a range of ports if one is already in use.

**Comment by gregorydlogan** [comment]
Looking at this test, it's already trying [100 (hopefully) different ports](https://github.com/opencast/opencast/blob/develop/modules/rest-test-environment/src/main/java/org/opencastproject/test/rest/RestServiceTestEnv.java#L118) as part of the test setup.  Is this repeatable?

**Comment by lkiesow** [comment]
I think what could be the problem is that multiple tests decide on the same port which then causes the error. That said, chances are still pretty slim that this happens often. I guess we can close this for now. We can always re-open this if the problem starts popping up on a regular basis.

**Comment by lkiesow** [comment]
It seems like something doesn't seem to work like it should. I've seen at least two more exceptions like this:

```
Error:  Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.141 s <<< FAILURE! - in org.opencastproject.adminui.endpoint.CaptureAgentsEndpointTest
Error:  org.opencastproject.adminui.endpoint.CaptureAgentsEndpointTest  Time elapsed: 0.14 s  <<< ERROR!
java.io.IOException: Failed to bind to 0.0.0.0/0.0.0.0:8084
	at org.opencastproject.adminui.endpoint.CaptureAgentsEndpointTest.oneTimeSetUp(CaptureAgentsEndpointTest.java:193)
Caused by: java.net.BindException: Address already in use
	at org.opencastproject.adminui.endpoint.CaptureAgentsEndpointTest.oneTimeSetUp(CaptureAgentsEndpointTest.java:193)
```

Every time it seems like the test is trying to use port 8084. That's less random than expected…

**Comment by lkiesow** [comment]
The test still seems to be problematic. I have seen this fail a few times on CI and just had this fail on my dev machine as well. Maybe, multiple tests try opening the same random port. We need to investigate a bit more…

```
[INFO] Running org.opencastproject.adminui.endpoint.JobEndpointTest                                                                                                                                                                           
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.048 s <<< FAILURE! - in org.opencastproject.adminui.endpoint.JobEndpointTest                                                                                        
[ERROR] org.opencastproject.adminui.endpoint.JobEndpointTest  Time elapsed: 0.048 s  <<< ERROR!                                                                                                                                               
java.io.IOException: Failed to bind to 0.0.0.0/0.0.0.0:50634                                                                                                                                                                                  
        at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:346)                                                                                                                                               
        at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:307)                                                                                                                                                            
        at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)                                                                                                                                        
        at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:231)                                                                                                                                                         
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)                                                                                                                                                
        at org.eclipse.jetty.server.Server.doStart(Server.java:385)                                                                                                                                                                           
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)                                                                                                                                                
        at org.opencastproject.test.rest.RestServiceTestEnv.setUpServer(RestServiceTestEnv.java:163)                                                                                                                                          
        at org.opencastproject.adminui.endpoint.JobEndpointTest.oneTimeSetUp(JobEndpointTest.java:216)                                                                                                                                        
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                                                                                                                                                     
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)                                                                                                                                   
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: java.net.BindException: Address already in use
        at java.base/sun.nio.ch.Net.bind0(Native Method)
        at java.base/sun.nio.ch.Net.bind(Net.java:455)
        at java.base/sun.nio.ch.Net.bind(Net.java:447)
        at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:227)
        at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:80)
        at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:342)
        ... 28 more


…

[INFO]                                                                                                                                                                                                                                        
[INFO] Results:                                                                                                                                                                                                                               
[INFO]                                                                                                                                                                                                                                        
[ERROR] Errors:                                                                                                                                                                                                                               
[ERROR]   JobEndpointTest.oneTimeSetUp:216 » IO Failed to bind to 0.0.0.0/0.0.0.0:50634                                                                                                                                                       
[INFO]                                                                                                                                                                                                                                        
[ERROR] Tests run: 127, Failures: 0, Errors: 1, Skipped: 0
```

**Comment by lkiesow** [comment]
I have absolutely no idea why this breaks but you can more or less reliably reproduce the error by running:

```
cd modules/admin-ui
while mvn clean install -Pdev -DtrimStackTrace=false ; do echo "\n\n\n\n\n\n\n"; done
```

And giving in 10-20 min

**Comment by gregorydlogan** [comment]
We should just use port 4. Chosen by fair dice roll, guaranteed to be random!

In all seriousness, this sounds like something isn't getting cleaned up properly and there are zombies holding open ports.
