### ISSUE TITLE
Auto-creation of table oc_incident_text fails on utf8mb4 database

### ISSUE THREAD

**Issue by kbudwi** [opencast/opencast#2294]
Error message on missing table appears repeatedly  in opencast.log
Admin-UI not working properly
 - Table "events" loads endlessly
 - metadata forms missing when uploading media

**To Reproduce**
* install Opencast 9.1
* Start with a blank database by following instructions at <https://docs.opencast.org/r/9.x/admin/#configuration/database/>
* Start opencast service
* monitor opencast.log

**Environment Information**
 - OS: ubuntu  Ubuntu 18.04.5 LTS, openjdk 11.0.9.1, MariaDB-Server 10.1.47-0ubuntu0.18
 - Opencast-9-allinone               9.1-2

** Error message**

```
2021-02-04T15:44:17,426 | INFO  | (OsgiIncidentService:117) - Activating persistence manager for job incidents
2021-02-04T15:44:17,605 | ERROR | (R6LogServiceLogger:50) - bundle opencast-serviceregistry:9.1.0 (163)[org.opencastproject.serviceregistry.impl.OsgiIncidentService(251)] : The activate method has thrown an exception
org.eclipse.persistence.exceptions.DatabaseException:
Internal Exception: java.sql.SQLSyntaxErrorException: (conn=32) Table 'opencast.oc_incident_text' doesn't exist
Error Code: 1146
Call: SELECT id, text FROM oc_incident_text WHERE (id = ?)
        bind => [1 parameter bound]
Query: ReadObjectQuery(name="readIncidentTextDto" referenceClass=IncidentTextDto sql="SELECT id, text FROM oc_incident_text WHERE (id = ?)")
        at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:342) ~[?:?]
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:691) ~[?:?]
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeCall(DatabaseAccessor.java:567) ~[?:?]
        at org.eclipse.persistence.internal.sessions.AbstractSession.basicExecuteCall(AbstractSession.java:2099) ~[?:?]
        at org.eclipse.persistence.sessions.server.ServerSession.executeCall(ServerSession.java:603) ~[?:?]
        at org.eclipse.persistence.sessions.server.ClientSession.executeCall(ClientSession.java:265) ~[?:?]
        at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:277) ~[?:?]
        at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:263) ~[?:?]
        at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.selectOneRow(DatasourceCallQueryMechanism.java:766) ~[?:?]
        at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.selectOneRowFromTable(ExpressionQueryMechanism.java:2822) ~[?:?]
        at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.selectOneRow(ExpressionQueryMechanism.java:2775) ~[?:?]
        at org.eclipse.persistence.queries.ReadObjectQuery.executeObjectLevelReadQuery(ReadObjectQuery.java:561) ~[?:?]
        at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeDatabaseQuery(ObjectLevelReadQuery.java:1232) ~[?:?]
        at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:911) ~[?:?]
        at org.eclipse.persistence.queries.ObjectLevelReadQuery.execute(ObjectLevelReadQuery.java:1191) ~[?:?]
        at org.eclipse.persistence.queries.ReadObjectQuery.execute(ReadObjectQuery.java:447) ~[?:?]
        at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeInUnitOfWork(ObjectLevelReadQuery.java:1279) ~[?:?]
        at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:2983) ~[?:?]
        at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1898) ~[?:?]
        at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1880) ~[?:?]
        at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1830) ~[?:?]
        at org.eclipse.persistence.internal.jpa.EntityManagerImpl.executeQuery(EntityManagerImpl.java:1012) ~[?:?]
        at org.eclipse.persistence.internal.jpa.EntityManagerImpl.findInternal(EntityManagerImpl.java:954) ~[?:?]
        at org.eclipse.persistence.internal.jpa.EntityManagerImpl.find(EntityManagerImpl.java:830) ~[?:?]
        at org.eclipse.persistence.internal.jpa.EntityManagerImpl.find(EntityManagerImpl.java:696) ~[?:?]
        at org.opencastproject.util.persistence.Queries.persistOrUpdate(Queries.java:72) ~[?:?]
        at org.opencastproject.util.persistence.Queries$3.apply(Queries.java:85) ~[?:?]
        at org.opencastproject.util.persistence.Queries$3.apply(Queries.java:83) ~[?:?]
        at org.opencastproject.util.persistence.PersistenceEnvs$2.tx(PersistenceEnvs.java:70) ~[?:?]
        at org.opencastproject.util.persistence.PersistenceEnvs$3.tx(PersistenceEnvs.java:94) ~[?:?]
        at org.opencastproject.serviceregistry.impl.OsgiIncidentService.storeIncidentTexts(OsgiIncidentService.java:178) ~[?:?]
        at org.opencastproject.serviceregistry.impl.OsgiIncidentService.activate(OsgiIncidentService.java:122) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.apache.felix.scr.impl.inject.methods.BaseMethod.invokeMethod(BaseMethod.java:242) ~[!/:?]
        at org.apache.felix.scr.impl.inject.methods.BaseMethod.access$500(BaseMethod.java:41) ~[!/:?]
        at org.apache.felix.scr.impl.inject.methods.BaseMethod$Resolved.invoke(BaseMethod.java:678) ~[!/:?]
        at org.apache.felix.scr.impl.inject.methods.BaseMethod.invoke(BaseMethod.java:524) [!/:?]
        at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:318) [!/:?]
        at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:308) [!/:?]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.createImplementationObject(SingleComponentManager.java:342) [!/:?]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.createComponent(SingleComponentManager.java:115) [!/:?]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:984) [!/:?]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:957) [!/:?]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:902) [!/:?]
        at org.apache.felix.framework.ServiceRegistrationImpl.getFactoryUnchecked(ServiceRegistrationImpl.java:347) [org.apache.felix.framework-5.6.12.jar:?]


Exectuting CREATE TABLE stratement manually causes database error

MariaDB [(none)]> use utf8mb4_db;
Database changed
MariaDB [utf8mb4_db]> CREATE TABLE oc_incident_text (id VARCHAR(255) NOT NULL, text VARCHAR(2038) NOT NULL, PRIMARY KEY (id));
ERROR 1071 (42000): Specified key was too long; max key length is 767 bytes
```

see #2282

**Comment by lkiesow** [comment]
Same comment as before, this is mostly MariaDB configuration and the official configuration of current MariaDB (see Docker container) should already work. For a configuration example, see:
https://dba.stackexchange.com/a/231234

I've created  #2295 to reduce the ID size which should still suffice, but you might want to increase that anyway.
Still, if you could check if the patch fixes the problem for you, that would be great.

**Comment by kbudwi** [comment]
Manual execution of the modified statement works without problems 

```
MariaDB [(none)]> use utf8mb4_db;
Database changed
MariaDB [utf8mb4_db]> CREATE TABLE oc_incident_text (id VARCHAR(128) NOT NULL, text VARCHAR(2038) NOT NULL, PRIMARY KEY (id));
Query OK, 0 rows affected (0.06 sec)
```

With the table manually created on the on the opencast database instance, malfunctions of the Admin-UI are gone.

**Comment by lkiesow** [comment]
Thanks for testing.

**Comment by kbudwi** [comment]
Addendum: The root cause of the database errors observed on ubuntu 18.04 LTS
while switching to the utf8mb4 character set is MariaDB version 10.1 provided in
this distribution. Here, the default InnoDB file format is Antelope and default
row format COMPACT, which only supports VARCHAR key fields up to 191 characters
(767/4=191,75) [1]. Creation of new tables with columns > 191 characters is therefore not possible.

Unfortunately, updating older opencast databases created with character set utf8 and collation
utf8_general_ci (Opencast 7.X and earlier) to the current settings (utf8mb4/utf8mb4_unicode_ci) with
the method suggested in [2] also fails, even with the shortened primary keys, as not only those keys cause problems but also some foreign keys.

IMHO it is not possible to run the opencast database with the current
settings on ubuntu 18.04 without reconfiguration of the database server to use
the newer Barracuda file format (with row format DYNAMIC) as default.

This is done by adding the lines

innodb_file_format = Barracuda
innodb_file_per_table = on
innodb_default_row_format = dynamic
innodb_large_prefix = 1
innodb_file_format_max = Barracuda

to /etc/mysql/mariadb.conf.d/50-server.cnf and restarting MariaDB

Ubuntu 20.04 LTS provides MariaDB 10.3 where Barracuda is the default. Unless there are compatibility issues with server version 10.3 vs. client version 10.1 running this distribution as the database server could be an alternative workaroud.

[1] https://mariadb.com/kb/en/innodb-file-format/
[2] https://dba.stackexchange.com/questions/8239/how-to-easily-convert-utf8-tables-to-utf8mb4-in-mysql-5-5/104866#104866
