### ISSUE TITLE
Cannot update org.apache.karaf.shell.cfg

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast#2359]
The following error appears on RPM based Opencast installations on startup:

```
2021-02-24T15:35:01,993 | WARN  | (FeatureConfigInstaller:134) - Can't update cfg file
java.io.FileNotFoundException: /etc/opencast/org.apache.karaf.shell.cfg (Keine Berechtigung)
        at java.io.FileOutputStream.open0(Native Method) ~[?:1.8.0_275]
        at java.io.FileOutputStream.open(FileOutputStream.java:270) ~[?:1.8.0_275]
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213) ~[?:1.8.0_275]
        at java.io.FileOutputStream.<init>(FileOutputStream.java:162) ~[?:1.8.0_275]
        at org.apache.felix.utils.properties.Properties.save(Properties.java:153) ~[org.apache.karaf.main-4.2.9.jar:4.2.9]
        at org.apache.felix.utils.properties.TypedProperties.save(TypedProperties.java:106) ~[org.apache.karaf.main-4.2.9.jar:4.2.9]
        at org.apache.karaf.features.internal.service.FeatureConfigInstaller.updateStorage(FeatureConfigInstaller.java:297) ~[?:?]
        at org.apache.karaf.features.internal.service.FeatureConfigInstaller.installFeatureConfigs(FeatureConfigInstaller.java:132) ~[?:?]
        at org.apache.karaf.features.internal.service.BundleInstallSupportImpl.installConfigs(BundleInstallSupportImpl.java:301) ~[?:?]
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.installConfigs(FeaturesServiceImpl.java:1178) ~[?:?]
        at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:955) ~[?:?]
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1062) ~[?:?]
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:998) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_275]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_275]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_275]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]

```

- Appears with 9.x packages
- It's actually harmless just doesn't look very nice

**Comment by lkiesow** [comment]
Fixed in 9.3 RPMs
