### ISSUE TITLE
Several Opencast 10 Distributions Broken

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast#2410]
Opencast fails with an OSGi wiring error when trying to start a worker distribution. My best guess is the restructured index rebuild service since that one is part of the resolution path that causes the error.

```
start-opencast: JAVA_HOME not set; results may vary
org.apache.felix.resolver.reason.ReasonException: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=opencast-worker; type=karaf.feature; version="[10.0.0.SNAPSHOT,10.0.0.SNAPSHOT]"; filter:="(&(osgi.identity=opencast-worker)(type=karaf.feature)(version>=10.0.0.SNAPSHOT)(version<=10.0.0.SNAPSHOT))" [caused by: Unable to resolve opencast-worker/10.0.0.SNAPSHOT: missing requirement [opencast-worker/10.0.0.SNAPSHOT] osgi.identity; osgi.identity=opencast-series-service-remote; type=osgi.bundle; version="[10.0.0.SNAPSHOT,10.0.0.SNAPSHOT]"; resolution:=mandatory [caused by: Unable to resolve opencast-series-service-remote/10.0.0.SNAPSHOT: missing requirement [opencast-series-service-remote/10.0.0.SNAPSHOT] osgi.service; filter:="(objectClass=org.opencastproject.serviceregistry.api.ServiceRegistry)"; effective:=active [caused by: Unable to resolve opencast-serviceregistry/10.0.0.SNAPSHOT: missing requirement [opencast-serviceregistry/10.0.0.SNAPSHOT] osgi.service; filter:="(objectClass=org.opencastproject.security.api.UserDirectoryService)"; effective:=active [caused by: Unable to resolve opencast-userdirectory/10.0.0.SNAPSHOT: missing requirement [opencast-userdirectory/10.0.0.SNAPSHOT] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.opencastproject.index.rebuild)(version>=10.0.0)(!(version>=11.0.0)))"]]]]
        at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1343)
        at org.apache.felix.resolver.ResolverImpl.doResolve(ResolverImpl.java:392)
        at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:378)
        at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:332)
        at org.apache.karaf.features.internal.region.SubsystemResolver.resolve(SubsystemResolver.java:257)
        at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:393)
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1062)
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:998)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve opencast-worker/10.0.0.SNAPSHOT: missing requirement [opencast-worker/10.0.0.SNAPSHOT] osgi.identity; osgi.identity=opencast-series-service-remote; type=osgi.bundle; version="[10.0.0.SNAPSHOT,10.0.0.SNAPSHOT]"; resolution:=mandatory [caused by: Unable to resolve opencast-series-service-remote/10.0.0.SNAPSHOT: missing requirement [opencast-series-service-remote/10.0.0.SNAPSHOT] osgi.service; filter:="(objectClass=org.opencastproject.serviceregistry.api.ServiceRegistry)"; effective:=active [caused by: Unable to resolve opencast-serviceregistry/10.0.0.SNAPSHOT: missing requirement [opencast-serviceregistry/10.0.0.SNAPSHOT] osgi.service; filter:="(objectClass=org.opencastproject.security.api.UserDirectoryService)"; effective:=active [caused by: Unable to resolve opencast-userdirectory/10.0.0.SNAPSHOT: missing requirement [opencast-userdirectory/10.0.0.SNAPSHOT] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.opencastproject.index.rebuild)(version>=10.0.0)(!(version>=11.0.0)))"]]]
        at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1343)
        ... 12 more
Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve opencast-series-service-remote/10.0.0.SNAPSHOT: missing requirement [opencast-series-service-remote/10.0.0.SNAPSHOT] osgi.service; filter:="(objectClass=org.opencastproject.serviceregistry.api.ServiceRegistry)"; effective:=active [caused by: Unable to resolve opencast-serviceregistry/10.0.0.SNAPSHOT: missing requirement [opencast-serviceregistry/10.0.0.SNAPSHOT] osgi.service; filter:="(objectClass=org.opencastproject.security.api.UserDirectoryService)"; effective:=active [caused by: Unable to resolve opencast-userdirectory/10.0.0.SNAPSHOT: missing requirement [opencast-userdirectory/10.0.0.SNAPSHOT] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.opencastproject.index.rebuild)(version>=10.0.0)(!(version>=11.0.0)))"]]
        at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1343)
        ... 13 more
Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve opencast-serviceregistry/10.0.0.SNAPSHOT: missing requirement [opencast-serviceregistry/10.0.0.SNAPSHOT] osgi.service; filter:="(objectClass=org.opencastproject.security.api.UserDirectoryService)"; effective:=active [caused by: Unable to resolve opencast-userdirectory/10.0.0.SNAPSHOT: missing requirement [opencast-userdirectory/10.0.0.SNAPSHOT] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.opencastproject.index.rebuild)(version>=10.0.0)(!(version>=11.0.0)))"]
        at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1343)
        ... 14 more
Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve opencast-userdirectory/10.0.0.SNAPSHOT: missing requirement [opencast-userdirectory/10.0.0.SNAPSHOT] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.opencastproject.index.rebuild)(version>=10.0.0)(!(version>=11.0.0)))"
        at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1343)
        ... 15 more
```

Distributions that seems to be broken:

- Worker
- Presentation
- Ingest

Most likely cause:
> Unable to resolve opencast-userdirectory/10.0.0.SNAPSHOT: missing requirement […] org.o
pencastproject.index.rebuild […]

**Comment by KatrinIhler** [comment]
I'm gonna look into this. I already have an idea...
