### ISSUE TITLE
Cover-image operation cannot handle multi-byte Unicdoe characters

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast#2499]
If the event title contains multi-byte Unicode characters, the operation `cover-image` claims to finish successfully but will result in a black image and the following (not properly logged) message:

```
2021-04-16 00:25:27,600 | INFO  | (CoverImageWorkflowOperationHandlerBase:105) - Cover Image Workflow started for media package 'e8bfe29b-bce3-442d-8917-7c02b8c05cbe'                                                                        
About to transcoder source of type: org.apache.batik.apps.rasterizer.SVGConverterFileSource                                                                                                                                                   
org.apache.batik.transcoder.TranscoderException: null                                                                                                                                                                                         
Enclosed Exception:
Character reference "&#55357" is an invalid XML character.
        at org.apache.batik.transcoder.XMLAbstractTranscoder.transcode(XMLAbstractTranscoder.java:136)
        at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(SVGAbstractTranscoder.java:156)
        at org.apache.batik.apps.rasterizer.SVGConverter.transcode(SVGConverter.java:1001)
        at org.apache.batik.apps.rasterizer.SVGConverter.execute(SVGConverter.java:717)
        at org.opencastproject.coverimage.impl.AbstractCoverImageService.rasterizeSvg(AbstractCoverImageService.java:283)
        at org.opencastproject.coverimage.impl.AbstractCoverImageService.generateCoverImageInternal(AbstractCoverImageService.java:176)
        at org.opencastproject.coverimage.impl.AbstractCoverImageService.process(AbstractCoverImageService.java:128)
        at org.opencastproject.job.api.AbstractJobProducer$JobRunner.call(AbstractJobProducer.java:313)
        at org.opencastproject.job.api.AbstractJobProducer$JobRunner.call(AbstractJobProducer.java:272)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
2021-04-16 00:25:37,631 | INFO  | (CoverImageWorkflowOperationHandlerBase:193) - Cover Image Workflow finished successfully for media package 'e8bfe29b-bce3-442d-8917-7c02b8c05cbe' within 17ms
```

Should happen with all Opencast 8 and Opencast 9 versions.

**Comment by lkiesow** [comment]
Fixed by #3188
