### ISSUE TITLE
LDAP: UsernameNotFoundException when search filter does applay

### ISSUE THREAD

**Issue by Arnei** [opencast/opencast#2528]
**Describe the bug**
When using LDAP in Opencast 8.10 with the a searchfilter, a `UsernameNotFoundException` is thrown in case the user does exist in the system, but does not match the search filter.

For example, if I have a user of the form
```
# jmacy, example.com
dn: uid=jmacy,dc=example,dc=com
memberOf: cn=not-opencast
```
and my search filter is
`org.opencastproject.userdirectory.ldap.searchfilter=(&(uid={0})(memberOf= cn=opencast))`
, the UsernameNotFoundException will be thrown.

<details>
  <summary>Log output</summary> 
2021-04-19T15:14:29,317 | WARN  | (HttpChannel:585) - /admin-ng/j_spring_security_check
 org.springframework.security.core.userdetails.UsernameNotFoundException: cb441030
        at org.opencastproject.userdirectory.UserAndRoleDirectoryServiceImpl.loadUserByUsername(UserAndRoleDirectoryServiceImpl.java:360) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor65.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:319) ~[?:?]
        at org.springframework.osgi.service.importer.support.internal.aop.ServiceInvoker.doInvoke(ServiceInvoker.java:58) ~[?:?]
        at org.springframework.osgi.service.importer.support.internal.aop.ServiceInvoker.invoke(ServiceInvoker.java:62) ~[?:?]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[?:?]
        at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:131) ~[?:?]
        at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:119) ~[?:?]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[?:?]
        at org.springframework.osgi.service.util.internal.aop.ServiceTCCLInterceptor.invokeUnprivileged(ServiceTCCLInterceptor.java:56) ~[?:?]
        at org.springframework.osgi.service.util.internal.aop.ServiceTCCLInterceptor.invoke(ServiceTCCLInterceptor.java:39) ~[?:?]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[?:?]
        at org.springframework.osgi.service.importer.support.LocalBundleContextAdvice.invoke(LocalBundleContextAdvice.java:59) ~[?:?]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[?:?]
        at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:131) ~[?:?]
        at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:119) ~[?:?]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[?:?]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202) ~[?:?]
        at com.sun.proxy.$Proxy137.loadUserByUsername(Unknown Source) ~[?:?]
[...]
</details>

**To Reproduce**
1. Configure your Opencast to use LDAP
2. Have a searchfilter that will exclude part of your LDAP users (and maybe some extra roles)
3. Try to log into the Opencast Admin UI with a user that does not match searchfilter

**Environment Information**
 - OS: CentOS 7
 - Opencast version: 8.10

**Comment by Arnei** [comment]
This issue seems to be local to a single opencast installation, I could not replicate the error on other installations. Therefore I'm closing this for now.
