### ISSUE TITLE
Comparison method violates its general contract

### ISSUE THREAD

**Issue by poffensand** [opencast/opencast#2745]
**Describe the bug**
Opencast workflows sometimes fail with the error message `java.lang.IllegalArgumentException: Comparison method violates its general contract`. As requested on Mailinglist, issue is filed here (https://groups.google.com/a/opencast.org/g/users/c/Xa8ax6sCpoU)

Sample Error Message:
```
org.opencastproject.workflow.api.WorkflowOperationException: 
java.lang.IllegalArgumentException: Comparison method violates its general 
contract!
 at org.opencastproject.workflow.impl.WorkflowOperationWorker.start(WorkflowOperationWorker.java:206) 
 at org.opencastproject.workflow.impl.WorkflowOperationWorker.execute(WorkflowOperationWorker.java:116) 
 at org.opencastproject.workflow.impl.WorkflowServiceImpl.runWorkflowOperation(WorkflowServiceImpl.java:801) 
 at org.opencastproject.workflow.impl.WorkflowServiceImpl.process(WorkflowServiceImpl.java:1833) 
 at org.opencastproject.workflow.impl.WorkflowServiceImpl$JobRunner.call(WorkflowServiceImpl.java:2283) 
 at org.opencastproject.workflow.impl.WorkflowServiceImpl$JobRunner.call(WorkflowServiceImpl.java:2249) 
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 
 at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Comparison method violates its general contract!
 at java.util.TimSort.mergeLo(TimSort.java:777)
 at java.util.TimSort.mergeAt(TimSort.java:514)
 at java.util.TimSort.mergeForceCollapse(TimSort.java:457)
 at java.util.TimSort.sort(TimSort.java:254)
 at java.util.Arrays.sort(Arrays.java:1512)
 at java.util.ArrayList.sort(ArrayList.java:1464)
 at java.util.Collections.sort(Collections.java:177)
 at org.opencastproject.serviceregistry.impl.ServiceRegistryJpaImpl.getServiceRegistrationsByLoad(ServiceRegistryJpaImpl.java:2805) 
 at org.opencastproject.serviceregistry.impl.ServiceRegistryJpaImpl.getServiceRegistrationsByLoad(ServiceRegistryJpaImpl.java:2198) 
 at org.opencastproject.serviceregistry.api.RemoteBase.getResponse(RemoteBase.java:176) 
 at org.opencastproject.serviceregistry.api.RemoteBase.getResponse(RemoteBase.java:145) 
 at org.opencastproject.ingestdownloadservice.remote.IngestDownloadServiceRemoteImpl.ingestDownload(IngestDownloadServiceRemoteImpl.java:92) 
 at org.opencastproject.workflow.handler.ingest.IngestDownloadWorkflowOperationHandler.start(IngestDownloadWorkflowOperationHandler.java:86) 
 at org.opencastproject.workflow.impl.WorkflowOperationWorker.start(WorkflowOperationWorker.java:193) 
 ... 9 more
```

**To Reproduce**
1. Start workflows on a bunch of different videos 
2. Get "lucky" and get the error in one of the workflows
3. See error

**Environment Information**
 - OS: CentOS 7
 - Java openjdk 1.8.0_292
 - Opencast version 9.5

**Comment by gregorydlogan** [comment]
So the gist of what's happening here is that we first compare the load factors of all nodes (jobLoad/maxLoad) and if the nodes are within 0.01 of each other then we tiebreak with the nodes max load. This sounds fine, but means that depending on input order of the nodes we'll get different results, violating the contract for `compare`.

The solution is to do this in two passes rather than one: first sort by load factors, then walk the results and for resort anything that's within 0.01 of each other.

**Comment by gregorydlogan** [comment]
@poffensand can we know more about your cluster? How many nodes, how many cores per node, any custom workflows, and how many workflows do you see a day on average?

I would have expected this to show up when I first added this logic, the fact that it hasn't shown up until now makes me think you've got something different going on in your cluster that's triggering it.

To be clear, this is still a bug and I'll get it fixed, but I would have expected this to show up in one of the bigger adopters first.

**Comment by poffensand** [comment]
Currently, we have 1 admin node (36 cores), 1 present node (12 cores), 10 worker nodes with 12 cores, 6 worker nodes with 40 cores, 14 worker nodes with 24 cores and 5 workers with 32 cores (so 35 worker nodes). 
We are using a custom workflow, which is a copy of schedule-and-upload, though it only differs in skipping to concatenate intro/outro, even if the series has a theme with those attached. 
We did have about 1200 Events per day added, increased to about 5000 Events per day, with one workflow per event and about 400 workflow instances running in parallel. 
This whole setup and processing was due to a needed migration from one opencast-instance to another, as mentioned in my latest post on the mailinglist.
