### ISSUE TITLE
Upgrade Opencast from 8.x to 10.1 - Missing table "oc_adopter_registration" error

### ISSUE THREAD

**Issue by slaudel** [opencast/opencast#2896]
After upgrade of an opencast test system from version **8.x** to **10.1** I'm seeing an error message thrown in the opencast log.
It seems related to #2282, where this error message appeared too.

What I did:
- Old 8.x installation was running on CentOS 7
- Reformatted disk and installed AlmaLinux 8.4
- installed all necessary tools and Opencast 10.1
- applied configuration from old installation (via ansible) and matched it to new 10.1 version
- The DB upgrade script "8_to_9" was run but there is no "9_to_10" script.
- started Opencast  

Maybe I missed some upgrade step? Otherwise, does the creation of this seemingly new table have to be included in an upgrade script? I'm wondering nobody else (except #2282) did stumble upon this?

Environment:
- AlmaLinux 8.4
- Java 11
- MariaDB 10.3
- Opencast 10.1 from RPM

Following the details/stacktrace of the error:

```
2021-08-03T11:58:13,109 | ERROR | (ScheduledDataCollector:145) - Couldn't retrieve adopter form data.
org.opencastproject.adopter.registration.FormRepositoryException: javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.7.v20200504-69f2c2b80d): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLSyntaxErrorException: (conn=262631) Table 'opencast7testdb.oc_adopter_registration' doesn't exist
Error Code: 1146
Call: SELECT adopter_key, agreed_to_policy, allows_error_reports, allows_statistics, city, contact_me, country, created, last_modified, department, email, first_name, last_name, organisation, postal_code, registered, statistic_key, street, street_no FROM oc_adopter_registration
Query: ReadAllQuery(name="Form.findAll" referenceClass=Form sql="SELECT adopter_key, agreed_to_policy, allows_error_reports, allows_statistics, city, contact_me, country, created, last_modified, department, email, first_name, last_name, organisation, postal_code, registered, statistic_key, street, street_no FROM oc_adopter_registration")
	at org.opencastproject.adopter.registration.FormRepositoryImpl.getForm(FormRepositoryImpl.java:141) ~[!/:?]
	at org.opencastproject.adopter.registration.FormRepositoryImpl.getForm(FormRepositoryImpl.java:117) ~[!/:?]
	at org.opencastproject.adopter.registration.AdopterRegistrationServiceImpl.retrieveFormData(AdopterRegistrationServiceImpl.java:55) ~[!/:?]
	at org.opencastproject.adopter.registration.AdopterRegistrationServiceImpl.retrieveFormData(AdopterRegistrationServiceImpl.java:30) ~[!/:?]
	at org.opencastproject.adopter.statistic.ScheduledDataCollector.run(ScheduledDataCollector.java:143) [!/:?]
	at java.util.TimerThread.mainLoop(Timer.java:556) [?:?]
	at java.util.TimerThread.run(Timer.java:506) [?:?]
Caused by: javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.7.v20200504-69f2c2b80d): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLSyntaxErrorException: (conn=262631) Table 'opencast7testdb.oc_adopter_registration' doesn't exist
Error Code: 1146
Call: SELECT adopter_key, agreed_to_policy, allows_error_reports, allows_statistics, city, contact_me, country, created, last_modified, department, email, first_name, last_name, organisation, postal_code, registered, statistic_key, street, street_no FROM oc_adopter_registration
Query: ReadAllQuery(name="Form.findAll" referenceClass=Form sql="SELECT adopter_key, agreed_to_policy, allows_error_reports, allows_statistics, city, contact_me, country, created, last_modified, department, email, first_name, last_name, organisation, postal_code, registered, statistic_key, street, street_no FROM oc_adopter_registration")
	at org.eclipse.persistence.internal.jpa.QueryImpl.getDetailedException(QueryImpl.java:391) ~[!/:?]
	at org.eclipse.persistence.internal.jpa.QueryImpl.executeReadQuery(QueryImpl.java:264) ~[!/:?]
	at org.eclipse.persistence.internal.jpa.QueryImpl.getSingleResult(QueryImpl.java:530) ~[!/:?]
	at org.eclipse.persistence.internal.jpa.EJBQueryImpl.getSingleResult(EJBQueryImpl.java:404) ~[!/:?]
	at org.opencastproject.adopter.registration.FormRepositoryImpl.getForm(FormRepositoryImpl.java:137) ~[!/:?]
	... 6 more
Caused by: org.eclipse.persistence.exceptions.DatabaseException:
Internal Exception: java.sql.SQLSyntaxErrorException: (conn=262631) Table 'opencast7testdb.oc_adopter_registration' doesn't exist
Error Code: 1146
Call: SELECT adopter_key, agreed_to_policy, allows_error_reports, allows_statistics, city, contact_me, country, created, last_modified, department, email, first_name, last_name, organisation, postal_code, registered, statistic_key, street, street_no FROM oc_adopter_registration
Query: ReadAllQuery(name="Form.findAll" referenceClass=Form sql="SELECT adopter_key, agreed_to_policy, allows_error_reports, allows_statistics, city, contact_me, country, created, last_modified, department, email, first_name, last_name, organisation, postal_code, registered, statistic_key, street, street_no FROM oc_adopter_registration")
	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:342) ~[!/:?]
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:691) ~[!/:?]
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeCall(DatabaseAccessor.java:567) ~[!/:?]
	at org.eclipse.persistence.internal.sessions.AbstractSession.basicExecuteCall(AbstractSession.java:2099) ~[!/:?]
	at org.eclipse.persistence.sessions.server.ServerSession.executeCall(ServerSession.java:603) ~[!/:?]
	at org.eclipse.persistence.sessions.server.ClientSession.executeCall(ClientSession.java:265) ~[!/:?]
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:277) ~[!/:?]
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:263) ~[!/:?]
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeSelectCall(DatasourceCallQueryMechanism.java:334) ~[!/:?]
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.selectAllRows(DatasourceCallQueryMechanism.java:746) ~[!/:?]
	at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.selectAllRowsFromTable(ExpressionQueryMechanism.java:2759) ~[!/:?]
	at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.selectAllRows(ExpressionQueryMechanism.java:2712) ~[!/:?]
	at org.eclipse.persistence.queries.ReadAllQuery.executeObjectLevelReadQuery(ReadAllQuery.java:584) ~[!/:?]
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeDatabaseQuery(ObjectLevelReadQuery.java:1232) ~[!/:?]
	at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:911) ~[!/:?]
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.execute(ObjectLevelReadQuery.java:1191) ~[!/:?]
	at org.eclipse.persistence.queries.ReadAllQuery.execute(ReadAllQuery.java:485) ~[!/:?]
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeInUnitOfWork(ObjectLevelReadQuery.java:1279) ~[!/:?]
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:2983) ~[!/:?]
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1898) ~[!/:?]
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1880) ~[!/:?]
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1845) ~[!/:?]
	at org.eclipse.persistence.internal.jpa.QueryImpl.executeReadQuery(QueryImpl.java:262) ~[!/:?]
	at org.eclipse.persistence.internal.jpa.QueryImpl.getSingleResult(QueryImpl.java:530) ~[!/:?]
	at org.eclipse.persistence.internal.jpa.EJBQueryImpl.getSingleResult(EJBQueryImpl.java:404) ~[!/:?]
	at org.opencastproject.adopter.registration.FormRepositoryImpl.getForm(FormRepositoryImpl.java:137) ~[!/:?]
	... 6 more
Caused by: java.sql.SQLSyntaxErrorException: (conn=262631) Table 'opencast7testdb.oc_adopter_registration' doesn't exist
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62) ~[?:?]
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:153) ~[?:?]
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:274) ~[?:?]
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:229) ~[?:?]
	at org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:149) ~[?:?]
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeQuery(ClientSidePreparedStatement.java:163) ~[?:?]
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:1471) ~[?:?]
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeSelect(DatabaseAccessor.java:1015) ~[!/:?]
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:651) ~[!/:?]
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeCall(DatabaseAccessor.java:567) ~[!/:?]
	at org.eclipse.persistence.internal.sessions.AbstractSession.basicExecuteCall(AbstractSession.java:2099) ~[!/:?]
	at org.eclipse.persistence.sessions.server.ServerSession.executeCall(ServerSession.java:603) ~[!/:?]
	at org.eclipse.persistence.sessions.server.ClientSession.executeCall(ClientSession.java:265) ~[!/:?]
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:277) ~[!/:?]
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:263) ~[!/:?]
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeSelectCall(DatasourceCallQueryMechanism.java:334) ~[!/:?]
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.selectAllRows(DatasourceCallQueryMechanism.java:746) ~[!/:?]
	at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.selectAllRowsFromTable(ExpressionQueryMechanism.java:2759) ~[!/:?]
	at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.selectAllRows(ExpressionQueryMechanism.java:2712) ~[!/:?]
	at org.eclipse.persistence.queries.ReadAllQuery.executeObjectLevelReadQuery(ReadAllQuery.java:584) ~[!/:?]
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeDatabaseQuery(ObjectLevelReadQuery.java:1232) ~[!/:?]
	at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:911) ~[!/:?]
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.execute(ObjectLevelReadQuery.java:1191) ~[!/:?]
	at org.eclipse.persistence.queries.ReadAllQuery.execute(ReadAllQuery.java:485) ~[!/:?]
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeInUnitOfWork(ObjectLevelReadQuery.java:1279) ~[!/:?]
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:2983) ~[!/:?]
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1898) ~[!/:?]
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1880) ~[!/:?]
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1845) ~[!/:?]
	at org.eclipse.persistence.internal.jpa.QueryImpl.executeReadQuery(QueryImpl.java:262) ~[!/:?]
	at org.eclipse.persistence.internal.jpa.QueryImpl.getSingleResult(QueryImpl.java:530) ~[!/:?]
	at org.eclipse.persistence.internal.jpa.EJBQueryImpl.getSingleResult(EJBQueryImpl.java:404) ~[!/:?]
	at org.opencastproject.adopter.registration.FormRepositoryImpl.getForm(FormRepositoryImpl.java:137) ~[!/:?]
	... 6 more
Caused by: org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException: Table 'opencast7testdb.oc_adopter_registration' doesn't exist
	at org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException.of(MariaDbSqlException.java:34) ~[?:?]
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.exceptionWithQuery(AbstractQueryProtocol.java:192) ~[?:?]
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.exceptionWithQuery(AbstractQueryProtocol.java:175) ~[?:?]
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:319) ~[?:?]
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:220) ~[?:?]
	at org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:149) ~[?:?]
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeQuery(ClientSidePreparedStatement.java:163) ~[?:?]
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:1471) ~[?:?]
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeSelect(DatabaseAccessor.java:1015) ~[!/:?]
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:651) ~[!/:?]
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeCall(DatabaseAccessor.java:567) ~[!/:?]
	at org.eclipse.persistence.internal.sessions.AbstractSession.basicExecuteCall(AbstractSession.java:2099) ~[!/:?]
	at org.eclipse.persistence.sessions.server.ServerSession.executeCall(ServerSession.java:603) ~[!/:?]
	at org.eclipse.persistence.sessions.server.ClientSession.executeCall(ClientSession.java:265) ~[!/:?]
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:277) ~[!/:?]
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:263) ~[!/:?]
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeSelectCall(DatasourceCallQueryMechanism.java:334) ~[!/:?]
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.selectAllRows(DatasourceCallQueryMechanism.java:746) ~[!/:?]
	at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.selectAllRowsFromTable(ExpressionQueryMechanism.java:2759) ~[!/:?]
	at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.selectAllRows(ExpressionQueryMechanism.java:2712) ~[!/:?]
	at org.eclipse.persistence.queries.ReadAllQuery.executeObjectLevelReadQuery(ReadAllQuery.java:584) ~[!/:?]
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeDatabaseQuery(ObjectLevelReadQuery.java:1232) ~[!/:?]
	at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:911) ~[!/:?]
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.execute(ObjectLevelReadQuery.java:1191) ~[!/:?]
	at org.eclipse.persistence.queries.ReadAllQuery.execute(ReadAllQuery.java:485) ~[!/:?]
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeInUnitOfWork(ObjectLevelReadQuery.java:1279) ~[!/:?]
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:2983) ~[!/:?]
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1898) ~[!/:?]
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1880) ~[!/:?]
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1845) ~[!/:?]
	at org.eclipse.persistence.internal.jpa.QueryImpl.executeReadQuery(QueryImpl.java:262) ~[!/:?]
	at org.eclipse.persistence.internal.jpa.QueryImpl.getSingleResult(QueryImpl.java:530) ~[!/:?]
	at org.eclipse.persistence.internal.jpa.EJBQueryImpl.getSingleResult(EJBQueryImpl.java:404) ~[!/:?]
	at org.opencastproject.adopter.registration.FormRepositoryImpl.getForm(FormRepositoryImpl.java:137) ~[!/:?]
	... 6 more
Caused by: java.sql.SQLException: Table 'opencast7testdb.oc_adopter_registration' doesn't exist
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1681) ~[?:?]
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1543) ~[?:?]
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1506) ~[?:?]
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:316) ~[?:?]
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:220) ~[?:?]
	at org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:149) ~[?:?]
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeQuery(ClientSidePreparedStatement.java:163) ~[?:?]
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:1471) ~[?:?]
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeSelect(DatabaseAccessor.java:1015) ~[!/:?]
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:651) ~[!/:?]
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeCall(DatabaseAccessor.java:567) ~[!/:?]
	at org.eclipse.persistence.internal.sessions.AbstractSession.basicExecuteCall(AbstractSession.java:2099) ~[!/:?]
	at org.eclipse.persistence.sessions.server.ServerSession.executeCall(ServerSession.java:603) ~[!/:?]
	at org.eclipse.persistence.sessions.server.ClientSession.executeCall(ClientSession.java:265) ~[!/:?]
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:277) ~[!/:?]
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:263) ~[!/:?]
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeSelectCall(DatasourceCallQueryMechanism.java:334) ~[!/:?]
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.selectAllRows(DatasourceCallQueryMechanism.java:746) ~[!/:?]
	at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.selectAllRowsFromTable(ExpressionQueryMechanism.java:2759) ~[!/:?]
	at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.selectAllRows(ExpressionQueryMechanism.java:2712) ~[!/:?]
	at org.eclipse.persistence.queries.ReadAllQuery.executeObjectLevelReadQuery(ReadAllQuery.java:584) ~[!/:?]
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeDatabaseQuery(ObjectLevelReadQuery.java:1232) ~[!/:?]
	at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:911) ~[!/:?]
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.execute(ObjectLevelReadQuery.java:1191) ~[!/:?]
	at org.eclipse.persistence.queries.ReadAllQuery.execute(ReadAllQuery.java:485) ~[!/:?]
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeInUnitOfWork(ObjectLevelReadQuery.java:1279) ~[!/:?]
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:2983) ~[!/:?]
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1898) ~[!/:?]
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1880) ~[!/:?]
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1845) ~[!/:?]
	at org.eclipse.persistence.internal.jpa.QueryImpl.executeReadQuery(QueryImpl.java:262) ~[!/:?]
	at org.eclipse.persistence.internal.jpa.QueryImpl.getSingleResult(QueryImpl.java:530) ~[!/:?]
	at org.eclipse.persistence.internal.jpa.EJBQueryImpl.getSingleResult(EJBQueryImpl.java:404) ~[!/:?]
	at org.opencastproject.adopter.registration.FormRepositoryImpl.getForm(FormRepositoryImpl.java:137) ~[!/:?]
	... 6 more
```

_EDIT(@lkiesow ): Formatting…_

**Comment by lkiesow** [comment]
Did you allow Opencast to create the table?

**Comment by slaudel** [comment]
I think so.
```MariaDB [opencast7testdb]> show grants;
+---------------------------------------------------------------------------------------------------------------------------+
| Grants for opencasttest@urzopencastadm3.domain                                                                                   |
+---------------------------------------------------------------------------------------------------------------------------+
| GRANT USAGE ON *.* TO 'opencasttest'@'urzopencastadm3.domain' IDENTIFIED BY PASSWORD 'PASSWD' |
| GRANT ALL PRIVILEGES ON `opencast7testdb`.* TO 'opencasttest'@'urzopencastadm3.domain'                                           |
| GRANT ALL PRIVILEGES ON `opencasttest2db`.* TO 'opencasttest'@'urzopencastadm3.domain'                                           |
+--------------------------------------------------------------------------------------------------------------------------+```

**Comment by lkiesow** [comment]
Can you check which SQL statement fails on your database? We are running/supporting 15+ 10.x clusters by now with different MySQL, MariaDB and PostgreSQL versions but have never seen this issue.

**Comment by Gao-Jun** [comment]
I encounted a similar problem yesterday when I purge a database and create a new one.
After some digging work, finally, I found I misspell this config line `org.opencastproject.db.jdbc.url` in `custom.properties`
So, @slaudel  may be you can check whether your jdbc url is something like `jdbc:mysql://maria.ip/opencast?useMysqlMetadata=true`

**Comment by gregorydlogan** [comment]
Is this still an issue?

**Comment by mliradelc** [comment]
I will close this issue because the user haven't answered if this is still a problem.
@slaudel If you are still having this problem, please comment again to reopen this issue.

**Comment by slaudel** [comment]
Sorry for not reporting back. For those stumbling upon this issue, I found a solution in this thread from the german speaking Google group: [https://groups.google.com/a/opencast.org/g/anwender/c/8qD5zEOYtvo](https://groups.google.com/a/opencast.org/g/anwender/c/8qD5zEOYtvo).
