### ISSUE TITLE
ffmpeg error oc 11.x

### ISSUE THREAD

**Issue by luepschenk** [opencast/opencast#3358]
I installed oc 11.2 via ubuntu Package as distributed system (and also tested allinone) and I receive an ffmpeg inspection error after uploading.

Package: ffmpeg-dist
Version: 20211115053315-N-104552-g23a1f11d02-1

Following are the allinone Error-logs:

2022-01-17T15:18:41,819 | WARN  | (MediaInspector:298) - Error enriching track http://192.168.178.86:8080/files/mediapackage/c7e5a990-39df-4a50-a735-e4c986344a6e/5aaeac22-cd46-47cc-a820-c27357e7b641/180926ac_a5e8_4887_9b72_48976d66aa1f.mp4
org.opencastproject.inspection.api.MediaInspectionException: org.opencastproject.inspection.ffmpeg.api.MediaAnalyzerException: Frame analyzer ffprobe exited with code 139
	at org.opencastproject.inspection.ffmpeg.MediaInspector.getFileMetadata(MediaInspector.java:406) ~[!/:?]
	at org.opencastproject.inspection.ffmpeg.MediaInspector.enrichTrack(MediaInspector.java:227) [!/:?]
	at org.opencastproject.inspection.ffmpeg.MediaInspector.enrich(MediaInspector.java:187) [!/:?]
	at org.opencastproject.inspection.ffmpeg.MediaInspectionServiceImpl.process(MediaInspectionServiceImpl.java:157) [!/:?]
	at org.opencastproject.job.api.AbstractJobProducer$JobRunner.call(AbstractJobProducer.java:313) [!/:?]
	at org.opencastproject.job.api.AbstractJobProducer$JobRunner.call(AbstractJobProducer.java:272) [!/:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: org.opencastproject.inspection.ffmpeg.api.MediaAnalyzerException: Frame analyzer ffprobe exited with code 139
	at org.opencastproject.inspection.ffmpeg.FFmpegAnalyzer.analyze(FFmpegAnalyzer.java:121) ~[!/:?]
	at org.opencastproject.inspection.ffmpeg.MediaInspector.getFileMetadata(MediaInspector.java:378) ~[!/:?]
	... 9 more
2022-01-17T15:18:41,866 | INFO  | (ServiceRegistryJpaImpl:2564) - State set to WARNING for current service org.opencastproject.inspection on host http://192.168.178.86:8080
2022-01-17T15:18:41,915 | ERROR | (AbstractJobProducer$JobRunner:343) - Error handling operation 'Enrich':
org.opencastproject.serviceregistry.api.ServiceRegistryException: Error handling operation 'Enrich'
	at org.opencastproject.inspection.ffmpeg.MediaInspectionServiceImpl.process(MediaInspectionServiceImpl.java:168) ~[?:?]
	at org.opencastproject.job.api.AbstractJobProducer$JobRunner.call(AbstractJobProducer.java:313) [!/:?]
	at org.opencastproject.job.api.AbstractJobProducer$JobRunner.call(AbstractJobProducer.java:272) [!/:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: org.opencastproject.inspection.api.MediaInspectionException: org.opencastproject.inspection.ffmpeg.api.MediaAnalyzerException: Frame analyzer ffprobe exited with code 139
	at org.opencastproject.inspection.ffmpeg.MediaInspector.getFileMetadata(MediaInspector.java:406) ~[?:?]
	at org.opencastproject.inspection.ffmpeg.MediaInspector.enrichTrack(MediaInspector.java:227) ~[?:?]
	at org.opencastproject.inspection.ffmpeg.MediaInspector.enrich(MediaInspector.java:187) ~[?:?]
	at org.opencastproject.inspection.ffmpeg.MediaInspectionServiceImpl.process(MediaInspectionServiceImpl.java:157) ~[?:?]
	... 6 more
Caused by: org.opencastproject.inspection.ffmpeg.api.MediaAnalyzerException: Frame analyzer ffprobe exited with code 139
	at org.opencastproject.inspection.ffmpeg.FFmpegAnalyzer.analyze(FFmpegAnalyzer.java:121) ~[?:?]
	at org.opencastproject.inspection.ffmpeg.MediaInspector.getFileMetadata(MediaInspector.java:378) ~[?:?]
	at org.opencastproject.inspection.ffmpeg.MediaInspector.enrichTrack(MediaInspector.java:227) ~[?:?]
	at org.opencastproject.inspection.ffmpeg.MediaInspector.enrich(MediaInspector.java:187) ~[?:?]
	at org.opencastproject.inspection.ffmpeg.MediaInspectionServiceImpl.process(MediaInspectionServiceImpl.java:157) ~[?:?]
	... 6 more
2022-01-17T15:18:44,789 | ERROR | (WorkflowOperationWorker:143) - Workflow operation 'operation:'inspect', position:3, state:'FAILED'' failed
org.opencastproject.workflow.api.WorkflowOperationException: Track http://192.168.178.86:8080/files/mediapackage/c7e5a990-39df-4a50-a735-e4c986344a6e/5aaeac22-cd46-47cc-a820-c27357e7b641/180926ac_a5e8_4887_9b72_48976d66aa1f.mp4 could not be inspected
	at org.opencastproject.workflow.handler.inspection.InspectWorkflowOperationHandler.start(InspectWorkflowOperationHandler.java:166) ~[?:?]
	at org.opencastproject.workflow.impl.WorkflowOperationWorker.start(WorkflowOperationWorker.java:193) ~[!/:?]
	at org.opencastproject.workflow.impl.WorkflowOperationWorker.execute(WorkflowOperationWorker.java:116) [!/:?]
	at org.opencastproject.workflow.impl.WorkflowServiceImpl.runWorkflowOperation(WorkflowServiceImpl.java:795) [!/:?]
	at org.opencastproject.workflow.impl.WorkflowServiceImpl.process(WorkflowServiceImpl.java:1832) [!/:?]
	at org.opencastproject.workflow.impl.WorkflowServiceImpl$JobRunner.call(WorkflowServiceImpl.java:2271) [!/:?]
	at org.opencastproject.workflow.impl.WorkflowServiceImpl$JobRunner.call(WorkflowServiceImpl.java:2237) [!/:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]

**Comment by gregorydlogan** [comment]
This looks like `ffprobe` is having trouble figuring out what the file is.  Are you uploading a video file, or something else?  Opencast only support video files.

**Comment by luepschenk** [comment]
I tried different mp4 files. The files work in our oc 10.x produktion cluster.

**Comment by gregorydlogan** [comment]
Then there's some kind of configuration issue, assuming the ffmpeg versions are both from our repository.  Does http://192.168.178.86:8080/files/mediapackage/c7e5a990-39df-4a50-a735-e4c986344a6e/5aaeac22-cd46-47cc-a820-c27357e7b641/180926ac_a5e8_4887_9b72_48976d66aa1f.mp4 download and play back correctly for you?

**Comment by luepschenk** [comment]
Yes ffmpeg is from the Ubuntu opencast 11.x stable repo. I can Download the Video and it does run normaly. I tried using ffmpeg from the Ubuntu default mirror. The Inspection works with that Version.(but has other issues later in the workflow.)

**Comment by gregorydlogan** [comment]
Any chance you can upload a sample of the problematic media somewhere?  This sounds like something that ffmpeg should be able to handle (cf the Ubuntu version working), but the version we're using doesn't.

I can certainly package up the most recent version we have and put it in the test repository tomorrow, but I'm not sure if that would even help.

**Comment by luepschenk** [comment]
this specific file is linked below but I tried different videos and also lectures we recorded and processed with our oc 10 cluster with the same result.

https://nc.rubcast.ruhr-uni-bochum.de/index.php/s/gjYs6RFm48Woo7g

**Comment by luepschenk** [comment]
Hey Greg,
I just purged ffmpeg-dist from opencast 11.x stable and installed ffmpeg-dist from opencast 10.x stable and it workes perfectly fine

It is Version: 20210620044626-N-102774-g2cf95f2dd9-1

**Comment by gregorydlogan** [comment]
That's really, really odd considering the media you've posted isn't in some weird format.  I wonder if the specific point revision we've picked just happens to not like something in the file.

@mtneug @lkiesow I was talking on Matrix about packaging up a ffmpeg 5.x release, maybe we should pick a recent 4.x and update that as well?  Have you had anyone else with issues?

**Comment by lkiesow** [comment]
I never put the new one in stable and still have the old one in the RPM repository since I never found time to extensively test the new one. I do know of issues. But they shouldn't affect Opencast. It's basically that this FFmpeg segfaults when trying to open encrypted network streams if you have a somewhat new version of glibc. So I just wanted the new one for streaming, …

The version I linked earlier today in Matrix fixes that, which is why I was considering putting that one into the repository. It is already running on develop.opencast.org though.

If anyone wants to help testing, the new version can be found at:

- https://s3.opencast.org/opencast-ffmpeg-static/ffmpeg-20220117045355-N-105291-gdcc9454ab9.tar.xz

Just unpack it and copy it to the correct place, these are static binaries.

**Comment by gregorydlogan** [comment]
The version on stable.opencast.org (N-98643-gffa6072fc7) doesn't seem to mind the file either.  I'm thinking this is down to a bug in a specific ffmpeg point revision, and/or its interactions with Opencast's encoding profiles.

@luepschenk, if 10.x stable's version works for you then I would stick with that, and periodically test 11.x's stable to see if things have resolved.  My `ffmpeg-dist` package is just a wrapper around one of the static builds from s3, so it's not going to hurt anything to swap ffmpegs until you find one that works.

**Comment by Sebastinus-Schulze** [comment]
Hello,

I got the same issue on my Ubuntu with Opencast 11.2 that Kevin discovered.
ffmpeg version N-104552-g23a1f11d02

After replacing this version with the ffmpeg-version N-105291-gdcc9454ab9 provided by Lars, the errors disappeared and the processing of the videos are successful.

Many greetings
Sebastian

**Comment by lkiesow** [comment]
Based on Greg's description, the issue should be resolved for now.
The resolution plus potential steps to roll back are described here:

- https://groups.google.com/a/opencast.org/g/users/c/a5zJtGBBvTQ
