### ISSUE TITLE
Workflow Tests Racing

### ISSUE THREAD

**Issue by gregorydlogan** [opencast/opencast#3814]
**Describe the bug**
Starting with `12.x`, the workflow service implementation tests randomly deadlock, resulting in build timeouts and failures.  The GH logs unfortunately don't give you anything to go on, but (finally) reproducing this locally let me attach a debugger

**To Reproduce**
1. Move to workflow service impl
2. `while true; do mvn test; done`
3. Go get a *lot* of coffee
4. Eventually see that the tests have stopped
5. Go get *even more* coffee
6. Get stack traces

```
May 30, 2022 5:18:47 PM org.eclipse.persistence.session./file:/home/greg/.m2/repository/org/opencastproject/opencast-workflow-service-api/12
-SNAPSHOT/opencast-workflow-service-api-12-SNAPSHOT.jar_org.opencastproject.workflow.api_nonJtaDataSource=1739806152
WARNING:
Local Exception Stack:
Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.5.v20191016-ea124dd158): org.eclipse.persistence.exceptions.DatabaseExcepti
on
Internal Exception: org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: "PRIMARY KEY ON PUBLIC.OC_WORKFLOW(ID)" [23505-176]
Error Code: 23505
Call: UPDATE oc_workflow SET date_completed = ?, state = ? WHERE (id = ?)
        bind => [3 parameters bound]
Query: UpdateObjectQuery(Workflow {3})
        at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:333)
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeDirectNoSelect(DatabaseAccessor.java:908)
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeNoSelect(DatabaseAccessor.java:970)
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:640)
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeCall(DatabaseAccessor.java:567)
        at org.eclipse.persistence.internal.sessions.AbstractSession.basicExecuteCall(AbstractSession.java:2099)
        at org.eclipse.persistence.sessions.server.ClientSession.executeCall(ClientSession.java:313)
        at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:275)
        at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:261)
        at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.updateObject(DatasourceCallQueryMechanism.java:848)
        at org.eclipse.persistence.internal.queries.StatementQueryMechanism.updateObject(StatementQueryMechanism.java:437)
        at org.eclipse.persistence.internal.queries.DatabaseQueryMechanism.updateObjectForWriteWithChangeSet(DatabaseQueryMechanism.java:109
3)
        at org.eclipse.persistence.queries.UpdateObjectQuery.executeCommitWithChangeSet(UpdateObjectQuery.java:86)
        at org.eclipse.persistence.internal.queries.DatabaseQueryMechanism.executeWriteWithChangeSet(DatabaseQueryMechanism.java:316)
        at org.eclipse.persistence.queries.WriteObjectQuery.executeDatabaseQuery(WriteObjectQuery.java:60)
        at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:911)
        at org.eclipse.persistence.queries.DatabaseQuery.executeInUnitOfWork(DatabaseQuery.java:810)
        at org.eclipse.persistence.queries.ObjectLevelModifyQuery.executeInUnitOfWorkObjectLevelModifyQuery(ObjectLevelModifyQuery.java:110)
        at org.eclipse.persistence.queries.ObjectLevelModifyQuery.executeInUnitOfWork(ObjectLevelModifyQuery.java:87)
        at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:2983)
        at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1898)
        at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1880)
        at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1830)
        at org.eclipse.persistence.internal.sessions.CommitManager.commitChangedObjectsForClassWithChangeSet(CommitManager.java:275)
        at org.eclipse.persistence.internal.sessions.CommitManager.commitAllObjectsForClassWithChangeSet(CommitManager.java:195)
        at org.eclipse.persistence.internal.sessions.CommitManager.commitAllObjectsWithChangeSet(CommitManager.java:141)
        at org.eclipse.persistence.internal.sessions.AbstractSession.writeAllObjectsWithChangeSet(AbstractSession.java:4398)
        at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitToDatabase(UnitOfWorkImpl.java:1495)
        at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitToDatabaseWithChangeSet(UnitOfWorkImpl.java:1585)
        at org.eclipse.persistence.internal.sessions.RepeatableWriteUnitOfWork.commitRootUnitOfWork(RepeatableWriteUnitOfWork.java:280)
        at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitAndResume(UnitOfWorkImpl.java:1222)
        at org.eclipse.persistence.internal.jpa.transaction.EntityTransactionImpl.commit(EntityTransactionImpl.java:136)
        at org.opencastproject.workflow.api.WorkflowServiceDatabaseImpl.updateInDatabase(WorkflowServiceDatabaseImpl.java:355)
        at org.opencastproject.workflow.impl.WorkflowServiceImpl.update(WorkflowServiceImpl.java:1253)
        at org.opencastproject.workflow.impl.WorkflowServiceImpl.runWorkflowOperation(WorkflowServiceImpl.java:757)
        at org.opencastproject.workflow.impl.WorkflowServiceImpl.process(WorkflowServiceImpl.java:1736)
        at org.opencastproject.workflow.impl.WorkflowServiceImpl$JobRunner.call(WorkflowServiceImpl.java:2097)
        at org.opencastproject.workflow.impl.WorkflowServiceImpl$JobRunner.call(WorkflowServiceImpl.java:2063)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: "PRIMARY KEY ON PUBLIC.OC_WORKFLOW(ID)" [23505-176]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
        at org.h2.message.DbException.get(DbException.java:178)
        at org.h2.message.DbException.get(DbException.java:154)
        at org.h2.index.PageDataIndex.getNewDuplicateKeyException(PageDataIndex.java:166)
        at org.h2.index.PageDataIndex.add(PageDataIndex.java:144)
        at org.h2.table.RegularTable.addRow(RegularTable.java:120)
        at org.h2.engine.UndoLogRecord.undo(UndoLogRecord.java:111)
        at org.h2.engine.Session.rollbackTo(Session.java:595)
        at org.h2.command.Command.executeUpdate(Command.java:278)
        at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:158)
        at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:144)
        at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:1502)
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeDirectNoSelect(DatabaseAccessor.java:898)
        ... 40 more
```

**Comment by gregorydlogan** [comment]
The debugger points me at

https://github.com/opencast/opencast/blob/da079663af8ff4f2b21051acdce47b54380e31ff/modules/workflow-service-impl/src/test/java/org/opencastproject/workflow/impl/WorkflowServiceImplTest.java#L619-L623

which leads back to WorkflowServiceImpl's `fireListeners` method, which is (only) called by WorkflowServiceImpl's `update` method.

**Comment by lkiesow** [comment]
So, it fails to insert or update an event in the database. That probably leads to the workflow being in a different state than expected. That leads to the tests forever waiting for the expected state. Possible causes that come to mind:

1. The ID is derived from the job id. Tests may feed this invalid data, starting “the same” job over and over again, potentially with no proper cleanup in some cases
2. Writing an event, the transaction is not yet finished and then, Opencast tries to write the event to the database twice.

**Comment by gregorydlogan** [comment]
Running the same test this morning, and it's deadlocked at https://github.com/opencast/opencast/blob/da079663af8ff4f2b21051acdce47b54380e31ff/modules/workflow-service-impl/src/test/java/org/opencastproject/workflow/impl/HoldStateTest.java#L278

Definitely related to the listener, or the updates.
