### ISSUE TITLE
inbox.datetime.format does not support date only values

### ISSUE THREAD

**Issue by Rillke** [opencast/opencast#3817]
**Describe the bug**
A clear and concise description of what you see:
When configuring the inbox to with only a date (and no time) to be matched, you'll see a `DateTimeParseException` when putting video files into the inbox matching that pattern.

**To Reproduce**
1. Configure your inbox:
2. `inbox.datetime.format = yyyy-MM-dd`
3. `inbox.metadata.regex = (?<created>....-..-..)[ _](?<spatial>[^ ]+) (?<title>.+)\\.(?:mp4|mov|MP4|MOV)`.
4. Drop a file named `2021-12-10 hs1 Biology 101.mp4` into the inbox.
5. See admin error log:

```
java.time.format.DateTimeParseException: Text '2022-05-24' could not be parsed: Unable to obtain LocalDateTime from TemporalAccessor: {},ISO resolved to 2022-05-24 of type java.time.format.Parsed
	at java.time.format.DateTimeFormatter.createError(DateTimeFormatter.java:2017) ~[?:?]
	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1952) ~[?:?]
	at java.time.LocalDateTime.parse(LocalDateTime.java:492) ~[?:?]
	at org.opencastproject.ingest.scanner.Ingestor$RetriableIngestJob.lambda$call$2(Ingestor.java:198) [!/:?]
	at org.opencastproject.security.util.SecurityContext.runInContext(SecurityContext.java:58) [!/:?]
	at org.opencastproject.ingest.scanner.Ingestor$RetriableIngestJob.call(Ingestor.java:158) [!/:?]
	at org.opencastproject.ingest.scanner.Ingestor$RetriableIngestJob.call(Ingestor.java:131) [!/:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.time.DateTimeException: Unable to obtain LocalDateTime from TemporalAccessor: {},ISO resolved to 2022-05-24 of type java.time.format.Parsed
	at java.time.LocalDateTime.from(LocalDateTime.java:461) ~[?:?]
	at java.time.format.Parsed.query(Parsed.java:235) ~[?:?]
	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1948) ~[?:?]
	... 11 more
Caused by: java.time.DateTimeException: Unable to obtain LocalTime from TemporalAccessor: {},ISO resolved to 2022-05-24 of type java.time.format.Parsed
	at java.time.LocalTime.from(LocalTime.java:431) ~[?:?]
	at java.time.LocalDateTime.from(LocalDateTime.java:457) ~[?:?]
	at java.time.format.Parsed.query(Parsed.java:235) ~[?:?]
	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1948) ~[?:?]
	... 11 more
```

It would be helpful if times could be omitted.

**Environment Information**
 - OS: based on Opencast Docker image
 - Opencast version with minor release 11.7

**Comment by lkiesow** [comment]
The underlying metadata will expect a date and time in the end. How would you expect this to work? Would it map those dates to a fixed time?

**Comment by Rillke** [comment]
One of our users said: Can you remove the time from the pattern, to save me some work? I said, "no problem" and changed the pattern because without looking at the implementation it's not obvious that a time is strictly required.

> Would it map those dates to a fixed time?

Yes. I like how [answers the issue](https://stackoverflow.com/a/39685202/2683737) using DateTimeFormatterBuilder and default values for optional fields.

If we don't agree here, it would be helpful to throw an error while reading the properties file and to document the fact.

**Comment by lkiesow** [comment]
I don't mind having a default time and the linked solution looks good.
