### ISSUE TITLE
Unable to use Vosk-cli

### ISSUE THREAD

**Issue by gregorydlogan** [opencast/opencast#3841]
**Describe the bug**
I've installed [vosk-cli](https://github.com/elan-ev/vosk-cli) more or less how it's supposed to be - it's installed for my user, not in a virtual env.  When testing, I get the following error:

```
2022-06-06 10:02:06,230 | ERROR | (AbstractJobProducer$JobRunner:343) - Error handling operation 'speechtotext':
org.opencastproject.speechtotext.api.SpeechToTextServiceException: Error while generating subtitle from http://localhost:8080/files/mediapackage/160a0bef-9aa6-4b5d-b98c-5a1a8eeba28d/4a87482a-9e09-4a3c-8b95-9e695604b5ca/nonsegment_audio.mpg
        at org.opencastproject.speechtotext.impl.SpeechToTextServiceImpl.process(SpeechToTextServiceImpl.java:166) ~[?:?]
        at org.opencastproject.job.api.AbstractJobProducer$JobRunner.call(AbstractJobProducer.java:313) [!/:?]
        at org.opencastproject.job.api.AbstractJobProducer$JobRunner.call(AbstractJobProducer.java:272) [!/:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: org.opencastproject.speechtotext.api.SpeechToTextEngineException: org.opencastproject.speechtotext.api.SpeechToTextEngineException: Vosk exited abnormally with status 1 (command: [vosk-cli, -i, /home/greg/opencast/upstream/build/opencast-dist-allinone/data/opencast/workspace/mediapackage/160a0bef-9aa6-4b5d-b98c-5a1a8eeba28d/4a87482a-9e09-4a3c-8b95-9e695604b5ca/nonsegment_audio.mpg, -o, /home/greg/opencast/upstream/build/opencast-dist-allinone/data/opencast/workspace/collection/subtitles/tmp_719_nonsegment_audio.vtt, -l, demo])
 Output:
Traceback (most recent call last):
  File "/home/greg/.local/bin/vosk-cli", line 5, in <module>
    from scripts.transcribe import main
ModuleNotFoundError: No module named 'scripts'

        at org.opencastproject.speechtotext.impl.engine.VoskEngine.generateSubtitlesFile(VoskEngine.java:123) ~[?:?]
        at org.opencastproject.speechtotext.impl.SpeechToTextServiceImpl.process(SpeechToTextServiceImpl.java:156) ~[?:?]
        ... 6 more
Caused by: org.opencastproject.speechtotext.api.SpeechToTextEngineException: Vosk exited abnormally with status 1 (command: [vosk-cli, -i, /home/greg/opencast/upstream/build/opencast-dist-allinone/data/opencast/workspace/mediapackage/160a0bef-9aa6-4b5d-b98c-5a1a8eeba28d/4a87482a-9e09-4a3c-8b95-9e695604b5ca/nonsegment_audio.mpg, -o, /home/greg/opencast/upstream/build/opencast-dist-allinone/data/opencast/workspace/collection/subtitles/tmp_719_nonsegment_audio.vtt, -l, demo])
 Output:
Traceback (most recent call last):
  File "/home/greg/.local/bin/vosk-cli", line 5, in <module>
    from scripts.transcribe import main
ModuleNotFoundError: No module named 'scripts'

        at org.opencastproject.speechtotext.impl.engine.VoskEngine.generateSubtitlesFile(VoskEngine.java:115) ~[?:?]
        at org.opencastproject.speechtotext.impl.SpeechToTextServiceImpl.process(SpeechToTextServiceImpl.java:156) ~[?:?]
        ... 6 more
2022-06-06 10:02:09,165 | ERROR | (WorkflowOperationWorker:140) - Workflow operation 'operation:'speechtotext, state:'FAILED'' failed
org.opencastproject.workflow.api.WorkflowOperationException: Speech-to-Text job for media package '160a0bef-9aa6-4b5d-b98c-5a1a8eeba28d' failed
        at org.opencastproject.workflow.handler.speechtotext.SpeechToTextWorkflowOperationHandler.createSubtitle(SpeechToTextWorkflowOperationHandler.java:181) ~[?:?]
        at org.opencastproject.workflow.handler.speechtotext.SpeechToTextWorkflowOperationHandler.start(SpeechToTextWorkflowOperationHandler.java:146) ~[?:?]
        at org.opencastproject.workflow.impl.WorkflowOperationWorker.start(WorkflowOperationWorker.java:212) ~[!/:?]
        at org.opencastproject.workflow.impl.WorkflowOperationWorker.execute(WorkflowOperationWorker.java:117) [!/:?]
        at org.opencastproject.workflow.impl.WorkflowServiceImpl.runWorkflowOperation(WorkflowServiceImpl.java:719) [!/:?]
        at org.opencastproject.workflow.impl.WorkflowServiceImpl.process(WorkflowServiceImpl.java:1736) [!/:?]
        at org.opencastproject.workflow.impl.WorkflowServiceImpl$JobRunner.call(WorkflowServiceImpl.java:2097) [!/:?]
        at org.opencastproject.workflow.impl.WorkflowServiceImpl$JobRunner.call(WorkflowServiceImpl.java:2063) [!/:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```

This happens every time.  I have not modified my vosk config.  Copy and pasting the command from the error works as expected so it's not that `vosk-cli` isn't working, it's that something in Opencast isn't running `vosk-cli` correctly.

Previously filed at https://github.com/elan-ev/vosk-cli/issues/5, when I thought this was a vosk bug.

**Comment by lkiesow** [comment]
This is certainly not an Opencast bug. It will just start the tool. That's it.
My guess would still be your deployment.
The most likely problem I would say is that you deployed this using `pip` as your user. Which will require it to be run as your user and might (or might not) require your environment variables.

**Comment by gregorydlogan** [comment]
Opencast is, as far as I know, running as my user.  I guess if `start-opencast` or its sub-scripts is munging the env variables that might explain things.  Although looking at the output of `env`, I don't have anything obvious defined, aside from `$PATH`, which contains `$HOME/.local/bin` where `vosk-cli` put itself.

**Comment by gregorydlogan** [comment]
Of course, testing this *with* a venv works as expected, so who knows.  I still think someone (an adopter) is going to run into this, but without being able to better define what's wrong I'm not sure how to continue debugging.  In the meantime, if you're an adopter and running into this, try building `vosk-cli` in a venv and see if that fixes things.
