### ISSUE TITLE
MariaDB upgrade script for 12.x fails over Character Set Issue

### ISSUE THREAD

**Issue by mliradelc** [opencast/opencast#4028]
**Describe the bug**
When try to upgrade Opencast MariaDB script with a database with a Collation set to `utf8_general_ci`, the script fails with the error:

```
# python3 /usr/share/opencast/docs/upgrade/11_to_12/workflows_mariadb.py
Creating connection to database...
Traceback (most recent call last):
  File "/usr/share/opencast/docs/upgrade/11_to_12/workflows_mariadb.py", line 121, in <module>
    connection = create_connection(host, user, password, database)
  File "/usr/share/opencast/docs/upgrade/11_to_12/workflows_mariadb.py", line 39, in create_connection
    database=db_name
  File "/home/ladmin/venv/lib64/python3.6/site-packages/mysql/connector/pooling.py", line 287, in connect
    return MySQLConnection(*args, **kwargs)
  File "/home/ladmin/venv/lib64/python3.6/site-packages/mysql/connector/connection.py", line 137, in __init__
    self.connect(**kwargs)
  File "/home/ladmin/venv/lib64/python3.6/site-packages/mysql/connector/abstracts.py", line 1095, in connect
    self._open_connection()
  File "/home/ladmin/venv/lib64/python3.6/site-packages/mysql/connector/connection.py", line 544, in _open_connection
    self.set_converter_class(self._converter_class)
  File "/home/ladmin/venv/lib64/python3.6/site-packages/mysql/connector/abstracts.py", line 1271, in set_converter_class
    self.converter = convclass(charset_name, self._use_unicode)
  File "/home/ladmin/venv/lib64/python3.6/site-packages/mysql/connector/conversion.py", line 136, in __init__
    MySQLConverterBase.__init__(self, charset, use_unicode, str_fallback)
  File "/home/ladmin/venv/lib64/python3.6/site-packages/mysql/connector/conversion.py", line 59, in __init__
    self.set_charset(charset)
  File "/home/ladmin/venv/lib64/python3.6/site-packages/mysql/connector/conversion.py", line 73, in set_charset
    self.charset_id = CharacterSet.get_charset_info(self.charset)[0]
  File "/home/ladmin/venv/lib64/python3.6/site-packages/mysql/connector/constants.py", line 775, in get_charset_info
    info = cls.get_default_collation(charset)
  File "/home/ladmin/venv/lib64/python3.6/site-packages/mysql/connector/constants.py", line 746, in get_default_collation
    raise ProgrammingError(f"Character set '{charset}' unsupported")
mysql.connector.errors.ProgrammingError: Character set 'utf8' unsupported
```

**To Reproduce**
1. Have a MariaDB Database configured to `utf8_general_ci`
2. Execute the migration Script

**Environment Information**
 - OS: Rocky Linux 8
 - Opencast version 11.9 upgrading to 12.0

**Comment by mliradelc** [comment]
UPDATE:

Thanks the tip from @marwyg, downgrading `mysql-connector-python` to version `8.0.29` solves the issue

**Comment by mliradelc** [comment]
#4032 and #4033  Make aware about that issue, I tried to add a bug report to Mysql connector repo, but their UI is not so friendly

**Comment by DZenker** [comment]
I had the same issue on a CentOS 7 which could be solved by downgrading mysql-connector-python, too.
**But:** On another CentOS 7 system the former version could not be installed directly (_pip3 install mysql-connector-python==8.0.29_) due to a missing dependency (error: "_protobuf requires Python '>=3.7' but the running Python is 3.6.8_")

**Work-around:**
1. Installation of the current mysql-connector-python version, which successfully installs the protobuf dependency.
2. Deinstallation of mysql-connector-python and installation of the 8.0.29 version as mentioned above
