### ISSUE TITLE
Update Event Persmissions through Series Fails in oc-12

### ISSUE THREAD

**Issue by CGreweling** [opencast/opencast#4110]
**Describe the bug**
Update Event Persmissions fails with aws.s3 error
Service org.opencastproject.distribution.aws.s3 will go into ERROR state

'''
2022-08-25T08:27:49,341 | WARN  | (AwsS3DistributionServiceImpl:573) - Error distributing element security-policy-series of media package 66f12c72-2d55-4d18-8017-06522f9f040d
java.lang.NullPointerException: null
        at org.opencastproject.distribution.aws.s3.AwsS3DistributionServiceImpl.distributeElement(AwsS3DistributionServiceImpl.java:507) [!/:?]
        at org.opencastproject.distribution.aws.s3.AwsS3DistributionServiceImpl.distributeElement(AwsS3DistributionServiceImpl.java:491) [!/:?]
        at org.opencastproject.distribution.aws.s3.AwsS3DistributionServiceImpl.distributeElements(AwsS3DistributionServiceImpl.java:451) [!/:?]
        at org.opencastproject.distribution.aws.s3.AwsS3DistributionServiceImpl.process(AwsS3DistributionServiceImpl.java:880) [!/:?]
        at org.opencastproject.job.api.AbstractJobProducer$JobRunner.call(AbstractJobProducer.java:313) [!/:?]
        at org.opencastproject.job.api.AbstractJobProducer$JobRunner.call(AbstractJobProducer.java:272) [!/:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
2022-08-25T08:27:49,378 | ERROR | (AbstractJobProducer$JobRunner:343) - Error handling operation 'Distribute':
org.opencastproject.serviceregistry.api.ServiceRegistryException: Error handling operation 'Distribute'
        at org.opencastproject.distribution.aws.s3.AwsS3DistributionServiceImpl.process(AwsS3DistributionServiceImpl.java:897) ~[?:?]
        at org.opencastproject.job.api.AbstractJobProducer$JobRunner.call(AbstractJobProducer.java:313) [!/:?]
        at org.opencastproject.job.api.AbstractJobProducer$JobRunner.call(AbstractJobProducer.java:272) [!/:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: org.opencastproject.distribution.api.DistributionException: java.lang.NullPointerException
        at org.opencastproject.distribution.aws.s3.AwsS3DistributionServiceImpl.distributeElement(AwsS3DistributionServiceImpl.java:577) ~[?:?]
        at org.opencastproject.distribution.aws.s3.AwsS3DistributionServiceImpl.distributeElement(AwsS3DistributionServiceImpl.java:491) ~[?:?]
        at org.opencastproject.distribution.aws.s3.AwsS3DistributionServiceImpl.distributeElements(AwsS3DistributionServiceImpl.java:451) ~[?:?]
        at org.opencastproject.distribution.aws.s3.AwsS3DistributionServiceImpl.process(AwsS3DistributionServiceImpl.java:880) ~[?:?]
        ... 6 more
Caused by: java.lang.NullPointerException
        at org.opencastproject.distribution.aws.s3.AwsS3DistributionServiceImpl.distributeElement(AwsS3DistributionServiceImpl.java:507) ~[?:?]
        at org.opencastproject.distribution.aws.s3.AwsS3DistributionServiceImpl.distributeElement(AwsS3DistributionServiceImpl.java:491) ~[?:?]
        at org.opencastproject.distribution.aws.s3.AwsS3DistributionServiceImpl.distributeElements(AwsS3DistributionServiceImpl.java:451) ~[?:?]
:

'''

**To Reproduce**
1. Go to a 'series'
2. Click on 'Access-policy'
3. Add a new Ploicy with read an write permissions
4. Click on 'Update Event Permissions'

**Environment Information**
 - Opencast version with minor release [12.0, 12.x]
 - Opencast Develop ist working

**Comment by CGreweling** [comment]
We do not use aws S3 at all

**Comment by mliradelc** [comment]
Solved by #4111, if this still happens, please open this issue again.

**Comment by CGreweling** [comment]
@gregorydlogan as #4111 reverts a patch to solve a problem with aws.s3.
Would be nice, if you could test, if this patch brings a problem with aws.s3 back.

**Comment by gregorydlogan** [comment]
This doesn't seem to happen in my testing, granted that's with a modified AWS component that's adding glacier.
