### ISSUE TITLE
WorkflowOperationException: java.io.IOException: Unable to delete directory in STT-WOH

### ISSUE THREAD

**Issue by Rillke** [opencast/opencast#4265]
**Describe the bug**
When processing a media package with the SpeechToTextWorkflowOperationHandler, I receive an exception that a workspace directory can't be deleted:

```
job-operation

START_OPERATION

job-type

org.opencastproject.workflow

stack-trace

org.opencastproject.workflow.api.WorkflowOperationException: java.io.IOException: Unable to delete directory /data/opencast/workspace/mediapackage/fb481b01-cae6-40a6-8502-87541d18470e.
	at org.opencastproject.workflow.handler.speechtotext.SpeechToTextWorkflowOperationHandler.createSubtitle(SpeechToTextWorkflowOperationHandler.java:237)
	at org.opencastproject.workflow.handler.speechtotext.SpeechToTextWorkflowOperationHandler.start(SpeechToTextWorkflowOperationHandler.java:146)
	at org.opencastproject.workflow.impl.WorkflowOperationWorker.start(WorkflowOperationWorker.java:212)
	at org.opencastproject.workflow.impl.WorkflowOperationWorker.execute(WorkflowOperationWorker.java:117)
	at org.opencastproject.workflow.impl.WorkflowServiceImpl.runWorkflowOperation(WorkflowServiceImpl.java:718)
	at org.opencastproject.workflow.impl.WorkflowServiceImpl.process(WorkflowServiceImpl.java:1735)
	at org.opencastproject.workflow.impl.WorkflowServiceImpl$JobRunner.call(WorkflowServiceImpl.java:2096)
	at org.opencastproject.workflow.impl.WorkflowServiceImpl$JobRunner.call(WorkflowServiceImpl.java:2062)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: Unable to delete directory /data/opencast/workspace/mediapackage/fb481b01-cae6-40a6-8502-87541d18470e.
	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1212)
	at org.opencastproject.workspace.impl.WorkspaceImpl.cleanup(WorkspaceImpl.java:969)
	at org.opencastproject.workspace.impl.WorkspaceImpl.cleanup(WorkspaceImpl.java:955)
	at org.opencastproject.workflow.handler.speechtotext.SpeechToTextWorkflowOperationHandler.createSubtitle(SpeechToTextWorkflowOperationHandler.java:235)
```

**To Reproduce**
1. Have Opencast 12.3
2. Install a WF Operation that looks like this in your WF:
```xml
        <operation
                id="speechtotext"
                exception-handler-workflow="partial-error"
                description="Generates subtitles for video and audio files">
            <configurations>
                <configuration key="source-flavor">*/stt</configuration>
                <configuration key="target-flavor">captions/vtt+de</configuration>
                <configuration key="target-element">attachment</configuration>
                <configuration key="target-tags">stt,vosk,lang:de</configuration>
                <configuration key="language-code">ger</configuration>
                <configuration key="punctuation">true</configuration>
            </configurations>
        </operation>
```
4. Process an event using that Workflow
5. See error
<img width="980" alt="Screenshot 2022-10-01 at 17 51 16" src="https://user-images.githubusercontent.com/2311611/193417501-39a6150e-9faf-40b9-80e8-b26ea4df53e5.png">
<img width="967" alt="Screenshot 2022-10-01 at 17 52 34" src="https://user-images.githubusercontent.com/2311611/193417546-2273d6c3-df96-4bee-9948-65113146d3fb.png">

The workspace directory lives in NFS and after the workflow errored, only (empty) directories left:

```
root@d40e467e03ec:/data/opencast/workspace/mediapackage# tree fb481b01-cae6-40a6-8502-87541d18470e
fb481b01-cae6-40a6-8502-87541d18470e
├── 13f965eb-abfc-47d3-b6eb-7869f0242e78
├── 1cb243ce-53e6-4d8f-8d0e-0ffd1b5417f9
├── 1e580af9-7983-46d2-8646-11826e19d9ea
├── 23a8368f-32ed-4bb7-94f2-3e4242aea197
├── 24bf9c99-9f6d-454d-9a81-4cddcb777b56
├── 67bfd02d-48c0-4156-9d08-23e718748aca
├── 77e14701-fc1f-4f92-80ca-c3eab4159fce
├── 781059c6-6bf3-4053-b25d-f7253850920d
├── 8d304931-a81f-4023-a55e-b24d75e045ac
├── 9469129e-abc0-4f73-a8bb-f516d96309e5
├── 94bf046b-4ed6-4bbd-adfb-a7115d96d4b1
├── 9a2354d7-40b2-47bc-ae69-c7a5bc4818cb
├── 9bfa06e9-5e29-4d95-987b-5ff2ef20e712
├── a1c55f5b-54ad-4ffa-8dcb-8726768aebb4
├── a5032679-8e91-492c-851a-5c30e3c82d4f
├── a7236791-3103-4a45-8da5-43063ba52679
├── ae4b9254-8409-4442-b52c-39d8950e7391
├── b513fe84-3d64-484d-82b7-ad72b0f23072
├── b95ab1f0-3cd9-4385-8a63-44f2e56dd1c6
├── bc048a31-4957-45f9-94d1-0bc241f14547
├── c1903aec-d0fe-4a1c-84d9-be86abc866c9
├── c843220b-0336-4ddd-86ab-d2f85998f129
├── d685606c-2814-4239-838d-cdab69ed336d
├── f45e2827-da09-43c5-a5b8-226029989672
├── f704748a-0c5d-40e3-8842-622fd742b47e
├── f869cce5-5792-4a97-a210-f3d0813ce406
└── security-policy-series

27 directories, 0 files
```

**Environment Information**
 - OS: debian bullseye (inside docker)
 - Opencast version with minor release 12.3 with only some modifications in the players shipped with it.

**Comment by Rillke** [comment]
Also found this one on our admin node.

```
org.apache.commons.io.IOExceptionList: 1 exceptions: [java.io.IOException: Unable to delete file: /data/opencast/workspace/mediapackage/582cc9df-8fe1-4117-ad06-9baa86778d9d/aecf1e2b-7e0e-429
     at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:345) ~[!/:2.8.0]
     at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1206) ~[!/:2.8.0]
     at org.opencastproject.workspace.impl.WorkspaceImpl.cleanup(WorkspaceImpl.java:969) ~[?:?]
     at org.opencastproject.workspace.impl.WorkspaceImpl.cleanup(WorkspaceImpl.java:955) ~[?:?]
     at org.opencastproject.workflow.handler.speechtotext.SpeechToTextWorkflowOperationHandler.createSubtitle(SpeechToTextWorkflowOperationHandler.java:235) [!/:?]
     at org.opencastproject.workflow.handler.speechtotext.SpeechToTextWorkflowOperationHandler.start(SpeechToTextWorkflowOperationHandler.java:146) [!/:?]
     at org.opencastproject.workflow.impl.WorkflowOperationWorker.start(WorkflowOperationWorker.java:212) [!/:?]
     at org.opencastproject.workflow.impl.WorkflowOperationWorker.execute(WorkflowOperationWorker.java:117) [!/:?]
     at org.opencastproject.workflow.impl.WorkflowServiceImpl.runWorkflowOperation(WorkflowServiceImpl.java:718) [!/:?]
     at org.opencastproject.workflow.impl.WorkflowServiceImpl.process(WorkflowServiceImpl.java:1735) [!/:?]
     at org.opencastproject.workflow.impl.WorkflowServiceImpl$JobRunner.call(WorkflowServiceImpl.java:2096) [!/:?]
     at org.opencastproject.workflow.impl.WorkflowServiceImpl$JobRunner.call(WorkflowServiceImpl.java:2062) [!/:?]
     at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
     at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.io.IOException: Unable to delete file: /data/opencast/workspace/mediapackage/582cc9df-8fe1-4117-ad06-9baa86778d9d/aecf1e2b-7e0e-429b-a334-4d2b04eb1320
     at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:1425) ~[!/:2.8.0]
     at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:338) ~[!/:2.8.0]
     ... 15 more
Caused by: java.nio.file.FileSystemException: /data/opencast/workspace/mediapackage/582cc9df-8fe1-4117-ad06-9baa86778d9d/aecf1e2b-7e0e-429b-a334-4d2b04eb1320/.nfs00000000080b236e000009e6: Device or resource busy
     at sun.nio.fs.UnixException.translateToIOException(UnixException.java:100) ~[?:?]
     at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
     at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[?:?]
     at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:249) ~[?:?]
     at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:110) ~[?:?]
     at java.nio.file.Files.deleteIfExists(Files.java:1181) ~[?:?]
     at org.apache.commons.io.file.DeletingPathVisitor.visitFile(DeletingPathVisitor.java:142) ~[!/:2.8.0]
     at org.apache.commons.io.file.DeletingPathVisitor.visitFile(DeletingPathVisitor.java:36) ~[!/:2.8.0]
     at java.nio.file.Files.walkFileTree(Files.java:2725) ~[?:?]
     at java.nio.file.Files.walkFileTree(Files.java:2797) ~[?:?]
     at org.apache.commons.io.file.PathUtils.visitFileTree(PathUtils.java:687) ~[!/:2.8.0]
     at org.apache.commons.io.file.PathUtils.deleteDirectory(PathUtils.java:328) ~[!/:2.8.0]
     at org.apache.commons.io.file.PathUtils.delete(PathUtils.java:303) ~[!/:2.8.0]
     at org.apache.commons.io.file.PathUtils.delete(PathUtils.java:280) ~[!/:2.8.0]
     at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:1423) ~[!/:2.8.0]
     at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:338) ~[!/:2.8.0]
     ... 15 mo
```

https://serverfault.com/q/201294/326675

**Comment by Rillke** [comment]
This is apparently not easily reproducible. If your institution is also suffering from this issue, please help setting up a test case so it can be reproduced by developers. We are currently (2023-01) happy to fund a code fix and code review trough our current support partner elan e.V.

**Comment by gregorydlogan** [comment]
For clarity, this is leaving behind orphaned *directories* only, right?  How often is this occurring?

I wonder if a simple
```
try {
  FileUtils.deleteDirectory(mediaPackageDir);
} catch (IOException e) {
  FileUtils.deleteQuietly(mediaPackageDir);
}
```

would be enough to resolve this?

**Comment by mliradelc** [comment]
@Rillke Is this still an issue?
