### ISSUE TITLE
SSLHandshakeException "unable to find valid certification path to requested target"

### ISSUE THREAD

**Issue by MiniMinerLPs** [opencast/opencast#4673]
Hi,

**Describe the bug**

I installed opencast on a fresh Debian 11 system but uloaded media won't go past the "Pending"/"Queued" state because the workflow won't start. In the opencast log, I found the following error:

**Stack trace**

```
2023-02-08T18:59:14,903 | WARN  | (JobDispatcher$JobDispatcherRunner:555) - Unable to dispatch Job {id:1554, operation:START_WORKFLOW, status:QUEUED}
org.opencastproject.security.api.TrustedHttpClientException: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at org.opencastproject.kernel.security.TrustedHttpClientImpl.getRealmAndNonce(TrustedHttpClientImpl.java:614) ~[?:?]
	at org.opencastproject.kernel.security.TrustedHttpClientImpl.manuallyHandleDigestAuthentication(TrustedHttpClientImpl.java:538) ~[?:?]
	at org.opencastproject.kernel.security.TrustedHttpClientImpl.execute(TrustedHttpClientImpl.java:398) ~[?:?]
	at org.opencastproject.kernel.security.TrustedHttpClientImpl.execute(TrustedHttpClientImpl.java:348) ~[?:?]
	at org.opencastproject.serviceregistry.impl.JobDispatcher$JobDispatcherRunner.dispatchJob(JobDispatcher.java:532) [!/:?]
	at org.opencastproject.serviceregistry.impl.JobDispatcher$JobDispatcherRunner.dispatchDispatchableJobs(JobDispatcher.java:423) [!/:?]
	at org.opencastproject.serviceregistry.impl.JobDispatcher$JobDispatcherRunner.run(JobDispatcher.java:324) [!/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alert.createSSLException(Alert.java:131) ~[?:?]
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:353) ~[?:?]
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:296) ~[?:?]
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:291) ~[?:?]
	at sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1357) ~[?:?]
	at sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1232) ~[?:?]
	at sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1175) ~[?:?]
	at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392) ~[?:?]
	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443) ~[?:?]
	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:421) ~[?:?]
	at sun.security.ssl.TransportContext.dispatch(TransportContext.java:183) ~[?:?]
	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:172) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1507) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1417) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:456) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:427) ~[?:?]
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436) ~[?:?]
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384) ~[?:?]
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142) ~[?:?]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376) ~[?:?]
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393) ~[?:?]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[?:?]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[?:?]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[?:?]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[?:?]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[?:?]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[?:?]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108) ~[?:?]
	at org.opencastproject.kernel.security.TrustedHttpClientImpl.getRealmAndNonce(TrustedHttpClientImpl.java:593) ~[?:?]
	... 12 more
```

**Server environment**
Debian 11 VM
Opencast 13.1-1
Java 11
Nginx 1.18.0 (configuration in comment below)
MariaDB 10.5.18

I found no other users with this problem. Write me a message if you need more info!

**Comment by gregorydlogan** [comment]
That's because you really, *really*, don't want Opencast handling the SSL termination.  Put Apache, or nginx in front of Opencast to handle SSL, as described from https://docs.opencast.org/r/13.x/admin/#configuration/https/.

Technically what you're trying to do is doable, but unless you have a very good reason to let OC do the SSL, you're better off doing this with something else.

**Comment by MiniMinerLPs** [comment]
Hi Gregory,

thank you for your quick message. Sorry I completely forgot to mention that I use nginx as a reverse proxy. Here is my nginx conf (I replaced my domain with "opencast.mydomain.tld"):

```
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    ssl_certificate /etc/letsencrypt/live/opencast.mydomain.tld/cert.pem;
    ssl_certificate_key /etc/letsencrypt/live/opencast.mydomain.tld/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/opencast.mydomain.tld/fullchain.pem;
    ssl_session_timeout 1d;
    ssl_session_cache shared:MozSSL:10m;  # about 40000 sessions
    ssl_session_tickets off;
    ssl_dhparam /etc/nginx/dhparam.pem;
    ssl_stapling on;
    ssl_stapling_verify on;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-S>
    ssl_prefer_server_ciphers off;

    add_header Strict-Transport-Security "max-age=63072000" always;
    add_header Access-Control-Allow-Origin https://studio.opencast.org;
    add_header Access-Control-Allow-Methods 'GET, POST';
    add_header Access-Control-Allow-Credentials true;
    add_header Access-Control-Allow-Headers 'Origin,Content-Type,Accept,Authorization';

if ($request_method = OPTIONS) {
    return 200;
}

    client_max_body_size 0;
        location / {

            proxy_set_header        Host $host;
            proxy_set_header        X-Real-IP $remote_addr;
            proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header        X-Forwarded-Proto $scheme;
            proxy_pass              http://127.0.0.1:8080;
            proxy_redirect          http://$host https://$host;
            proxy_buffering         off;
            proxy_request_buffering off;
        }

}
```

I also tried the exact configuration from the docs but the same error occurs.

More information:
- Nginx as reverse proxy
- MariaDB as database

**Comment by lkiesow** [comment]
Opencast complains that the worker does not provide a valid domain.

From the configuration you posted, it seems like you misconfigured Nginx:

```
ssl_certificate /etc/letsencrypt/live/opencast.mydomain.tld/cert.pem;
ssl_certificate_key /etc/letsencrypt/live/opencast.mydomain.tld/privkey.pem;
ssl_trusted_certificate /etc/letsencrypt/live/opencast.mydomain.tld/fullchain.pem;
```

should probably be:

```
ssl_certificate_key /etc/letsencrypt/live/opencast.mydomain.tld/privkey.pem;
ssl_certificate /etc/letsencrypt/live/opencast.mydomain.tld/fullchain.pem;
```

You can easily test this with cURL. Testing this with browsers can be a bit tricky since they often cache intermediate certificates. But this will give you an error if your certificate chain is not set up correctly:

```
curl -i https://opencast.mydomain.tld
```

**Comment by MiniMinerLPs** [comment]
Hi Lars,

that fixed the issue! Thank you very much Lars and Gregory!
