### ISSUE TITLE
Latest Paella 7 version (1.20) is broken in Opencast 

### ISSUE THREAD

**Issue by mliradelc** [opencast/opencast#4708]
**Describe the bug**

I was making routine updates to Paella 7 dependencies, The PR #4705 broke paella 7 with `player is not defined` error.

The error log in debug mode is:
```
Log.js:60 paella-core - Debug: New paella player instance
Log.js:60 paella-core - Debug: Loading paella player
Log.js:60 paella-core - Debug: Using default configuration loading function.
:8080/usertracking/stats.json?id=d8516a01-c75a-46d2-8e8d-5b7e8d0dc77e:1          Failed to load resource: the server responded with a status of 404 (Not Found)
:8080/usertracking/detailenabled:1          Failed to load resource: the server responded with a status of 404 (Not Found)

Log.js:57 paella-core - Info: Paella player load done

VideoContainer.js:317 Uncaught (in promise) ReferenceError: player is not defined
    at E.<anonymous> (VideoContainer.js:317:30)
    at l (VideoContainer.js:2:1)
    at Generator.<anonymous> (VideoContainer.js:2:1)
    at Generator.next (VideoContainer.js:2:1)
    at Ot (VideoContainer.js:2:1)
    at a (VideoContainer.js:2:1)
    at VideoContainer.js:2:1
    at new Promise (<anonymous>)
    at E.<anonymous> (VideoContainer.js:2:1)
    at E.<anonymous> (VideoContainer.js:400:6)

VideoContainer.js:437 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'indexOf')
    at E.<anonymous> (VideoContainer.js:437:39)
    at l (VideoContainer.js:2:1)
    at Generator.<anonymous> (VideoContainer.js:2:1)
    at Generator.next (VideoContainer.js:2:1)
    at Ot (VideoContainer.js:2:1)
    at a (VideoContainer.js:2:1)
    at VideoContainer.js:2:1
    at new Promise (<anonymous>)
    at E.<anonymous> (VideoContainer.js:2:1)
    at E.<anonymous> (VideoContainer.js:453:6)
```

**To Reproduce**

1. Apply 1.20
2. build as default
3. Play an event with paella 7

**Expected behaviour**

Paella player 7 running as normal

**Workaround**

Working on reverting #4705 

Reverting this PR solves the issue

**User environment:**

- Opencast 13
- Chrome latest version as browser

**Comment by mliradelc** [comment]
@miesgre @ferserc1

**Comment by miesgre** [comment]
There is a bug in paella-core 1.20.
It is fixed in commit https://github.com/polimediaupv/paella-core/commit/72bc3b05dcc34c83aa5e47f6a0e1d265f3d1c1b9 (paella-core 1.20.1).

Once [dependabot](https://github.com/apps/dependabot) update paella-core to 1.20.1 it will be fixed in opencast.

**Comment by mliradelc** [comment]
Thanks @miesgre! I will merge as soon dependabot shows it.
