### ISSUE TITLE
Exception in waveform processing

### ISSUE THREAD

**Issue by hercherf** [opencast/opencast#4865]
**Describe the bug**

While testing Opencast 13.4 with a demo video from https://www.demolandia.net/4k-video-test/dolby-vision/page-1.html (https://www.demolandia.net/downloads.html?id=86575423) the encoding fails in the waveform extraction job with the  exception below. Firing up ffmpeg with the parameters taken from the Exception seems to work fine.

**To Reproduce**

Use 'docker-compose -f docker-compose.allinone.mariadb.yml up' from https://github.com/opencast/opencast-docker.git:13.4, download https://www.demolandia.net/downloads.html?id=86575423 and use the "process upon upload and schedule" workflow with "straight to publish"

**Expected behavior**

Video should be processed without errors.

**Stack trace**

```
docker-compose-opencast-1    | 2023-04-17T06:33:54,788 | ERROR | (AbstractJobProducer$JobRunner:343) - Error handling operation 'Waveform':
docker-compose-opencast-1    | org.opencastproject.serviceregistry.api.ServiceRegistryException: Error handling operation 'Waveform'
docker-compose-opencast-1    |  at org.opencastproject.waveform.ffmpeg.WaveformServiceImpl.process(WaveformServiceImpl.java:291) ~[?:?]
docker-compose-opencast-1    |  at org.opencastproject.job.api.AbstractJobProducer$JobRunner.call(AbstractJobProducer.java:313) [!/:?]
docker-compose-opencast-1    |  at org.opencastproject.job.api.AbstractJobProducer$JobRunner.call(AbstractJobProducer.java:272) [!/:?]
docker-compose-opencast-1    |  at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
docker-compose-opencast-1    |  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
docker-compose-opencast-1    |  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
docker-compose-opencast-1    |  at java.lang.Thread.run(Thread.java:829) [?:?]
docker-compose-opencast-1    | Caused by: org.opencastproject.waveform.api.WaveformServiceException: The encoder process exited abnormally with exit code 1 using command
docker-compose-opencast-1    | ffmpeg -nostats -nostdin -hide_banner -i /data/opencast/workspace/mediapackage/8874b099-71c4-427c-93ae-e533cf1e2075/5efb5149-3a33-4bc1-b2eb-ce15fd8a7d4c/dolby-vision-art-_www.demolandia.net_.mp4 -lavfi showwavespic=split_channels=0:s=5000x500:scale=lin:colors=black -frames:v 1 -an -vn -sn /data/opencast/workspace/mediapackage/8874b099-71c4-427c-93ae-e533cf1e2075/5efb5149-3a33-4bc1-b2eb-ce15fd8a7d4c/dolby-vision-art-_www.demolandia.net_-5efb5149-3a33-4bc1-b2eb-ce15fd8a7d4c-waveform.png
docker-compose-opencast-1    |  at org.opencastproject.waveform.ffmpeg.WaveformServiceImpl.extractWaveform(WaveformServiceImpl.java:378) ~[?:?]
docker-compose-opencast-1    |  at org.opencastproject.waveform.ffmpeg.WaveformServiceImpl.process(WaveformServiceImpl.java:283) ~[?:?]
docker-compose-opencast-1    |  ... 6 more
docker-compose-opencast-1    | 2023-04-17T06:33:57,715 | ERROR | (WorkflowOperationWorker:140) - Workflow operation 'operation:'waveform, state:'FAILED'' failed
docker-compose-opencast-1    | org.opencastproject.workflow.api.WorkflowOperationException: Waveform extraction jobs for media package '8874b099-71c4-427c-93ae-e533cf1e2075' have not completed successfully
```

**Server environment:**
 - OS: Arch Linux
 - Distribution: allinone
 - Installation method: docker-compose.allinone.mariadb.yml from https://github.com/opencast/opencast-docker.git:13.4
 - Version 13.4

**Comment by gregorydlogan** [comment]
This looks like ffmpeg can't handle the input filetype.  In testing this locally my (up-to-date) ffmpeg can handle the file, and afaik the Docker images use the same binary.  Is this still happening with updated 13.x (even 13.4) container images?

**Comment by hercherf** [comment]
It's a bit weird - i was using OpenCast 13.4.
Entering the container and calling ffmpeg with the parameters shown in the exception works flawless - that left me bewildered and led to this Issue :)
