### ISSUE TITLE
Vosk Test fails - 'Unable to map language to model'

### ISSUE THREAD

**Issue by mliradelc** [opencast/opencast#4926]
When #4869 was being reviewed, it was found this error:

```
ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.316 s <<< FAILURE! - in org.opencastproject.speechtotext.impl.SpeechToTextServiceImplTest
[ERROR] testVoskSpeechToText(org.opencastproject.speechtotext.impl.SpeechToTextServiceImplTest)  Time elapsed: 1.145 s  <<< ERROR!
java.lang.reflect.UndeclaredThrowableException
        at org.opencastproject.speechtotext.impl.SpeechToTextServiceImplTest.testVoskSpeechToText(SpeechToTextServiceImplTest.java:152)
Caused by: org.opencastproject.speechtotext.api.SpeechToTextServiceException: Error while generating subtitle from file:/Users/maxlira/repos/mldc-opencast/modules/speech-to-text-impl/target/test-classes/speech_to_text_test.mp4
        at org.opencastproject.speechtotext.impl.SpeechToTextServiceImplTest.lambda$setUp$2(SpeechToTextServiceImplTest.java:140)
        at org.opencastproject.speechtotext.impl.SpeechToTextServiceImplTest.testVoskSpeechToText(SpeechToTextServiceImplTest.java:152)
Caused by: org.opencastproject.speechtotext.api.SpeechToTextEngineException:
org.opencastproject.speechtotext.api.SpeechToTextEngineException: Vosk exited abnormally with status 1 (command: [vosk-cli, -i, /Users/maxlira/repos/mldc-opencast/modules/speech-to-text-impl/target/test-classes/speech_to_text_test.mp4, -o, /Users/maxlira/repos/mldc-opencast/modules/speech-to-text-impl/target/junit16714273990897239948/junit3351326031937111432/collection/subtitles/tmp_0_speech_to_text_test.vtt, -l, eng])
 Output:
Traceback (most recent call last):
  File "/usr/local/bin/vosk-cli", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/voskcli/transcribe.py", line 392, in main
    model = [match_language_to_model(lang) for lang in args.language]
  File "/usr/local/lib/python3.10/site-packages/voskcli/transcribe.py", line 392, in <listcomp>
    model = [match_language_to_model(lang) for lang in args.language]
  File "/usr/local/lib/python3.10/site-packages/voskcli/transcribe.py", line 343, in match_language_to_model
    raise ValueError('Unable to map language to model')
ValueError: Unable to map language to model

        at org.opencastproject.speechtotext.impl.SpeechToTextServiceImplTest.lambda$setUp$2(SpeechToTextServiceImplTest.java:140)
        at org.opencastproject.speechtotext.impl.SpeechToTextServiceImplTest.testVoskSpeechToText(SpeechToTextServiceImplTest.java:152)
Caused by: org.opencastproject.speechtotext.api.SpeechToTextEngineException:
Vosk exited abnormally with status 1 (command: [vosk-cli, -i, /Users/maxlira/repos/mldc-opencast/modules/speech-to-text-impl/target/test-classes/speech_to_text_test.mp4, -o, /Users/maxlira/repos/mldc-opencast/modules/speech-to-text-impl/target/junit16714273990897239948/junit3351326031937111432/collection/subtitles/tmp_0_speech_to_text_test.vtt, -l, eng])
 Output:
Traceback (most recent call last):
  File "/usr/local/bin/vosk-cli", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/voskcli/transcribe.py", line 392, in main
    model = [match_language_to_model(lang) for lang in args.language]
  File "/usr/local/lib/python3.10/site-packages/voskcli/transcribe.py", line 392, in <listcomp>
    model = [match_language_to_model(lang) for lang in args.language]
  File "/usr/local/lib/python3.10/site-packages/voskcli/transcribe.py", line 343, in match_language_to_model
    raise ValueError('Unable to map language to model')
ValueError: Unable to map language to model

        at org.opencastproject.speechtotext.impl.SpeechToTextServiceImplTest.lambda$setUp$2(SpeechToTextServiceImplTest.java:140)
        at org.opencastproject.speechtotext.impl.SpeechToTextServiceImplTest.testVoskSpeechToText(SpeechToTextServiceImplTest.java:152)
```

After checking the code, the affected line is:
```
Job job = speechToTextService.transcribe(videoUri, "eng", false);
```
If `vosk-cli` run normally with the command that appears in the error log, Vosk completes the task successfully

**To Reproduce**

1. Install `vosk-cli`
2. Install a english language model (Add it to Opencast source root folder under `models`, create folder if necessary )
3. Start compilation. 

**Expected behavior**

Clear build

**Additional context**

**Comment by gregorydlogan** [comment]
This is actually why I filed https://github.com/elan-ev/vosk-cli/pull/30. I had to put my model in /usr, and name is `eng` rather than the default from the zip file before things would work.

**Comment by mliradelc** [comment]
> This is actually why I filed [elan-ev/vosk-cli#30](https://github.com/elan-ev/vosk-cli/pull/30). I had to put my model in /usr, and name is `eng` rather than the default from the zip file before things would work.

Thanks your PR, without it, I would be lost looking where to install it

**Comment by mliradelc** [comment]
Close as #4968 fixes this bug
