### ISSUE TITLE
Processing fails if less than ~3 seconds of video remaining after editing

### ISSUE THREAD

**Issue by jduehring** [opencast/opencast#5174]
If there are less than about 3-4 seconds of the initial video remaining after editing, then the editor operation fails during processing.

**To Reproduce**

1. Edit video, so that there are only a few seconds remaining.
![image](https://github.com/opencast/opencast/assets/32971521/2ba004ba-6468-4f90-8447-36e1a49f79cc)
3. Click on Finish -> Start Processing
4. See error during processing
![image](https://github.com/opencast/opencast/assets/32971521/6f88af38-be4e-41d7-bc4a-9557747df5db)

**Expected behavior**

Either it should not be possible to cut the video that short or even better the processing should work correctly! 

**Stack trace**
```
org.opencastproject.videoeditor.api.ProcessFailedException: Unable to process SMIL: null
	at org.opencastproject.videoeditor.impl.VideoEditorServiceImpl.processSmil(VideoEditorServiceImpl.java:418)
	at org.opencastproject.videoeditor.impl.VideoEditorServiceImpl.process(VideoEditorServiceImpl.java:514)
	at org.opencastproject.job.api.AbstractJobProducer$JobRunner.call(AbstractJobProducer.java:313)
	at org.opencastproject.job.api.AbstractJobProducer$JobRunner.call(AbstractJobProducer.java:272)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.util.NoSuchElementException
	at java.base/java.util.LinkedList.removeFirst(LinkedList.java:274)
	at java.base/java.util.LinkedList.pop(LinkedList.java:805)
	at org.opencastproject.videoeditor.impl.VideoEditorServiceImpl.sortSegments(VideoEditorServiceImpl.java:457)
	at org.opencastproject.videoeditor.impl.VideoEditorServiceImpl.processSmil(VideoEditorServiceImpl.java:315)
	... 7 more
```

**Server environment:**
Tested on a distributed system as well as on develop.opencast.org

**Comment by gregorydlogan** [comment]
Covered up by #1717.  I guess technically you could still submit smil manually that Opencast wouldn't handle properly, but from our frontends this now should not happen.  Is that enough to close this out?

**Comment by Arnei** [comment]
@jduehring

**Comment by jduehring** [comment]
Works for me, thanks for the patch!
