### ISSUE TITLE
NullPointerException when activating WorkflowCleaner

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast#5188]
Appears in 12.x. Need to verify that the problem persists in 14.x:

```
2023-08-28T17:12:08,448 | INFO  | (ServiceRegistryJpaImpl:651) - Jobs with IDs '[14520]' deleted
2023-08-28T17:12:08,458 | WARN  | (WorkflowServiceImpl:2232) - [>0439e6c4] No events for workflow instance 14520 found in the Elasticsearch index.
2023-08-28T17:12:08,477 | ERROR | (WorkflowCleanupScanner:195) - Unable to cleanup failed jobs:
org.opencastproject.workflow.api.WorkflowDatabaseException: org.opencastproject.workflow.api.WorkflowDatabaseException: Could not delete workflow with ID '14520'
        at org.opencastproject.workflow.impl.WorkflowServiceImpl.cleanupWorkflowInstances(WorkflowServiceImpl.java:2133) ~[!/:?]
        at org.opencastproject.workflow.impl.WorkflowCleanupScanner.scan(WorkflowCleanupScanner.java:193) [!/:?]
        at org.opencastproject.security.util.SecurityContext.lambda$runInContext$0(SecurityContext.java:68) [!/:?]
        at org.opencastproject.security.util.SecurityContext.runInContext(SecurityContext.java:58) [!/:?]
        at org.opencastproject.security.util.SecurityContext.runInContext(SecurityContext.java:67) [!/:?]
        at org.opencastproject.workflow.impl.WorkflowCleanupScanner$Runner.execute(WorkflowCleanupScanner.java:253) [!/:?]
        at org.opencastproject.workflow.impl.WorkflowCleanupScanner$Runner.execute(WorkflowCleanupScanner.java:239) [!/:?]
        at org.opencastproject.kernel.scanner.AbstractScanner$TypedQuartzJob$1.xapply(AbstractScanner.java:311) [!/:?]
        at org.opencastproject.kernel.scanner.AbstractScanner$TypedQuartzJob$1.xapply(AbstractScanner.java:307) [!/:?]
        at org.opencastproject.util.data.Function0$X.apply(Function0.java:53) [!/:?]
        at org.opencastproject.util.NeedleEye.apply(NeedleEye.java:46) [!/:?]
        at org.opencastproject.kernel.scanner.AbstractScanner$TypedQuartzJob.execute(AbstractScanner.java:297) [!/:?]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:216) [!/:?]
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:549) [!/:?]
Caused by: org.opencastproject.workflow.api.WorkflowDatabaseException: Could not delete workflow with ID '14520'
        at org.opencastproject.workflow.api.WorkflowServiceDatabaseImpl.removeFromDatabase(WorkflowServiceDatabaseImpl.java:389) ~[!/:?]
        at org.opencastproject.workflow.impl.WorkflowServiceImpl.remove(WorkflowServiceImpl.java:966) ~[!/:?]
        at org.opencastproject.workflow.impl.WorkflowServiceImpl.remove(WorkflowServiceImpl.java:909) ~[!/:?]
        at org.opencastproject.workflow.impl.WorkflowServiceImpl.cleanupWorkflowInstances(WorkflowServiceImpl.java:2120) ~[!/:?]
        ... 13 more
Caused by: java.lang.NullPointerException
        at java.util.Hashtable.put(Hashtable.java:475) ~[?:?]
        at org.eclipse.persistence.indirection.IndirectMap.put(IndirectMap.java:697) ~[!/:?]
        at org.eclipse.persistence.internal.queries.MapContainerPolicy.addInto(MapContainerPolicy.java:134) ~[!/:?]
        at org.eclipse.persistence.internal.queries.MappedKeyMapContainerPolicy.addInto(MappedKeyMapContainerPolicy.java:198) ~[!/:?]
        at org.eclipse.persistence.queries.DataReadQuery.executeNonCursor(DataReadQuery.java:228) ~[!/:?]
        at org.eclipse.persistence.queries.DataReadQuery.executeDatabaseQuery(DataReadQuery.java:154) ~[!/:?]
        at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:911) ~[!/:?]
        at org.eclipse.persistence.queries.DataReadQuery.execute(DataReadQuery.java:139) ~[!/:?]
        at org.eclipse.persistence.queries.DatabaseQuery.executeInUnitOfWork(DatabaseQuery.java:810) ~[!/:?]
        at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:2983) ~[!/:?]
        at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1898) ~[!/:?]
        at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1880) ~[!/:?]
        at org.eclipse.persistence.internal.indirection.QueryBasedValueHolder.instantiate(QueryBasedValueHolder.java:135) ~[!/:?]
        at org.eclipse.persistence.internal.indirection.QueryBasedValueHolder.instantiate(QueryBasedValueHolder.java:122) ~[!/:?]
        at org.eclipse.persistence.internal.indirection.DatabaseValueHolder.getValue(DatabaseValueHolder.java:97) ~[!/:?]
        at org.eclipse.persistence.internal.indirection.UnitOfWorkValueHolder.instantiateImpl(UnitOfWorkValueHolder.java:175) ~[!/:?]
        at org.eclipse.persistence.internal.indirection.UnitOfWorkValueHolder.instantiate(UnitOfWorkValueHolder.java:238) ~[!/:?]
        at org.eclipse.persistence.internal.indirection.DatabaseValueHolder.getValue(DatabaseValueHolder.java:97) ~[!/:?]
        at org.eclipse.persistence.indirection.IndirectMap.buildDelegate(IndirectMap.java:129) ~[!/:?]
        at org.eclipse.persistence.indirection.IndirectMap.getDelegate(IndirectMap.java:416) ~[!/:?]
        at org.eclipse.persistence.indirection.IndirectMap$1.<init>(IndirectMap.java:226) ~[!/:?]
        at org.eclipse.persistence.indirection.IndirectMap.entrySet(IndirectMap.java:225) ~[!/:?]
        at org.eclipse.persistence.internal.queries.MapContainerPolicy$MapContainerPolicyIterator.<init>(MapContainerPolicy.java:877) ~[!/:?]
        at org.eclipse.persistence.internal.queries.MapContainerPolicy.iteratorFor(MapContainerPolicy.java:548) ~[!/:?]
        at org.eclipse.persistence.mappings.DirectMapMapping.cascadePerformRemoveIfRequired(DirectMapMapping.java:236) ~[!/:?]
        at org.eclipse.persistence.internal.descriptors.ObjectBuilder.cascadePerformRemove(ObjectBuilder.java:2450) ~[!/:?]
        at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.performRemove(UnitOfWorkImpl.java:3690) ~[!/:?]
        at org.eclipse.persistence.mappings.CollectionMapping.cascadePerformRemoveIfRequired(CollectionMapping.java:423) ~[!/:?]
        at org.eclipse.persistence.internal.descriptors.ObjectBuilder.cascadePerformRemove(ObjectBuilder.java:2450) ~[!/:?]
        at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.performRemove(UnitOfWorkImpl.java:3690) ~[!/:?]
        at org.eclipse.persistence.internal.jpa.EntityManagerImpl.remove(EntityManagerImpl.java:670) ~[!/:?]
        at org.opencastproject.workflow.api.WorkflowServiceDatabaseImpl.removeFromDatabase(WorkflowServiceDatabaseImpl.java:381) ~[!/:?]
        at org.opencastproject.workflow.impl.WorkflowServiceImpl.remove(WorkflowServiceImpl.java:966) ~[!/:?]
        at org.opencastproject.workflow.impl.WorkflowServiceImpl.remove(WorkflowServiceImpl.java:909) ~[!/:?]
        at org.opencastproject.workflow.impl.WorkflowServiceImpl.cleanupWorkflowInstances(WorkflowServiceImpl.java:2120) ~[!/:?]
        ... 13 more
```

Fix is likely just:

```diff
diff --git a/modules/workflow-service-api/src/main/java/org/opencastproject/workflow/api/WorkflowServiceDatabaseImpl.java b/modules/workflow-service-api/src/main/java/org/opencastproject/workflow/api/WorkflowServiceDatabaseImpl.java
index 2bc636422d..251ecf9895 100644
--- a/modules/workflow-service-api/src/main/java/org/opencastproject/workflow/api/WorkflowServiceDatabaseImpl.java
+++ b/modules/workflow-service-api/src/main/java/org/opencastproject/workflow/api/WorkflowServiceDatabaseImpl.java
@@ -377,8 +377,7 @@ public class WorkflowServiceDatabaseImpl implements WorkflowServiceDatabase {
       if (fromDb == null) {
         // Already removed
       } else {
-        instance = em.merge(instance);
-        em.remove(instance);
+        em.remove(fromDb);
       }
       tx.commit();
       logger.debug("Workflow with id {} was deleted.", instance.getId());
```

**Comment by lkiesow** [comment]
This is already fixed in Opencast 14.
