### ISSUE TITLE
Don't index themes

### ISSUE THREAD

**Issue by KatrinIhler** [opencast/opencast#5264]
IMO, putting themes in the Elasticsearch index is total overkill, because nobody has that many themes to warrant the effort. (If you are the exception to this rule, speak up now!) Might as well just get them from the database like we do for groups, users, and ACL templates already.

(Might be useful to make a proposal for this first, though.)

**Comment by DZenker** [comment]
I agree with this. 
Also, after updating from 12.x to 14.x, I noticed that the Themes Index rebuild doesn't work properly, at least in our installation:

_2023-08-22T08:31:08,944 | INFO  | (IndexEndpoint:166) - Starting to repopulate the index
2023-08-22T08:31:09,750 | INFO  | (IndexRebuildService:134) - Elasticsearch Index cleared, starting complete rebuild.
2023-08-22T08:31:09,750 | INFO  | (IndexRebuildService:206) - Starting to rebuild the Elasticsearch index from service 'Themes'
2023-08-22T08:31:09,770 | INFO  | (AbstractIndexProducer:66) - Starting update of the Elasticsearch index from service 'Themes' with 2 themes of organization 'lunex'
2023-08-22T08:31:09,771 | ERROR | (AbstractIndexProducer:199) - Error updating the Elasticsearch index from service 'Themes'.
java.lang.IllegalStateException: User's organization must match search organization
        at org.opencastproject.elasticsearch.index.objects.theme.ThemeSearchQuery.<init>(ThemeSearchQuery.java:93) ~[?:?]
        at org.opencastproject.elasticsearch.index.ElasticsearchIndex.getTheme(ElasticsearchIndex.java:345) ~[?:?]
        at org.opencastproject.elasticsearch.index.ElasticsearchIndex.getTheme(ElasticsearchIndex.java:319) ~[?:?]
        at org.opencastproject.themes.persistence.ThemesServiceDatabaseImpl.repopulate(ThemesServiceDatabaseImpl.java:314) ~[?:?]
        at org.opencastproject.elasticsearch.index.rebuild.IndexRebuildService.rebuildIndex(IndexRebuildService.java:209) ~[?:?]
        at org.opencastproject.elasticsearch.index.rebuild.IndexRebuildService.rebuildIndex(IndexRebuildService.java:137) ~[?:?]
        at org.opencastproject.elasticsearch.index.endpoint.IndexEndpoint.lambda$rebuildIndex$3(IndexEndpoint.java:167) ~[?:?]
        at org.opencastproject.security.util.SecurityContext.lambda$runInContext$0(SecurityContext.java:68) ~[?:?]
        at org.opencastproject.security.util.SecurityContext.runInContext(SecurityContext.java:58) ~[?:?]
        at org.opencastproject.security.util.SecurityContext.runInContext(SecurityContext.java:67) ~[?:?]
        at org.opencastproject.elasticsearch.index.endpoint.IndexEndpoint.lambda$rebuildIndex$4(IndexEndpoint.java:164) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
2023-08-22T08:31:09,772 | INFO  | (IndexRebuildService:214) - Finished to rebuild the Elasticsearch index from service 'Themes'_

The rebuild tried to index the themes of the wrong organization ("lunex"), but they belong to another organization. Is this a known issue?

**Comment by KatrinIhler** [comment]
@DZenker Not afaik, better file an issue for that.
