### ISSUE TITLE
Unprivileged User can't publish to Engage

### ISSUE THREAD

**Issue by KatrinIhler** [opencast/opencast#5333]
An unprivileged user without the Admin role, but with all UI roles and the role for the Admin UI is not able to publish to Engage with either the fast or the schedule-and-upload workflow. This problem exists in both 14.x and 13.x and also in released versions as far back as at least 13.10. The following exception occurs while trying to create the Engage publication:

```
2023-10-10 17:07:11,955 | INFO  | (PublishEngageWorkflowOperationHandler:697) - The search service doesn't know mediapackage f1f6f753-fc2f-4849-91c8-b82c87d70bd4.
2023-10-10 17:07:16,977 | INFO  | (PublishEngageWorkflowOperationHandler:424) - Publishing media package f1f6f753-fc2f-4849-91c8-b82c87d70bd4 to search index
2023-10-10 17:07:16,977 | INFO  | (PublishEngageWorkflowOperationHandler:433) - Using 'server.url' as a fallback for the non-existing organization level key 'org.opencastproject.engage.ui.url' for the publication url
2023-10-10 17:07:18,012 | WARN  | (WorkspaceImpl:483) - Received unexpected response status 403 while trying to download from http://localhost:8080/static/mh_default_org/engage-player/f1f6f753-fc2f-4849-91c8-b82c87d70bd4/security-policy-episode/xacml.xml
2023-10-10 17:07:18,035 | WARN  | (WorkspaceImpl:483) - Received unexpected response status 403 while trying to download from http://localhost:8080/static/mh_default_org/engage-player/f1f6f753-fc2f-4849-91c8-b82c87d70bd4/08a03103-6920-4e38-9460-7d2aee5ddfc5/dublincore.xml
2023-10-10 17:07:18,039 | ERROR | (DublinCoreUtil:79) - Unable to load metadata from catalog 'http://localhost:8080/static/mh_default_org/engage-player/f1f6f753-fc2f-4849-91c8-b82c87d70bd4/08a03103-6920-4e38-9460-7d2aee5ddfc5/dublincore.xml'
org.opencastproject.util.NotFoundException: null
	at org.opencastproject.workspace.impl.WorkspaceImpl.downloadIfNecessary(WorkspaceImpl.java:534) ~[?:?]
	at org.opencastproject.workspace.impl.WorkspaceImpl$2.xapply(WorkspaceImpl.java:556) ~[?:?]
	at org.opencastproject.workspace.impl.WorkspaceImpl$2.xapply(WorkspaceImpl.java:553) ~[?:?]
	at org.opencastproject.util.data.Function$X.apply(Function.java:104) ~[!/:?]
	at org.opencastproject.util.IoSupport.locked(IoSupport.java:478) ~[!/:?]
	at org.opencastproject.workspace.impl.WorkspaceImpl.get(WorkspaceImpl.java:401) ~[?:?]
	at org.opencastproject.workspace.impl.WorkspaceImpl.read(WorkspaceImpl.java:436) ~[?:?]
	at org.opencastproject.metadata.dublincore.DublinCoreUtil.loadDublinCore(DublinCoreUtil.java:76) [!/:?]
	at org.opencastproject.metadata.dublincore.StaticMetadataServiceDublinCoreImpl.getMetadata(StaticMetadataServiceDublinCoreImpl.java:156) [!/:?]
	at org.opencastproject.metadata.dublincore.StaticMetadataServiceDublinCoreImpl.getMetadata(StaticMetadataServiceDublinCoreImpl.java:83) [!/:?]
	at org.opencastproject.search.impl.solr.SolrIndexManager.lambda$getMetadata$3(SolrIndexManager.java:1271) [!/:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) [?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) [?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) [?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) [?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) [?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) [?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) [?:?]
	at org.opencastproject.search.impl.solr.SolrIndexManager.getMetadata(SolrIndexManager.java:1273) [!/:?]
	at org.opencastproject.search.impl.solr.SolrIndexManager.createEpisodeInputDocument(SolrIndexManager.java:444) [!/:?]
	at org.opencastproject.search.impl.solr.SolrIndexManager.add(SolrIndexManager.java:317) [!/:?]
	at org.opencastproject.search.impl.SearchServiceImpl.addSynchronously(SearchServiceImpl.java:420) [!/:?]
	at org.opencastproject.search.impl.SearchServiceImpl.process(SearchServiceImpl.java:720) [!/:?]
	at org.opencastproject.job.api.AbstractJobProducer$JobRunner.call(AbstractJobProducer.java:313) [!/:?]
	at org.opencastproject.job.api.AbstractJobProducer$JobRunner.call(AbstractJobProducer.java:272) [!/:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

It looks like the permission check is trying to get the ACL from the search service, but that ACL is not yet available. I'm gonna investigate this further and report my findings.

**Comment by KatrinIhler** [comment]
Update: 
This problem exists in 12.x and 11.x as well and is connected to Static File Protection (which explains why it works on systems where that is turned off :sweat_smile:). In 10.x the exception also occurs, but is caught and does not cause the workflow to fail (this was changed by #2826).

The problem is that when creating the index entry in search for the media package, we're trying to request ACL and catalog files from /static/mh_default_org/engage-player... but the permission check fails because the index entry doesn't exist yet. The files themselves were already distributed and can be requested by an Admin without a problem. 

To be honest, I'm not sure how to fix this yet. How do you handle this case where the files exist but the index entry doesn't? Just allow access? Probably gonna bring this up at the next Technical Meeting...

**Comment by KatrinIhler** [comment]
The results of the discussion are that we probably need some form of privilege escalation when requesting files in this specific case, or we need to find a way to request these files from the workspace.

**Comment by lkiesow** [comment]
This works in 14.x and I think we upgraded from 12.x to 14.x at UOS. So it did work in 12.x at some point.

We have the correct ACLs. So we can definitely evaluate them. The question is just what the best way to access them is:
- Get them from the workspace, where we have them as part of the running workflow
- Get them from the database, where they might already be included
- Make sure ACLs re the first thing we put into the index so that further evaluation of ACLs work from there
