### ISSUE TITLE
Deleting a user who created a theme will prevent re-indexation of themes (and therefore series)

### ISSUE THREAD

**Issue by Rillke** [opencast/opencast#5363]
**Describe the bug**

When you delete a (local) user from Opencast who created a theme, the re-indexation of themes will fail with a null pointer exception.

See https://groups.google.com/a/opencast.org/g/users/c/8y1a6FxENP4/m/LVu7nGd2BAAJ

**To Reproduce**

1. Log in as an admin to Opencast Admin UI.
2. Create a local user in Opencast using the Admin UI.
3. Log in as that user.
4. Create a theme using that user.
5. Log in as an admin again.
6. Delete the user you created in 2.
7. Start Re-Indexation of themes. (through `/index/rebuild/Themes`)
8. The following stack trace will be printed to your OC Admin Logs:

```
2023-10-24T23:21:12,865 | ERROR | (AbstractIndexProducer:199) | Error updating the Elasticsearch index from service 'Themes'.
java.lang.NullPointerException: null
        at org.opencastproject.themes.persistence.ThemesServiceDatabaseImpl.lambda$getThemeUpdateFunction$9(ThemesServiceDatabaseImpl.java:428) ~[!/:?]
        at org.opencastproject.themes.persistence.ThemesServiceDatabaseImpl.repopulate(ThemesServiceDatabaseImpl.java:316) [!/:?]
        at org.opencastproject.elasticsearch.index.rebuild.IndexRebuildService.rebuildIndex(IndexRebuildService.java:196) [!/:?]
        at org.opencastproject.elasticsearch.index.rebuild.IndexRebuildService.rebuildIndex(IndexRebuildService.java:128) [!/:?]
        at org.opencastproject.elasticsearch.index.endpoint.IndexEndpoint.lambda$rebuildIndex$3(IndexEndpoint.java:161) [!/:?]
        at org.opencastproject.security.util.SecurityContext.lambda$runInContext$0(SecurityContext.java:68) [!/:?]
        at org.opencastproject.security.util.SecurityContext.runInContext(SecurityContext.java:58) [!/:?]
        at org.opencastproject.security.util.SecurityContext.runInContext(SecurityContext.java:67) [!/:?]
        at org.opencastproject.elasticsearch.index.endpoint.IndexEndpoint.lambda$rebuildIndex$4(IndexEndpoint.java:158) [!/:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
2023-10-24T23:21:12,865 | ERROR | (IndexEndpoint:163) | Repopulating the index failed
org.opencastproject.elasticsearch.index.rebuild.IndexRebuildException: Error updating the Elasticsearch index for service Themes
        at org.opencastproject.themes.persistence.ThemesServiceDatabaseImpl.repopulate(ThemesServiceDatabaseImpl.java:332) ~[?:?]
        at org.opencastproject.elasticsearch.index.rebuild.IndexRebuildService.rebuildIndex(IndexRebuildService.java:196) ~[!/:?]
        at org.opencastproject.elasticsearch.index.rebuild.IndexRebuildService.rebuildIndex(IndexRebuildService.java:128) ~[!/:?]
        at org.opencastproject.elasticsearch.index.endpoint.IndexEndpoint.lambda$rebuildIndex$3(IndexEndpoint.java:161) [!/:?]
        at org.opencastproject.security.util.SecurityContext.lambda$runInContext$0(SecurityContext.java:68) [!/:?]
        at org.opencastproject.security.util.SecurityContext.runInContext(SecurityContext.java:58) [!/:?]
        at org.opencastproject.security.util.SecurityContext.runInContext(SecurityContext.java:67) [!/:?]
        at org.opencastproject.elasticsearch.index.endpoint.IndexEndpoint.lambda$rebuildIndex$4(IndexEndpoint.java:158) [!/:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.NullPointerException
        at org.opencastproject.themes.persistence.ThemesServiceDatabaseImpl.lambda$getThemeUpdateFunction$9(ThemesServiceDatabaseImpl.java:428) ~[?:?]
        at org.opencastproject.themes.persistence.ThemesServiceDatabaseImpl.repopulate(ThemesServiceDatabaseImpl.java:316) ~[?:?]
        ... 10 more
```

Note that the issue I see is that the referenced user name does not reference the user name in the oc_user table so users who created themes might be deleted without `ON DELTE` constraints, or re-indexation should not attempt to instantiate a `User` if it does not exist anymore. I would prefer a consistent DB (first option), though.

**Expected behavior**

Re-Indexation without exception in 7. or an error that prevented me from deleting the user in 6.

**Server environment:**
 - OS: RHEL8
 - Distribution: all
- Installation method: packages
 - Version: at least 13.x

**Additional context**

**Comment by mtneug** [comment]
Fixed by #6542.
