### ISSUE TITLE
OutOfMemory: Java heap space Error when populating index

### ISSUE THREAD

**Issue by NgoniChoga** [opencast/opencast#5364]
Java heap space Error when populating index in `modules/search-service-impl/src/main/java/org/opencastproject/search/impl/SearchServiceImpl.java:602`

This appears to happening as a result of holding too many media packages in memory during a reindex. Code causing the OutOfMemory error is located at, `modules/search-service-impl/src/main/java/org/opencastproject/search/impl/persistence/SearchServiceDatabaseImpl.java:227`:

```
List<Tuple<MediaPackage, String>> mediaPackageList = new LinkedList<>();
try {
  for (SearchEntity entity : searchEntities) {
    MediaPackage mediaPackage = MediaPackageParser.getFromXml(entity.getMediaPackageXML());
    mediaPackageList.add(Tuple.tuple(mediaPackage, entity.getOrganization().getId()));
  }
} catch (Exception e) {
  logger.error("Could not parse series entity: {}", e.getMessage());
  throw new SearchServiceDatabaseException(e);
} 
```

**To Reproduce**

1. Attempt to reindex an opencast instance with a large set of MediaPackages.

**Expected behavior**

Reindex should complete successfully.

**Stack trace**

```
ERROR o.o.s.i.SearchServiceImpl [FelixStartLevel] bundle opencast-search-service-impl:15.0.0.SNAPSHOT (160)[org.opencastproject.search.impl.SearchServiceImpl(322)] : The activate method has thrown an exception
java.lang.OutOfMemoryError: Java heap space
        at java.lang.StringUTF16.compress(StringUTF16.java:160) ~[?:?]
        at java.lang.String.<init>(String.java:3214) ~[?:?]
        at java.lang.String.<init>(String.java:276) ~[?:?]
        at org.apache.xerces.xni.XMLString.toString(Unknown Source) ~[org.apache.servicemix.bundles.xerces-2.12.0_1.jar:?]
        at org.apache.xerces.parsers.AbstractDOMParser.characters(Unknown Source) ~[org.apache.servicemix.bundles.xerces-2.12.0_1.jar:?]
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanContent(Unknown Source) ~[org.apache.servicemix.bundles.xerces-2.12.0_1.jar:?]
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source) ~[org.apache.servicemix.bundles.xerces-2.12.0_1.jar:?]
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source) ~[org.apache.servicemix.bundles.xerces-2.12.0_1.jar:?]
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) ~[org.apache.servicemix.bundles.xerces-2.12.0_1.jar:?]
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) ~[org.apache.servicemix.bundles.xerces-2.12.0_1.jar:?]
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source) ~[org.apache.servicemix.bundles.xerces-2.12.0_1.jar:?]
        at org.apache.xerces.parsers.DOMParser.parse(Unknown Source) ~[org.apache.servicemix.bundles.xerces-2.12.0_1.jar:?]
        at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source) ~[org.apache.servicemix.bundles.xerces-2.12.0_1.jar:?]
        at org.opencastproject.util.XmlSafeParser.parse(XmlSafeParser.java:187) ~[?:?]
        at org.opencastproject.util.XmlSafeParser.parse(XmlSafeParser.java:150) ~[?:?]
        at org.opencastproject.mediapackage.MediaPackageBuilderImpl.loadFromXml(MediaPackageBuilderImpl.java:106) ~[?:?]
        at org.opencastproject.mediapackage.MediaPackageBuilderImpl.loadFromXml(MediaPackageBuilderImpl.java:137) ~[?:?]
        at org.opencastproject.mediapackage.MediaPackageParser.getFromXml(MediaPackageParser.java:268) ~[?:?]
        at org.opencastproject.search.impl.persistence.SearchServiceDatabaseImpl.getAllMediaPackages(SearchServiceDatabaseImpl.java:230) ~[?:?]
        at org.opencastproject.search.impl.SearchServiceImpl.populateIndex(SearchServiceImpl.java:622) ~[?:?]
        at org.opencastproject.search.impl.SearchServiceImpl.activate(SearchServiceImpl.java:276) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.apache.felix.scr.impl.inject.methods.BaseMethod.invokeMethod(BaseMethod.java:245) ~[?:?]
        at org.apache.felix.scr.impl.inject.methods.BaseMethod.access$500(BaseMethod.java:41) ~[?:?]
        at org.apache.felix.scr.impl.inject.methods.BaseMethod$Resolved.invoke(BaseMethod.java:687) ~[?:?]
        at org.apache.felix.scr.impl.inject.methods.BaseMethod.invoke(BaseMethod.java:531) ~[?:?]
        at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:317) ~[?:?]
        at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:307) ~[?:?]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.createImplementationObject(SingleComponentManager.java:354) ~[?:?]
```

**Comment by gregorydlogan** [comment]
Closed with https://github.com/opencast/opencast/pull/5365
