### ISSUE TITLE
Document how to create new Opencast Services

### ISSUE THREAD

**Issue by gregorydlogan** [opencast/opencast#5410]
We have a bad habit of copy and pasting old services, and replacing their guts.  This has led to several bad habits over the years, to the point that even *I'm* not sure how to do it right.  We should fix that.

Subtasks:
- Document how to make an Opencast/OSGi service from scratch
  - What does `immediate` do?
- Document how to make said service a JobProducer, and what that means
- Document what a `ManagedService` is, *and why you probably don't want to make one*[1]
- Implement a checkstyle-and-whitelist system to the existing tests to ensure that new ones don't show up without a good reason

1: Via Lars on 23-11-06:
```
Just got a good example why you don't want to implement a ManagedService:

1234567891011121314151617181920212223242526272829ating configuration org.opencastproject.external.endpoint.EventsEndpoint
java.lang.NumberFormatException: For input string: "7200a"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:?]
        at java.lang.Long.parseLong(Long.java:692) ~[?:?]
        at java.lang.Long.parseLong(Long.java:817) ~[?:?]
        at org.opencastproject.external.endpoint.EventsEndpoint.updated(EventsEndpoint.java:369) ~[?:?]
        at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updated(ManagedServiceTracker.java:189) ~[?:?]
        at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updateService(ManagedServiceTracker.java:152) ~[?:?]
        at org.apache.felix.cm.impl.helper.ManagedServiceTracker.provideConfiguration(ManagedServiceTracker.java:85) ~[?:?]
        at org.apache.felix.cm.impl.ConfigurationManager$UpdateConfiguration.run(ConfigurationManager.java:1418) ~[?:?]
        at org.apache.felix.cm.impl.UpdateThread.run0(UpdateThread.java:122) ~[?:?]
        at org.apache.felix.cm.impl.UpdateThread.run(UpdateThread.java:84) ~[?:?]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
2023-11-03 12:15:22,120 | INFO  | (EventsEndpoint:350) - Activating External API - Events Endpoint
2023-11-03 12:15:22,159 | INFO  | (RestPublisher:331) - Registered REST endpoint at /api/events
2023-11-03 12:15:22,160 | ERROR | (Log:186) - [org.opencastproject.external.endpoint.EventsEndpoint, org.osgi.service.cm.ManagedService, id=790, bundle=116/mvn:org.opencastproject/opencast-external-api/15-SNAPSHOT]: Unexpected problem updating configuration org.opencastproject.external.endpoint.EventsEndpoint
java.lang.NumberFormatException: For input string: "7200a"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:?]
        at java.lang.Long.parseLong(Long.java:692) ~[?:?]
        at java.lang.Long.parseLong(Long.java:817) ~[?:?]
        at org.opencastproject.external.endpoint.EventsEndpoint.updated(EventsEndpoint.java:369) ~[?:?]
        at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updated(ManagedServiceTracker.java:189) ~[?:?]
        at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updateService(ManagedServiceTracker.java:152) ~[?:?]
        at org.apache.felix.cm.impl.helper.ManagedServiceTracker.provideConfiguration(ManagedServiceTracker.java:85) ~[?:?]
        at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.provide(ConfigurationManager.java:1131) ~[?:?]
        at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.run(ConfigurationManager.java:1087) ~[?:?]
        at org.apache.felix.cm.impl.UpdateThread.run0(UpdateThread.java:122) ~[?:?]
        at org.apache.felix.cm.impl.UpdateThread.run(UpdateThread.java:84) ~[?:?]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]

This is an update to the configuration file while Opencast is running. The exception is expected, because the configuration is broken. But it's weird that the exception appears twice, isn't it? 😁

The reason for that is that the ManagedService gets the new configuration and throws the exception but then the whole service is restarted by the logic behind OSGi declarative services (since the service does not implement a modified() method. This is why the ManagedService gets yet another configuration update which then fails a second time. Technically, well, this works. After all, the first run of update() does not matter because the service is then shut down. But that's probably not what anyone would expect and it's definitely not optimal.
```

**Comment by gregorydlogan** [comment]
Assigning to me, but if you want to work on this feel free just let me know!
