### ISSUE TITLE
Opencast won't start if a system jar with the same version is also in the deploy folder

### ISSUE THREAD

**Issue by KatrinIhler** [opencast/opencast#5471]
Opencast won't start if a system jar with the same version is also in the deploy folder:

```
org.osgi.framework.BundleException: Bundle symbolic name and version are not unique: opencast-admin-ui-frontend:14.0.0.SNAPSHOT
	at org.apache.felix.framework.BundleImpl.createRevision(BundleImpl.java:1352)
	at org.apache.felix.framework.BundleImpl.<init>(BundleImpl.java:114)
	at org.apache.felix.framework.Felix.installBundle(Felix.java:3287)
	at org.apache.felix.framework.BundleContextImpl.installBundle(BundleContextImpl.java:147)
	at org.eclipse.equinox.internal.region.BundleIdBasedRegion.installBundle0(BundleIdBasedRegion.java:120)
	at org.eclipse.equinox.internal.region.BundleIdBasedRegion.installBundleAtLocation(BundleIdBasedRegion.java:100)
	at org.apache.karaf.features.internal.service.BundleInstallSupportImpl.installBundle(BundleInstallSupportImpl.java:135)
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.installBundle(FeaturesServiceImpl.java:1145)
	at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:906)
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1069)
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:1004)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)


	at java.base/java.lang.Thread.run(Thread.java:829)
```

This error was seen in OC 14. I'm pretty sure that this used to work, but going as far back as OC 12 still shows the same error. Probably was changed by a Karaf update a while ago. Before, Karaf would just pick one at random iirc (which isn't much better). But this means that you can't (or shouldn't) use the deploy folder to update an existing Opencast module (which I sometimes like to do to avoid an OC restart) because while this works just fine at that moment, Opencast won't start up again once shutdown for any reason. Which can be a nasty surprise.

I would like for Karaf to pick the module from the deploy folder in hat case, but not sure if that's possible and how to do it.

**Comment by geichelberger** [comment]
That doesn't seem like a bug; it seems more like intended behavior. During development, it's easy to redeploy a bundle with the Karaf console `bundle:watch` or `bundle:install`

**Comment by lkiesow** [comment]
I agree. Loading from two places could certainly result in unforeseen behavior. It wouldn't be clear which bundle would be loaded first and therefor, which bundle would “win”. You could easily end up with one version the first time and with the other version after a restart.

**Comment by KatrinIhler** [comment]
Sure, but this was actually kinda useful for production as well, and I'm pretty sure this used to work. Right now the behavior is kind of weird, bc it works fine until somebody restarts Opencast, and then the service won't start anymore. :/

**Comment by KatrinIhler** [comment]
Ah, I was to fast with replying. :D @lkiesow I agree that we don't want to go back to Opencast basically throwing the dice for which module version to use. I think the most reasonable expectation right now is that the module in the deploy folder would win.

**Comment by geichelberger** [comment]
You could update the bundle in the system folder and force a reload.

**Comment by lkiesow** [comment]
Yep, that's what I usually do and recommend when I want to update a bundle without updating the version.

**Comment by KatrinIhler** [comment]
> You could update the bundle in the system folder and force a reload.

Can I do that without restarting Opencast? :eyes:

**Comment by geichelberger** [comment]
If you have access to the Karaf console, yes.

**Comment by KatrinIhler** [comment]
> If you have access to the Karaf console, yes.

I currently don't - any idea how to do that on a server without restarting Opencast to run the start script directly? :D ( :turtle:   all the way down...)

**Comment by geichelberger** [comment]
You can enable the remote console which can be accessed via SSH. https://karaf.apache.org/manual/latest/#_sshd_server

**Comment by KatrinIhler** [comment]
> You can enable the remote console which can be accessed via SSH. https://karaf.apache.org/manual/latest/#_sshd_server

Interesting, I thought this was more difficult. Though I wonder if it's a good idea to turn this on in a production system...

Back to topic: I still maintain that accepting a bundle with the same version in the deploy folder initially and only falling over dead when restarting later is kind of blegh. :D
