### ISSUE TITLE
Partial-Retract WOH does not work in combination with publication to wowza 

### ISSUE THREAD

**Issue by thet0ast3r** [opencast/opencast#5665]
**Describe the bug**

Attempting to use 'partial-retract' in a workflow, even if no flavors or tags are selected to partially retract (expected behavior: no change) results in a broken , non-playable, wowza stream. 

**To Reproduce**

1. run opencast in conjunction with wowza to serve videos.
2. Create an event with a working, playable publication. 
3. add a workflow definition that attempts to partially retract any flavor/tag/file or even nothing. 
4. Run the workflow.
5. Attempt to play the video - broken.

**Expected behavior**

Running the partial-retract wf operation should do what it states: just remove parts of the publication according to the selected flavors/tags in the wf-operation configuration. 

**Stack trace**

OC log from running a minimal workflow that does only partial-retract on a fresh event:

```
2024-03-05T12:24:34,237 | INFO  | (WorkflowServiceImpl:682) - Scheduling workflow 823133 for execution
2024-03-05T12:24:36,272 | INFO  | (PartialRetractEngageWorkflowOperationHandler:118) - Partially retracting 46639333-866e-4d9d-9dbe-d75f19e2ff21
2024-03-05T12:24:38,378 | WARN  | (WowzaStreamingDistributionService:931) - /datadisk/exports/matterhorn/content/streams/mh_default_org/engage-player/46639333-866e-4d9d-9dbe-d75f19e2ff21/cb17c298-fd1c-49ad-a236-077de2789f91/cam.mp4 does not exist but was to be deleted
2024-03-05T12:24:38,452 | WARN  | (WowzaStreamingDistributionService:931) - /datadisk/exports/matterhorn/content/streams/mh_default_org/engage-player/46639333-866e-4d9d-9dbe-d75f19e2ff21/0b1e7f18-d8c8-4bd4-9826-3e8e42eafea3/cam.mp4 does not exist but was to be deleted
2024-03-05T12:24:38,539 | WARN  | (WowzaStreamingDistributionService:931) - /datadisk/exports/matterhorn/content/streams/mh_default_org/engage-player/46639333-866e-4d9d-9dbe-d75f19e2ff21/636a6429-c49e-40c2-b1bb-89b7d0f8af9a/cam.mp4 does not exist but was to be deleted
2024-03-05T12:24:38,714 | WARN  | (WowzaStreamingDistributionService:978) - Tried to delete non-existent element file. Perhaps was already deleted?: /datadisk/exports/matterhorn/content/streams/mh_default_org/engage-player/46639333-866e-4d9d-9dbe-d75f19e2ff21/e7e40fcf-c0eb-43ea-8419-71a9d4784c34/cam.mp4
2024-03-05T12:24:38,798 | WARN  | (WowzaStreamingDistributionService:978) - Tried to delete non-existent element file. Perhaps was already deleted?: /datadisk/exports/matterhorn/content/streams/mh_default_org/engage-player/46639333-866e-4d9d-9dbe-d75f19e2ff21/e7e40fcf-c0eb-43ea-8419-71a9d4784c34/cam.mp4
2024-03-05T12:24:38,798 | WARN  | (WowzaStreamingDistributionService:992) - Element directory did not exist when trying to delete it: /datadisk/exports/matterhorn/content/streams/mh_default_org/engage-player/46639333-866e-4d9d-9dbe-d75f19e2ff21/e7e40fcf-c0eb-43ea-8419-71a9d4784c34
2024-03-05T12:24:38,817 | INFO  | (ServiceRegistryJpaImpl:2268) - State set to WARNING for current service org.opencastproject.distribution.streaming on host https://tube-test.tugraz.at
2024-03-05T12:24:38,849 | ERROR | (AbstractJobProducer$JobRunner:343) - Error handling operation 'Retract':
org.opencastproject.serviceregistry.api.ServiceRegistryException: Error handling operation 'Retract'
	at org.opencastproject.distribution.streaming.wowza.WowzaStreamingDistributionService.process(WowzaStreamingDistributionService.java:1134) ~[?:?]
	at org.opencastproject.job.api.AbstractJobProducer$JobRunner.call(AbstractJobProducer.java:313) [!/:?]
	at org.opencastproject.job.api.AbstractJobProducer$JobRunner.call(AbstractJobProducer.java:272) [!/:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.NullPointerException
	at org.opencastproject.distribution.streaming.wowza.WowzaStreamingDistributionService.deleteElementFile(WowzaStreamingDistributionService.java:984) ~[?:?]
	at org.opencastproject.distribution.streaming.wowza.WowzaStreamingDistributionService.retractElement(WowzaStreamingDistributionService.java:950) ~[?:?]
	at org.opencastproject.distribution.streaming.wowza.WowzaStreamingDistributionService.retractElements(WowzaStreamingDistributionService.java:897) ~[?:?]
	at org.opencastproject.distribution.streaming.wowza.WowzaStreamingDistributionService.process(WowzaStreamingDistributionService.java:1122) ~[?:?]
	... 6 more
2024-03-05T12:24:38,896 | WARN  | (WowzaStreamingDistributionService:978) - Tried to delete non-existent element file. Perhaps was already deleted?: /datadisk/exports/matterhorn/content/streams/mh_default_org/engage-player/46639333-866e-4d9d-9dbe-d75f19e2ff21/e7e40fcf-c0eb-43ea-8419-71a9d4784c34/cam.mp4
2024-03-05T12:24:38,896 | WARN  | (WowzaStreamingDistributionService:992) - Element directory did not exist when trying to delete it: /datadisk/exports/matterhorn/content/streams/mh_default_org/engage-player/46639333-866e-4d9d-9dbe-d75f19e2ff21/e7e40fcf-c0eb-43ea-8419-71a9d4784c34
2024-03-05T12:24:38,950 | WARN  | (WowzaStreamingDistributionService:978) - Tried to delete non-existent element file. Perhaps was already deleted?: /datadisk/exports/matterhorn/content/streams/mh_default_org/engage-player/46639333-866e-4d9d-9dbe-d75f19e2ff21/58965977-f626-4080-b5bb-c3b92b7e619c/cam.mp4
2024-03-05T12:24:38,950 | WARN  | (WowzaStreamingDistributionService:992) - Element directory did not exist when trying to delete it: /datadisk/exports/matterhorn/content/streams/mh_default_org/engage-player/46639333-866e-4d9d-9dbe-d75f19e2ff21/58965977-f626-4080-b5bb-c3b92b7e619c
2024-03-05T12:24:38,950 | WARN  | (WowzaStreamingDistributionService:975) - Could not properly delete element file: /datadisk/exports/matterhorn/content/streams/mh_default_org/engage-player/46639333-866e-4d9d-9dbe-d75f19e2ff21/58965977-f626-4080-b5bb-c3b92b7e619c/cam.mp4
2024-03-05T12:24:38,950 | WARN  | (WowzaStreamingDistributionService:992) - Element directory did not exist when trying to delete it: /datadisk/exports/matterhorn/content/streams/mh_default_org/engage-player/46639333-866e-4d9d-9dbe-d75f19e2ff21/58965977-f626-4080-b5bb-c3b92b7e619c
2024-03-05T12:24:38,954 | WARN  | (WowzaStreamingDistributionService:975) - Could not properly delete element file: /datadisk/exports/matterhorn/content/streams/mh_default_org/engage-player/46639333-866e-4d9d-9dbe-d75f19e2ff21/5ca04654-de1b-4f79-bc3a-7bf06d52c598/cam.mp4
2024-03-05T12:24:38,954 | WARN  | (WowzaStreamingDistributionService:975) - Could not properly delete element file: /datadisk/exports/matterhorn/content/streams/mh_default_org/engage-player/46639333-866e-4d9d-9dbe-d75f19e2ff21/5ca04654-de1b-4f79-bc3a-7bf06d52c598/cam.mp4
2024-03-05T12:24:38,989 | WARN  | (WowzaStreamingDistributionService:986) - Could not properly delete element directory: /datadisk/exports/matterhorn/content/streams/mh_default_org/engage-player/46639333-866e-4d9d-9dbe-d75f19e2ff21/5ca04654-de1b-4f79-bc3a-7bf06d52c598
2024-03-05T12:24:39,000 | INFO  | (ServiceRegistryJpaImpl:2289) - State reset to NORMAL for current service org.opencastproject.distribution.streaming on host https://tube-test.tugraz.at
2024-03-05T12:24:39,039 | INFO  | (WowzaStreamingDistributionService:961) - Finished retracting element https://wowza-test.tugraz.at/matterhorn_engage/smil:engage-player_46639333-866e-4d9d-9dbe-d75f19e2ff21_presenter.smil/manifest of media package 46639333-866e-4d9d-9dbe-d75f19e2ff21
2024-03-05T12:24:39,041 | WARN  | (WowzaStreamingDistributionService:999) - Could not properly delete mediapackage directory: /datadisk/exports/matterhorn/content/streams/mh_default_org/engage-player/46639333-866e-4d9d-9dbe-d75f19e2ff21
2024-03-05T12:24:39,041 | INFO  | (WowzaStreamingDistributionService:961) - Finished retracting element https://wowza-test.tugraz.at/matterhorn_engage/smil:engage-player_46639333-866e-4d9d-9dbe-d75f19e2ff21_presenter.smil/manifest.f4m of media package 46639333-866e-4d9d-9dbe-d75f19e2ff21
2024-03-05T12:24:39,210 | ERROR | (AbstractJobProducer$JobRunner:343) - Error handling operation 'Retract':
org.opencastproject.serviceregistry.api.ServiceRegistryException: Error handling operation 'Retract'
	at org.opencastproject.distribution.streaming.wowza.WowzaStreamingDistributionService.process(WowzaStreamingDistributionService.java:1134) ~[?:?]
	at org.opencastproject.job.api.AbstractJobProducer$JobRunner.call(AbstractJobProducer.java:313) [!/:?]
	at org.opencastproject.job.api.AbstractJobProducer$JobRunner.call(AbstractJobProducer.java:272) [!/:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.NullPointerException
	at org.opencastproject.distribution.streaming.wowza.WowzaStreamingDistributionService.deleteElementFile(WowzaStreamingDistributionService.java:984) ~[?:?]
	at org.opencastproject.distribution.streaming.wowza.WowzaStreamingDistributionService.retractElement(WowzaStreamingDistributionService.java:950) ~[?:?]
	at org.opencastproject.distribution.streaming.wowza.WowzaStreamingDistributionService.retractElements(WowzaStreamingDistributionService.java:897) ~[?:?]
	at org.opencastproject.distribution.streaming.wowza.WowzaStreamingDistributionService.process(WowzaStreamingDistributionService.java:1122) ~[?:?]
	... 6 more
2024-03-05T12:24:41,421 | ERROR | (WorkflowOperationWorker:140) - Workflow operation 'operation:'retract-partial, state:'FAILED'' failed
org.opencastproject.workflow.api.WorkflowOperationException: The retract jobs did not complete successfully
	at org.opencastproject.workflow.handler.distribution.PartialRetractEngageWorkflowOperationHandler.start(PartialRetractEngageWorkflowOperationHandler.java:160) ~[?:?]
	at org.opencastproject.workflow.impl.WorkflowOperationWorker.start(WorkflowOperationWorker.java:212) ~[!/:?]
	at org.opencastproject.workflow.impl.WorkflowOperationWorker.execute(WorkflowOperationWorker.java:117) [!/:?]
	at org.opencastproject.workflow.impl.WorkflowServiceImpl.runWorkflowOperation(WorkflowServiceImpl.java:723) [!/:?]
	at org.opencastproject.workflow.impl.WorkflowServiceImpl.process(WorkflowServiceImpl.java:1755) [!/:?]
	at org.opencastproject.workflow.impl.WorkflowServiceImpl$JobRunner.call(WorkflowServiceImpl.java:2116) [!/:?]
	at org.opencastproject.workflow.impl.WorkflowServiceImpl$JobRunner.call(WorkflowServiceImpl.java:2082) [!/:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]

```

**Server environment:**
OC 14.7.0 
CentOS 7 
Nodes:
Admin+Presentation, Worker nodes

**Comment by llttugraz** [comment]
Meanwhile we have an update on this:
We have switched our OS from CentOS to Debian 12 for hosting Opencast 15.6. We have openjdk 17.0.11 in the new system. We also use Wowza for publishing events.
Ever since the OS switch, retract operation would always fail for us with the following error:

```

job-operation

Retract

job-type

org.opencastproject.distribution.streaming

stack-trace

org.opencastproject.serviceregistry.api.ServiceRegistryException: Error handling operation 'Retract'
	at org.opencastproject.distribution.streaming.wowza.WowzaStreamingDistributionService.process(WowzaStreamingDistributionService.java:1134)
	at org.opencastproject.job.api.AbstractJobProducer$JobRunner.call(AbstractJobProducer.java:314)
	at org.opencastproject.job.api.AbstractJobProducer$JobRunner.call(AbstractJobProducer.java:273)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.NullPointerException: Cannot read the array length because the return value of "java.io.File.list()" is null
	at org.opencastproject.distribution.streaming.wowza.WowzaStreamingDistributionService.deleteElementFile(WowzaStreamingDistributionService.java:984)
	at org.opencastproject.distribution.streaming.wowza.WowzaStreamingDistributionService.retractElement(WowzaStreamingDistributionService.java:950)
	at org.opencastproject.distribution.streaming.wowza.WowzaStreamingDistributionService.retractElements(WowzaStreamingDistributionService.java:897)
	at org.opencastproject.distribution.streaming.wowza.WowzaStreamingDistributionService.process(WowzaStreamingDistributionService.java:1122)
	... 6 more

```

We found that problem are these lines:
- https://github.com/opencast/opencast/blob/80b3708ab6956afde1cd99c1f7b58009d0a86b36/modules/distribution-service-streaming-wowza/src/main/java/org/opencastproject/distribution/streaming/wowza/WowzaStreamingDistributionService.java#L983
`if (elementDir != null && elementDir.exists() && elementDir.list() != null) {`

- https://github.com/opencast/opencast/blob/80b3708ab6956afde1cd99c1f7b58009d0a86b36/modules/distribution-service-streaming-wowza/src/main/java/org/opencastproject/distribution/streaming/wowza/WowzaStreamingDistributionService.java#L996
`if (mediapackageDir != null && mediapackageDir.exists()) {`

We changed `if (elementDir != null && elementDir.exists() && elementDir.list() != null) {`
to 
`if (elementDir.isDirectory()) {`

and also changed `if (mediapackageDir != null && mediapackageDir.exists()) {`
to 
`if (mediapackageDir.isDirectory()) {`

then built the module and deployed on our system, and this fixed the retract issue caused by `value of "java.io.File.list()" is null`.

**Comment by llttugraz** [comment]
The above patch is working on our system but we'd be grateful if someone else would make a PR :)
Thanks

**Comment by JayBraker** [comment]
I'm curious as we might be facing a similar issue: Were you using CephFS by any chance?

**Comment by gregorydlogan** [comment]
I've filed the PR, going to need you to test though.  I don't have a Wowza install to use, nor can I reproduce it.

**Comment by aliyevTU** [comment]
> I'm curious as we might be facing a similar issue: Were you using CephFS by any chance?

yes, we are also using CephFS

**Comment by t-schroeder** [comment]
We observed the same error in the `retract-engage` WOH:

```
job-operation
Retract
job-type
org.opencastproject.distribution.streaming
stack-trace
org.opencastproject.serviceregistry.api.ServiceRegistryException: Error handling operation 'Retract'
	at org.opencastproject.distribution.streaming.wowza.WowzaStreamingDistributionService.process(WowzaStreamingDistributionService.java:1134)
	at org.opencastproject.job.api.AbstractJobProducer$JobRunner.call(AbstractJobProducer.java:314)
	at org.opencastproject.job.api.AbstractJobProducer$JobRunner.call(AbstractJobProducer.java:273)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.NullPointerException: Cannot read the array length because the return value of "java.io.File.list()" is null
	at org.opencastproject.distribution.streaming.wowza.WowzaStreamingDistributionService.deleteElementFile(WowzaStreamingDistributionService.java:984)
	at org.opencastproject.distribution.streaming.wowza.WowzaStreamingDistributionService.retractElement(WowzaStreamingDistributionService.java:950)
	at org.opencastproject.distribution.streaming.wowza.WowzaStreamingDistributionService.retractElements(WowzaStreamingDistributionService.java:897)
	at org.opencastproject.distribution.streaming.wowza.WowzaStreamingDistributionService.process(WowzaStreamingDistributionService.java:1122)
	... 6 more
```

Also using CephFS.

**Comment by aliyevTU** [comment]
@gregorydlogan can you please provide us with prebuilt module for Opencast version 14.12 and 15.6? If we get prebuilt jar files we can test it with wowza and let you know?

**Comment by gregorydlogan** [comment]
GitHub won't let me attach jars, so here they are as zips.  Had to modify the patch, but it's the same logic just a different version of `FileUtils`

[opencast-distribution-service-streaming-wowza-15.6.zip](https://github.com/user-attachments/files/18853668/opencast-distribution-service-streaming-wowza-15.6.zip)

[opencast-distribution-service-streaming-wowza-14.12.zip](https://github.com/user-attachments/files/18853669/opencast-distribution-service-streaming-wowza-14.12.zip)

**Comment by aliyevTU** [comment]
> GitHub won't let me attach jars, so here they are as zips. Had to modify the patch, but it's the same logic just a different version of `FileUtils`
> 
> [opencast-distribution-service-streaming-wowza-15.6.zip](https://github.com/user-attachments/files/18853668/opencast-distribution-service-streaming-wowza-15.6.zip)
> 
> [opencast-distribution-service-streaming-wowza-14.12.zip](https://github.com/user-attachments/files/18853669/opencast-distribution-service-streaming-wowza-14.12.zip)

Thanks for the files Greg. We tested it with Wowza on our system, all looks good.

**Comment by aliyevTU** [comment]
> I've filed the PR, going to need you to test though. I don't have a Wowza install to use, nor can I reproduce it.

we tested it, and its all good

**Comment by mtneug** [comment]
Fixed by #6431.
