### ISSUE TITLE
failure at workflow step "Inspecting audio and video streams" - dublincore.xml failed

### ISSUE THREAD

**Issue by mwuttke** [opencast/opencast#5731]
With the support of elan, we have adapted the schedule & upload workflow to be able to add subtitles to scheduled lecture recordings, either via Amberscript or Whipser. We then tested the workflows. The subtitling with Whisper in German and English runs through. The transcription with amberscript into English also works. However, the workflow fails repoducible for Amberscript for a German subtitling. The workflow always fails at step Inspecting audio and video streams with the following error message:

**Stack trace**
```
2024-03-27T14:29:42,939 | WARN  | (WorkspaceImpl:419) - The working file repository URI and paths don't match. Looking up https://XXX/files/mediapackage/0e33934e-4d0a-4188-95c5-58e055b5211a/79b519d3-66bb-410a-9468-32eb768d4d64/dublincore.xml at /srv/opencast/files/mediapackage/0e33934e-4d0a-4188-95c5-58e055b5211a/79b519d3-66bb-410a-9468-32eb768d4d64/dublincore.xml failed
2024-03-27T14:29:42,941 | WARN  | (WorkspaceImpl:387) - The working file repository and workspace paths don't match. Looking up https://XXX/files/mediapackage/0e33934e-4d0a-4188-95c5-58e055b5211a/79b519d3-66bb-410a-9468-32eb768d4d64/dublincore.xml at /srv/opencast/files/mediapackage/0e33934e-4d0a-4188-95c5-58e055b5211a/79b519d3-66bb-410a-9468-32eb768d4d64/dublincore.xml failed
2024-03-27T14:29:42,972 | ERROR | (DublinCoreUtil:79) - Unable to load metadata from catalog 'https://XXX/files/mediapackage/0e33934e-4d0a-4188-95c5-58e055b5211a/79b519d3-66bb-410a-9468-32eb768d4d64/dublincore.xml'
org.opencastproject.util.NotFoundException: null
	at org.opencastproject.workspace.impl.WorkspaceImpl.downloadIfNecessary(WorkspaceImpl.java:535) ~[?:?]
	at org.opencastproject.workspace.impl.WorkspaceImpl$2.xapply(WorkspaceImpl.java:557) ~[?:?]
	at org.opencastproject.workspace.impl.WorkspaceImpl$2.xapply(WorkspaceImpl.java:554) ~[?:?]
	at org.opencastproject.util.data.Function$X.apply(Function.java:104) ~[!/:?]
	at org.opencastproject.util.IoSupport.locked(IoSupport.java:478) ~[!/:?]
	at org.opencastproject.workspace.impl.WorkspaceImpl.get(WorkspaceImpl.java:402) ~[?:?]
	at org.opencastproject.workspace.impl.WorkspaceImpl.read(WorkspaceImpl.java:437) ~[?:?]
	at org.opencastproject.metadata.dublincore.DublinCoreUtil.loadDublinCore(DublinCoreUtil.java:76) [!/:?]
	at org.opencastproject.metadata.dublincore.DublinCoreCatalogService.getMetadata(DublinCoreCatalogService.java:107) [!/:?]
	at org.opencastproject.metadata.dublincore.DublinCoreCatalogService.getMetadata(DublinCoreCatalogService.java:55) [!/:?]
	at org.opencastproject.workflow.impl.WorkflowServiceImpl.populateMediaPackageMetadata(WorkflowServiceImpl.java:1575) [!/:?]
	at org.opencastproject.workflow.impl.WorkflowServiceImpl.update(WorkflowServiceImpl.java:1184) [!/:?]
	at org.opencastproject.workflow.impl.WorkflowServiceImpl.runWorkflowOperation(WorkflowServiceImpl.java:795) [!/:?]
	at org.opencastproject.workflow.impl.WorkflowServiceImpl.process(WorkflowServiceImpl.java:1755) [!/:?]
	at org.opencastproject.workflow.impl.WorkflowServiceImpl$JobRunner.call(WorkflowServiceImpl.java:2116) [!/:?]
	at org.opencastproject.workflow.impl.WorkflowServiceImpl$JobRunner.call(WorkflowServiceImpl.java:2082) [!/:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]
2024-03-27T14:29:42,972 | ERROR | (WorkflowServiceImpl:1209) - Metadata for media package 0e33934e-4d0a-4188-95c5-58e055b5211a could not be updated
org.opencastproject.util.NotFoundException: null
	at org.opencastproject.workspace.impl.WorkspaceImpl.downloadIfNecessary(WorkspaceImpl.java:535) ~[?:?]
	at org.opencastproject.workspace.impl.WorkspaceImpl$2.xapply(WorkspaceImpl.java:557) ~[?:?]
	at org.opencastproject.workspace.impl.WorkspaceImpl$2.xapply(WorkspaceImpl.java:554) ~[?:?]
	at org.opencastproject.util.data.Function$X.apply(Function.java:104) ~[!/:?]
	at org.opencastproject.util.IoSupport.locked(IoSupport.java:478) ~[!/:?]
	at org.opencastproject.workspace.impl.WorkspaceImpl.get(WorkspaceImpl.java:402) ~[?:?]
	at org.opencastproject.workspace.impl.WorkspaceImpl.read(WorkspaceImpl.java:437) ~[?:?]
	at org.opencastproject.metadata.dublincore.DublinCoreUtil.loadDublinCore(DublinCoreUtil.java:76) ~[?:?]
	at org.opencastproject.metadata.dublincore.DublinCoreCatalogService.getMetadata(DublinCoreCatalogService.java:107) ~[?:?]
	at org.opencastproject.metadata.dublincore.DublinCoreCatalogService.getMetadata(DublinCoreCatalogService.java:55) ~[?:?]
	at org.opencastproject.workflow.impl.WorkflowServiceImpl.populateMediaPackageMetadata(WorkflowServiceImpl.java:1575) ~[!/:?]
	at org.opencastproject.workflow.impl.WorkflowServiceImpl.update(WorkflowServiceImpl.java:1184) [!/:?]
	at org.opencastproject.workflow.impl.WorkflowServiceImpl.runWorkflowOperation(WorkflowServiceImpl.java:795) [!/:?]
	at org.opencastproject.workflow.impl.WorkflowServiceImpl.process(WorkflowServiceImpl.java:1755) [!/:?]
	at org.opencastproject.workflow.impl.WorkflowServiceImpl$JobRunner.call(WorkflowServiceImpl.java:2116) [!/:?]
	at org.opencastproject.workflow.impl.WorkflowServiceImpl$JobRunner.call(WorkflowServiceImpl.java:2082) [!/:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]
```

**To Reproduce**
1. Create a new Event
2. Select _Schedule single event_ or _Schedule multiple events_
3. Select workflow _Process upon upload and schedule_
4. Select _Straight to publishing_ and _German with amberscript_
5. Run the recording
6. See the error (above)

**Expected behavior**
The workflow should run through without errors, i.e. the lecture recording should be created and a subtitle generated.

**Server environment:**
- OS: Debian 12/Bookworm
- Opencast Version: 15.3 (deb packages)
- Separate nodes for adminpresentation, 4 workers
- NFS Server: nfsshare:/opencast /srv/opencast nfs auto,rw,bg,nosuid,nofail,timeo=100,soft,noatime,nfsvers=4,port=2049,fsc 0 0
- Extron SMP

**Additional context**
Piri from elan found similar errors on the Google mailing list:
https://groups.google.com/a/opencast.org/g/users/c/-4-1qIvThM4
https://groups.google.com/a/opencast.org/g/users/c/BXn8QkFix6U/m/sXpQntwaBgAJ

**Comment by mwuttke** [comment]
We can also reproduce this error with OC version 17.2.

As a temporary workaround, we have commented out the ingest-download operation in the partial-ingest workflow.

**Comment by KatrinIhler** [comment]
As the discussion posts already say, this is related to the timing of write and read operations on the NFS directly after each other from different nodes. It mostly appears when ingesting short videos. Switching to `sync` instead of `async` can work, but may impact performance. This was also experienced by folks from the University of Konstanz as well as the University of Bern. Iirc this doesn't happen for direct uploads bc the file is already in the workspace in that case.

@snoesberger Could you add what nfs options currently work for you?

**Comment by snoesberger** [comment]
Yes, we experienced the same problems. These problems only occurred for scheduled events and only occasionally. We never had a problem with manually uploaded videos in the Admin UI. Initially, we changed the NFS mount options to `sync`, which solved the problem with failed workflows. However, this significantly impacted the overall performance of Opencast, particularly when numerous activities occurred simultaneously (e.g., lots of recordings, uploads and manipulations at the same time).
Ultimately, we switched back to `async` and modified other mount options as recommended by our storage specialists. Currently, we have the following mount options active, and we have not had any problems since:
`vers=3,tcp,rw,hard,intr,async,actimeo=2,rsize=131072,wsize=131072,_netdev,bg`

The `actimeo=2` option in particular had a significant impact.

**Comment by scharnknhft** [comment]
Thank you for posting these mount options, they have solved the problem for us as well.

**Comment by mtneug** [comment]
As this is likely not directly related to Opencast but rather the NFS mount configuration, I will close this.
