### ISSUE TITLE
Setting `contentId` to `null` of a playlist entry returns a 500 error code

### ISSUE THREAD

**Issue by dennis531** [opencast/opencast#5744]
**Describe the bug**

The playlist API route `POST /{id}/entries` allows to set `null` values for `contentID`. It seems that there are no checks, which breaks the GET routes of the playlists api.

**Stack trace**
```
java.lang.IllegalArgumentException: Value of field 'contentId' must not be null
 	at com.entwinemedia.fn.data.json.Field.<init>(Field.java:31) ~[?:?]
 	at com.entwinemedia.fn.data.json.Jsons.f(Jsons.java:89) ~[?:?]
	at org.opencastproject.external.endpoint.PlaylistsEndpoint.playlistEntryToJson(PlaylistsEndpoint.java:401) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.Vector$VectorSpliterator.forEachRemaining(Vector.java:1470) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at org.opencastproject.external.endpoint.PlaylistsEndpoint.playlistToJson(PlaylistsEndpoint.java:384) ~[?:?]
	at org.opencastproject.external.endpoint.PlaylistsEndpoint.lambda$getPlaylistsAsJson$0(PlaylistsEndpoint.java:227) ~[?:?]
        ...
```

**Server environment:**
 - https://develop.opencast.org

**Comment by tgloeggl** [comment]
It seems that this affects the external api ( `/api/playlists`) only. `/playlists/playlists.json` still works fine and allows to see the broken entries.

**Comment by KatrinIhler** [comment]
> It seems that this affects the external api ( /api/playlists) only. /playlists/playlists.json still works fine and allows to see the broken entries.

Yes and no. If you set `withPublications`, the Elasticsearch Query will fall apart for an empty content id.
