### ISSUE TITLE
Creating subtitles using whisper.cpp does not work using long videos

### ISSUE THREAD

**Issue by mwuttke** [opencast/opencast#5747]
Creating subtitles using whisper.cpp does not work in our setup using long videos.

I have tested the Opencast Transcription Service SpeechtoText for whisper with [whisper.cpp](https://github.com/ggerganov/whisper.cpp) and corresponding workflows for German and English using videos with a length of 90 min.

The result cannot be saved at the end of the transcription job.

This is the logs:
```
2024-04-11T09:57:50,514 | INFO  | (ComposerServiceImpl:572) - Starting parallel encode with profile audio-whispercpp with job load 1
2024-04-11T09:58:09,274 | INFO  | (EncoderEngine:216) - Executing encoding command: [ffmpeg, -nostdin, -nostats, -i, /srv/opencast/workspace/https_domain.com/assets/assets/402ce3a8-13dc-41a7-82a9-867f34d3cc24/0d817546-f3ee-4ff8-a1b4-05f668be5239/9/HU_LCP_007_20221025_131000_S2R1.m4v, -vn, -ar, 16000, -ac, 1, -c:a, pcm_s16le, /srv/opencast/workspace/https_domain.com/assets/assets/402ce3a8-13dc-41a7-82a9-867f34d3cc24/0d817546-f3ee-4ff8-a1b4-05f668be5239/9/HU_LCP_007_20221025_131000_S2R1_c5cd9e95-303e-40b8-a9bd-46b8290745b8-stt.wav]
2024-04-11T09:58:09,358 | INFO  | (EncoderEngine:491) - Chapters:
2024-04-11T09:58:09,358 | INFO  | (EncoderEngine:491) - Chapter #0:0: start 0.000000, end 5999.477000
2024-04-11T09:58:09,358 | INFO  | (EncoderEngine:491) - vendor_id       : [0][0][0][0]
2024-04-11T09:58:09,358 | INFO  | (EncoderEngine:491) - vendor_id       : [0][0][0][0]
2024-04-11T09:58:09,363 | INFO  | (EncoderEngine:460) - Identified output file /srv/opencast/workspace/https_domain.com/assets/assets/402ce3a8-13dc-41a7-82a9-867f34d3cc24/0d817546-f3ee-4ff8-a1b4-05f668be5239/9/HU_LCP_007_20221025_131000_S2R1_c5cd9e95-303e-40b8-a9bd-46b8290745b8-stt.wav
2024-04-11T09:58:09,363 | INFO  | (EncoderEngine:491) - ISFT            : Lavf60.21.100
2024-04-11T09:58:09,363 | INFO  | (EncoderEngine:491) - Chapters:
2024-04-11T09:58:09,363 | INFO  | (EncoderEngine:491) - Chapter #0:0: start 0.000000, end 5999.477000
2024-04-11T09:58:09,363 | INFO  | (EncoderEngine:491) - vendor_id       : [0][0][0][0]
2024-04-11T09:58:18,380 | INFO  | (EncoderEngine:491) - [out#0/wav @ 0x6f8e640] video:0KiB audio:187481KiB subtitle:0KiB other streams:0KiB global headers:0KiB muxing overhead: 0.000041%
2024-04-11T09:58:18,384 | INFO  | (EncoderEngine:240) - Tracks {video=/srv/opencast/workspace/https_domain.com/assets/assets/402ce3a8-13dc-41a7-82a9-867f34d3cc24/0d817546-f3ee-4ff8-a1b4-05f668be5239/9/HU_LCP_007_20221025_131000_S2R1.m4v} successfully encoded using profile 'audio-whispercpp'
2024-04-11T09:58:19,427 | INFO  | (ComposerServiceImpl:533) - Copied the encoded file to the workspace at https://domain.com/files/collection/composer/12146261_0.wav
2024-04-11T09:58:24,587 | INFO  | (ComposerServiceImpl:553) - Deleted the local copy of the encoded file at /srv/opencast/workspace/https_domain.com/assets/assets/402ce3a8-13dc-41a7-82a9-867f34d3cc24/0d817546-f3ee-4ff8-a1b4-05f668be5239/9/HU_LCP_007_20221025_131000_S2R1_c5cd9e95-303e-40b8-a9bd-46b8290745b8-stt.wav
2024-04-11T09:58:28,212 | INFO  | (ComposerServiceImpl:572) - Starting parallel encode with profile audio-whispercpp with job load 1
2024-04-11T09:58:51,005 | INFO  | (EncoderEngine:216) - Executing encoding command: [ffmpeg, -nostdin, -nostats, -i, /srv/opencast/workspace/https_domain.com/assets/assets/a225fa83-3181-4b78-b169-e2a5a904607b/07d8a5af-2cf0-4d0f-b6e0-41c9b58e3860/9/HU_LCP_007_20221021_091000_S2R1.m4v, -vn, -ar, 16000, -ac, 1, -c:a, pcm_s16le, /srv/opencast/workspace/https_domain.com/assets/assets/a225fa83-3181-4b78-b169-e2a5a904607b/07d8a5af-2cf0-4d0f-b6e0-41c9b58e3860/9/HU_LCP_007_20221021_091000_S2R1_b3ead866-1b16-4f30-8d1d-022bb0de36dd-stt.wav]
2024-04-11T09:58:51,087 | INFO  | (EncoderEngine:491) - Chapters:
2024-04-11T09:58:51,087 | INFO  | (EncoderEngine:491) - Chapter #0:0: start 0.000000, end 6033.600000
2024-04-11T09:58:51,087 | INFO  | (EncoderEngine:491) - vendor_id       : [0][0][0][0]
2024-04-11T09:58:51,087 | INFO  | (EncoderEngine:491) - vendor_id       : [0][0][0][0]
2024-04-11T09:58:51,092 | INFO  | (EncoderEngine:460) - Identified output file /srv/opencast/workspace/https_domain.com/assets/assets/a225fa83-3181-4b78-b169-e2a5a904607b/07d8a5af-2cf0-4d0f-b6e0-41c9b58e3860/9/HU_LCP_007_20221021_091000_S2R1_b3ead866-1b16-4f30-8d1d-022bb0de36dd-stt.wav
2024-04-11T09:58:51,092 | INFO  | (EncoderEngine:491) - ISFT            : Lavf60.21.100
2024-04-11T09:58:51,092 | INFO  | (EncoderEngine:491) - Chapters:
2024-04-11T09:58:51,092 | INFO  | (EncoderEngine:491) - Chapter #0:0: start 0.000000, end 6033.600000
2024-04-11T09:58:51,092 | INFO  | (EncoderEngine:491) - vendor_id       : [0][0][0][0]
2024-04-11T09:59:00,284 | INFO  | (EncoderEngine:491) - [out#0/wav @ 0x881ba40] video:0KiB audio:188549KiB subtitle:0KiB other streams:0KiB global headers:0KiB muxing overhead: 0.000040%
2024-04-11T09:59:00,289 | INFO  | (EncoderEngine:240) - Tracks {video=/srv/opencast/workspace/https_domain.com/assets/assets/a225fa83-3181-4b78-b169-e2a5a904607b/07d8a5af-2cf0-4d0f-b6e0-41c9b58e3860/9/HU_LCP_007_20221021_091000_S2R1.m4v} successfully encoded using profile 'audio-whispercpp'
2024-04-11T09:59:01,243 | INFO  | (ComposerServiceImpl:533) - Copied the encoded file to the workspace at https://domain.com/files/collection/composer/12146263_0.wav
2024-04-11T09:59:06,378 | INFO  | (ComposerServiceImpl:553) - Deleted the local copy of the encoded file at /srv/opencast/workspace/https_domain.com/assets/assets/a225fa83-3181-4b78-b169-e2a5a904607b/07d8a5af-2cf0-4d0f-b6e0-41c9b58e3860/9/HU_LCP_007_20221021_091000_S2R1_b3ead866-1b16-4f30-8d1d-022bb0de36dd-stt.wav
2024-04-11T09:59:14,091 | INFO  | (WhisperCppEngine:328) - Using language de from workflows
2024-04-11T09:59:14,091 | INFO  | (WhisperCppEngine:346) - Executing WhisperC++'s transcription command: [/usr/bin/whisper.cpp, /srv/opencast/workspace/mediapackage/a225fa83-3181-4b78-b169-e2a5a904607b/d323609e-6f30-4e4b-aa4a-e1f2aeebf64c/HU_LCP_007_20221021_091000_S2R1.wav, --model, /usr/share/whisper.cpp/medium.bin/ggml-medium.bin, -ovtt, -oj, --output-file, /srv/opencast/workspace/collection/subtitles/job-12146265/HU_LCP_007_20221021_091000_S2R1, -t, 8, --language, de]
2024-04-11T09:59:14,095 | DEBUG | (WhisperCppEngine:362) - whisper_init_from_file_with_params_no_state: loading model from '/usr/share/whisper.cpp/medium.bin/ggml-medium.bin'
2024-04-11T09:59:14,095 | DEBUG | (WhisperCppEngine:362) - whisper_model_load: loading model
2024-04-11T09:59:14,095 | DEBUG | (WhisperCppEngine:362) - whisper_model_load: n_vocab       = 51865
2024-04-11T09:59:14,095 | DEBUG | (WhisperCppEngine:362) - whisper_model_load: n_audio_ctx   = 1500
2024-04-11T09:59:14,095 | DEBUG | (WhisperCppEngine:362) - whisper_model_load: n_audio_state = 1024
2024-04-11T09:59:14,095 | DEBUG | (WhisperCppEngine:362) - whisper_model_load: n_audio_head  = 16
2024-04-11T09:59:14,095 | DEBUG | (WhisperCppEngine:362) - whisper_model_load: n_audio_layer = 24
2024-04-11T09:59:14,095 | DEBUG | (WhisperCppEngine:362) - whisper_model_load: n_text_ctx    = 448
2024-04-11T09:59:14,095 | DEBUG | (WhisperCppEngine:362) - whisper_model_load: n_text_state  = 1024
2024-04-11T09:59:14,095 | DEBUG | (WhisperCppEngine:362) - whisper_model_load: n_text_head   = 16
2024-04-11T09:59:14,095 | DEBUG | (WhisperCppEngine:362) - whisper_model_load: n_text_layer  = 24
2024-04-11T09:59:14,095 | DEBUG | (WhisperCppEngine:362) - whisper_model_load: n_mels        = 80
2024-04-11T09:59:14,095 | DEBUG | (WhisperCppEngine:362) - whisper_model_load: ftype         = 1
2024-04-11T09:59:14,095 | DEBUG | (WhisperCppEngine:362) - whisper_model_load: qntvr         = 0
2024-04-11T09:59:14,095 | DEBUG | (WhisperCppEngine:362) - whisper_model_load: type          = 4 (medium)
2024-04-11T09:59:14,125 | DEBUG | (WhisperCppEngine:362) - whisper_model_load: adding 1608 extra tokens
2024-04-11T09:59:14,126 | DEBUG | (WhisperCppEngine:362) - whisper_model_load: n_langs       = 99
2024-04-11T09:59:14,129 | DEBUG | (WhisperCppEngine:362) - whisper_model_load:      CPU buffer size =  1533.52 MB
2024-04-11T09:59:14,696 | DEBUG | (WhisperCppEngine:362) - whisper_model_load: model size    = 1533.14 MB
2024-04-11T09:59:14,696 | DEBUG | (WhisperCppEngine:362) - whisper_init_state: kv self size  =  132.12 MB
2024-04-11T09:59:14,696 | DEBUG | (WhisperCppEngine:362) - whisper_init_state: kv cross size =  147.46 MB
2024-04-11T09:59:14,696 | DEBUG | (WhisperCppEngine:362) - whisper_init_state: compute buffer (conv)   =   25.61 MB
2024-04-11T09:59:14,697 | DEBUG | (WhisperCppEngine:362) - whisper_init_state: compute buffer (encode) =  170.28 MB
2024-04-11T09:59:14,698 | DEBUG | (WhisperCppEngine:362) - whisper_init_state: compute buffer (cross)  =    7.85 MB
2024-04-11T09:59:14,699 | DEBUG | (WhisperCppEngine:362) - whisper_init_state: compute buffer (decode) =   98.32 MB
2024-04-11T09:59:16,022 | DEBUG | (WhisperCppEngine:362) - 
2024-04-11T09:59:16,023 | DEBUG | (WhisperCppEngine:362) - system_info: n_threads = 8 / 24 | AVX = 1 | AVX2 = 1 | AVX512 = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | METAL = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | CUDA = 0 | COREML = 0 | OPENVINO = 0 | 
2024-04-11T09:59:16,023 | DEBUG | (WhisperCppEngine:362) - 
2024-04-11T09:59:16,023 | DEBUG | (WhisperCppEngine:362) - main: processing '/srv/opencast/workspace/mediapackage/a225fa83-3181-4b78-b169-e2a5a904607b/d323609e-6f30-4e4b-aa4a-e1f2aeebf64c/HU_LCP_007_20221021_091000_S2R1.wav' (96536917 samples, 6033.6 sec), 8 threads, 1 processors, 5 beams + best of 5, lang = de, task = transcribe, timestamps = 1 ...
2024-04-11T09:59:16,023 | DEBUG | (WhisperCppEngine:362) - 
2024-04-11T09:59:32,096 | DEBUG | (WhisperCppEngine:362) - 
...
2024-04-11T11:19:22,512 | DEBUG | (WhisperCppEngine:362) - output_vtt: failed to open '/srv/opencast/workspace/collection/subtitles/job-12146265/HU_LCP_007_20221021_091000_S2R1.vtt' for writing
2024-04-11T11:19:22,512 | DEBUG | (WhisperCppEngine:362) - output_json: failed to open '/srv/opencast/workspace/collection/subtitles/job-12146265/HU_LCP_007_20221021_091000_S2R1.json' for writing
2024-04-11T11:19:22,537 | DEBUG | (WhisperCppEngine:362) - 
2024-04-11T11:19:22,537 | DEBUG | (WhisperCppEngine:362) - whisper_print_timings:     load time =   600.54 ms
2024-04-11T11:19:22,537 | DEBUG | (WhisperCppEngine:362) - whisper_print_timings:     fallbacks =   4 p /  34 h
2024-04-11T11:19:22,537 | DEBUG | (WhisperCppEngine:362) - whisper_print_timings:      mel time =  3702.11 ms
2024-04-11T11:19:22,537 | DEBUG | (WhisperCppEngine:362) - whisper_print_timings:   sample time = 74343.51 ms / 114438 runs (    0.65 ms per run)
2024-04-11T11:19:22,537 | DEBUG | (WhisperCppEngine:362) - whisper_print_timings:   encode time = 2781819.75 ms /   250 runs (11127.28 ms per run)
2024-04-11T11:19:22,537 | DEBUG | (WhisperCppEngine:362) - whisper_print_timings:   decode time = 43027.06 ms /  1515 runs (   28.40 ms per run)
2024-04-11T11:19:22,537 | DEBUG | (WhisperCppEngine:362) - whisper_print_timings:   batchd time = 1414845.75 ms / 111659 runs (   12.67 ms per run)
2024-04-11T11:19:22,537 | DEBUG | (WhisperCppEngine:362) - whisper_print_timings:   prompt time = 488239.47 ms / 56527 runs (    8.64 ms per run)
2024-04-11T11:19:22,537 | DEBUG | (WhisperCppEngine:362) - whisper_print_timings:    total time = 4808441.50 ms
2024-04-11T11:19:22,706 | DEBUG | (WhisperCppEngine:362) - 
2024-04-11T11:19:22,708 | INFO  | (WhisperCppEngine:368) - WhisperC++ process finished with exit code 0
2024-04-11T11:19:22,709 | INFO  | (WhisperCppEngine:385) - Transcription failed closing WhisperC++ transcription process for: /srv/opencast/workspace/mediapackage/a225fa83-3181-4b78-b169-e2a5a904607b/d323609e-6f30-4e4b-aa4a-e1f2aeebf64c/HU_LCP_007_20221021_091000_S2R1.wav
2024-04-11T11:19:22,799 | INFO  | (ServiceRegistryJpaImpl:2268) - State set to WARNING for current service org.opencastproject.speechtotext on host https://opencast3.cms.hu-berlin.de
2024-04-11T11:19:23,348 | ERROR | (AbstractJobProducer$JobRunner:343) - Error handling operation 'speechtotext':
org.opencastproject.speechtotext.api.SpeechToTextServiceException: Error while generating subtitle from https://domain.com/files/mediapackage/a225fa83-3181-4b78-b169-e2a5a904607b/d323609e-6f30-4e4b-aa4a-e1f2aeebf64c/HU_LCP_007_20221021_091000_S2R1.wav
	at org.opencastproject.speechtotext.impl.SpeechToTextServiceImpl.process(SpeechToTextServiceImpl.java:165) ~[?:?]
	at org.opencastproject.job.api.AbstractJobProducer$JobRunner.call(AbstractJobProducer.java:313) [!/:?]
	at org.opencastproject.job.api.AbstractJobProducer$JobRunner.call(AbstractJobProducer.java:272) [!/:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: org.opencastproject.speechtotext.api.SpeechToTextEngineException: org.opencastproject.speechtotext.api.SpeechToTextEngineException: WhisperC++ produced no output
	at org.opencastproject.speechtotext.impl.engine.WhisperCppEngine.generateSubtitlesFile(WhisperCppEngine.java:386) ~[?:?]
	at org.opencastproject.speechtotext.impl.SpeechToTextServiceImpl.process(SpeechToTextServiceImpl.java:154) ~[?:?]
	... 6 more
Caused by: org.opencastproject.speechtotext.api.SpeechToTextEngineException: WhisperC++ produced no output
	at org.opencastproject.speechtotext.impl.engine.WhisperCppEngine.generateSubtitlesFile(WhisperCppEngine.java:381) ~[?:?]
	at org.opencastproject.speechtotext.impl.SpeechToTextServiceImpl.process(SpeechToTextServiceImpl.java:154) ~[?:?]
	... 6 more
```
**Server environment:**

    OS: Debian 12.x
    Distribution: 1x adminpresentation + 4x worker
    whisper-version:  [v1.5.4](https://github.com/ggerganov/whisper.cpp/releases/tag/v1.5.4)
    OC Version: 15.3
    Java Version: 17
    Installation method for OC & whisper.cpp: dpkg packages

**Comment by ziegenberg** [comment]
What happens between those two lines?

```
2024-04-11T09:59:32,096 | DEBUG | (WhisperCppEngine:362) - 
...
2024-04-11T11:19:22,512 | DEBUG | (WhisperCppEngine:362) - output_vtt: failed to open '/srv/opencast/workspace/collection/subtitles/job-12146265/HU_LCP_007_20221021_091000_S2R1.vtt' for writing
```

**Comment by ziegenberg** [comment]
Can you run just this whisper.cpp command on this box?

```bash
whisper.cpp --model /usr/share/whisper.cpp/medium.bin/ggml-medium.bin -ovtt -oj --output-file /srv/opencast/workspace/collection/subtitles/job-12146265/HU_LCP_007_20221021_091000_S2R1 -t 8 --language de /srv/opencast/workspace/mediapackage/a225fa83-3181-4b78-b169-e2a5a904607b/d323609e-6f30-4e4b-aa4a-e1f2aeebf64c/HU_LCP_007_20221021_091000_S2R1.wav
```

Please post the output and if it's inconclusive you might want to add `--debug-mode` to it.

**Comment by mwuttke** [comment]
> What happens between those two lines?
> 
> ```
> 2024-04-11T09:59:32,096 | DEBUG | (WhisperCppEngine:362) - 
> ...
> 2024-04-11T11:19:22,512 | DEBUG | (WhisperCppEngine:362) - output_vtt: failed to open '/srv/opencast/workspace/collection/subtitles/job-12146265/HU_LCP_007_20221021_091000_S2R1.vtt' for writing
> ```

There you can find the transcriptions, line by line for one hour, because of the DEBUG mode. ;-)

**Comment by gregorydlogan** [comment]
Heh, I feel like that ought to be slightly more than a debug log entry...

Any idea what's causing it? The mount is probably up since whisper is reading the file, right? Or does it fail part way through, causing whisper to fail, and the write to fail? Although in that case I would expect the whisper error code to be non-zero which ought to trigger different logging.

**Comment by mwuttke** [comment]
> Can you run just this whisper.cpp command on this box?
> 
> ```shell
> whisper.cpp --model /usr/share/whisper.cpp/medium.bin/ggml-medium.bin -ovtt -oj --output-file /srv/opencast/workspace/collection/subtitles/job-12146265/HU_LCP_007_20221021_091000_S2R1 -t 8 --language de /srv/opencast/workspace/mediapackage/a225fa83-3181-4b78-b169-e2a5a904607b/d323609e-6f30-4e4b-aa4a-e1f2aeebf64c/HU_LCP_007_20221021_091000_S2R1.wav
> ```
> 
> Please post the output and if it's inconclusive you might want to add `--debug-mode` to it.

No, these are only temporary files and folders. These are deleted at the end.

**Comment by mwuttke** [comment]
Hello @gregorydlogan. 
The transcription runs cleanly to the end. As you can see from the logs. I just hadn't copied it. The mount point is also retained until the end. This is specified on the server side and can also be written by the user opencast. If I understand the log entry correctly, however, the result of the transcription cannot be saved to the file provided for this purpose at the end. Up to this point, the transcription is probably kept in RAM or written to some temporary file.

**Comment by gregorydlogan** [comment]
Hrm... That long of a processing time...  What *else* ran between whisper start, and the error?  Could the directory be getting cleaned up by the workspace cleaner?

**Comment by Odrec** [comment]
Some notes from reading this against current `develop`, in case it helps whoever picks
this up next.

**This is not the "whisper output not consumed" bug from #5268.** Those two get grouped
together, but they are different failures. The `WhisperCppEngine:362` DEBUG lines here run
for the full ~80 minutes between 09:59 and 11:19, so output *was* being consumed
throughout — a full pipe buffer would have stalled the process early and silently. As
@mwuttke says above, whisper.cpp ran cleanly to the end; it failed only when writing its
result:

```
output_vtt:  failed to open '.../job-12146265/HU_LCP_007_20221021_091000_S2R1.vtt'  for writing
output_json: failed to open '.../job-12146265/HU_LCP_007_20221021_091000_S2R1.json' for writing
```

For reference, the #5268 fix (`68c2ed2843`, in `r/15.x` onward) added exactly that output
consumption, and it is present in `WhisperCppEngine` on `develop` today. So it is not
missing here — it is just not the problem.

**Where that path comes from.** `SpeechToTextServiceImpl` creates the job directory,
hands it to the engine, and removes it in a `finally` block:

https://github.com/opencast/opencast/blob/develop/modules/speech-to-text-impl/src/main/java/org/opencastproject/speechtotext/impl/SpeechToTextServiceImpl.java#L148-L167

`collection/subtitles/job-<id>` sits under the workspace root (`wsRoot`,
`/srv/opencast/workspace` in this deployment), so anything operating on the workspace root
by age can reach it.

**On @gregorydlogan's last question — yes, the workspace cleaner can do this.**
`WorkspaceImpl.cleanup(maxAgeInSeconds)` recursively cleans the entire workspace root by
file age, with no exclusion for jobs that are currently running. The source carries an
explicit warning about it:

> Warn if time is very short since this operation is dangerous and \*should\* only be a
> fallback for if stuff remained in the workspace due to some errors. If we have a very
> short maxAge, we may delete file which are currently being processed.

The timing fits the "only long videos" symptom: whisper.cpp opens its output files only at
the *very end* of the run, so `job-<id>/` sits untouched for the entire transcription.
Short videos finish before a cleanup pass can reach them; a 90-minute one does not. This
requires a non-default configuration — the shipped values are
`cleanup.max.age=2592000` (30 days) and `cleanup.period=86400` (24h) in
`etc/custom.properties` — so it would only bite a deployment that lowered `max.age`.

I could not narrow it further than that from the logs alone, and I have not reproduced it.
Worth noting for anyone testing: whether `job-12146265/` still exists after a failure
distinguishes the cleaner from a filesystem-level write refusal. (The mount itself was
already checked above and was up and writable.)

**One thing looks worth fixing regardless of the root cause.** whisper.cpp's write failure
is visible only at DEBUG, and the engine does not treat it as an error — whisper.cpp still
exits 0, so `execCommand` is satisfied, and the job then fails at

https://github.com/opencast/opencast/blob/develop/modules/speech-to-text-impl/src/main/java/org/opencastproject/speechtotext/impl/engine/WhisperCppEngine.java#L536-L541

with `WhisperC++ produced no output` — which says nothing about the write having failed.
@gregorydlogan made this point above ("I feel like that ought to be slightly more than a
debug log entry"). Checking that the expected output file exists and surfacing whisper's
own `failed to open` line would turn a silent hour-long dead end into an actionable error,
whatever the underlying cause turns out to be.

---
*AI usage: this analysis was done with the assistance of Claude (Anthropic), used to read
the source, correlate it with the log above, and draft this comment. The code references,
quoted source, and commit/branch claims were verified against the repository. The
workspace-cleaner explanation is a hypothesis consistent with the log; it was not
reproduced.*

**Comment by gregorydlogan** [comment]
@mwuttke is this still a thing with more recent OC + whisper combos?  If so, can you confirm the `cleanup.max.age` config value (on all nodes), and/or that said cleanup definitely *did not* run on *any node* during the whisper processing time?
