### ISSUE TITLE
RemoteUserAndOrganizationFilter rejects unknown named users, instead allowing ANONYMOUS access

### ISSUE THREAD

**Issue by karendolan** [opencast/opencast#5951]
**Describe the bug**

Unknown but non-anonymous users are currently FORBIDDEN from accessing ANONYMOUS endpoints.

**To Reproduce**

1. Use the default ROLE_ANONYOUS for the Series Service GET endpoint in the my_default_org security. [1]
2. Set up your Engage node to have a different authentication provider than your admin node. 
3. Set up your SeriesRemote to run on your Engage Node (default)
4. Set up your SeriesImp to run on your Admin Node (default)
5. Allow a user to authenticate on the Engage node.
6. The user attempts to use the Series Service on Engage. This invokes a SeriesRemote request from Engage to SeriesImpl on Admin.

**Expected behavior**

The user is able to access the ANONYMOUS endpoints of the series service on the Admin node.
The user only receives a FORBIDDEN if a non-anonymous endpoint is invoked with their unknown user id.

**Actual behavior**

- The ANONYMOUS endpoint returns a HTTP 403 Forbidden response.
- The Engage logs contains:
```
2024-06-24T18:21:53,633 | DEBUG | 249 | (SecurityServiceSpringImpl:129) - Authenticated user 'SallyAuthenticatedOnEngage' could not be found in any of the current UserProviders. Continuing anyway...
2024-06-24T18:21:53,633 | TRACE | 249 | (RemoteUserAndOrganizationFilter:151) - Request organization remains 'mh_default_org'
2024-06-24T18:21:53,633 | TRACE | 249 | (RemoteUserAndOrganizationFilter:265) - Executing the filter chain with user 'SallyAuthenticatedOnEngage@mh_default_org'
2024-06-24T18:21:53,649 | WARN  | 249 | (RemoteBase:227) - Service at http://myadmin.internal.edu/series/20220224801.xml returned unexpected response code 403
2024-06-24T18:21:53,649 | WARN  | 249 | (RemoteBase:244) - All services of type 'org.opencastproject.series' are in unknown state, abort remote call 20220224801.xml
2024-06-24T18:21:53,649 | ERROR | 249 | (SeriesServiceRemoteImpl:299) - Could not retrieve series: Unable to get series from remote series index
2024-06-24T18:21:53,650 | WARN  | 249 | (WebApplicationExceptionMapper:73) - javax.ws.rs.WebApplicationException: HTTP 500 Internal Server Error
        at org.opencastproject.series.remote.SeriesServiceRemoteImpl.getSeriesJSON(SeriesServiceRemoteImpl.java:300)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        ....
```        
- The Admin logs contains: `2024-06-24T18:49:44,120 | WARN  | 416 | (RemoteUserAndOrganizationFilter:177) - Unable to switch to non-existing user 'SallyAuthenticatedOnEngage' as specified in request header X-Opencast-Matterhorn-User`

** References **

[1] https://github.com/opencast/opencast/blob/develop/etc/security/mh_default_org.xml#L322-L323
[2]https://github.com/opencast/opencast/blob/develop/modules/kernel/src/main/java/org/opencastproject/kernel/security/RemoteUserAndOrganizationFilter.java#L169-L181

**Comment by karendolan** [comment]
`If no user has been provider by the request create a virtual user` of ANONYMOUS
https://github.com/opencast/opencast/blob/develop/modules/kernel/src/main/java/org/opencastproject/kernel/security/RemoteUserAndOrganizationFilter.java#L248-L251

But if a user is provided, and there is any issue, FORBIDDEN!
